;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; action
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(ns config.action
(:require
            [config.config :as c]))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; action glyphs
(def k_lc (c/mk c/_lc))
(def k_lo (c/mk c/_lo))
(def k_lt (c/mk c/_lt))
(def k_ls (c/mk c/_ls))

(def kp_lc (c/mk c/P c/_lc))
(def kp_lo (c/mk c/P c/_lo))
(def kp_lt (c/mk c/P c/_lt))
(def kp_ls (c/mk c/P c/_ls))

(def k_db (c/mk c/_db))
(def k_re (c/mk c/_re))
(def k_rs (c/mk c/_rs))
(def k_ro (c/mk c/_ro))
(def k_rc (c/mk c/_rc))
(def k_sp (c/mk c/_sp))

(def ko_db (c/mk c/K c/O c/_db))
(def ko_re (c/mk c/K c/O c/_re))
(def ko_rs (c/mk c/K c/O c/_rs))
(def ko_ro (c/mk c/K c/O c/_ro))
(def ko_rc (c/mk c/K c/O c/_rc))
(def ko_sp (c/mk c/K c/O c/_sp))

(def kt_db (c/mk c/K c/T c/_db))
(def kt_re (c/mk c/K c/T c/_re))
(def kt_rs (c/mk c/K c/T c/_rs))
(def kt_ro (c/mk c/K c/T c/_ro))
(def kt_rc (c/mk c/K c/T c/_rc))
(def kt_sp (c/mk c/K c/T c/_sp))

(def kc_db (c/mk c/K c/C c/_db))
(def kc_re (c/mk c/K c/C c/_re))
(def kc_rs (c/mk c/K c/C c/_rs))
(def kc_ro (c/mk c/K c/C c/_ro))
(def kc_rc (c/mk c/K c/C c/_rc))
(def kc_sp (c/mk c/K c/C c/_sp))

(def kot_db (c/mk c/K c/O c/T c/_db))
(def kot_re (c/mk c/K c/O c/T c/_re))
(def kot_rs (c/mk c/K c/O c/T c/_rs))
(def kot_ro (c/mk c/K c/O c/T c/_ro))
(def kot_rc (c/mk c/K c/O c/T c/_rc))
(def kot_sp (c/mk c/K c/O c/T c/_sp))

(def koc_db (c/mk c/K c/O c/C c/_db))
(def koc_re (c/mk c/K c/O c/C c/_re))
(def koc_rs (c/mk c/K c/O c/C c/_rs))
(def koc_ro (c/mk c/K c/O c/C c/_ro))
(def koc_rc (c/mk c/K c/O c/C c/_rc))
(def koc_sp (c/mk c/K c/O c/C c/_sp))

(def ktc_db (c/mk c/K c/T c/C c/_db))
(def ktc_re (c/mk c/K c/T c/C c/_re))
(def ktc_rs (c/mk c/K c/T c/C c/_rs))
(def ktc_ro (c/mk c/K c/T c/C c/_ro))
(def ktc_rc (c/mk c/K c/T c/C c/_rc))
(def ktc_sp (c/mk c/K c/T c/C c/_sp))

(def kotc_db (c/mk c/K c/O c/T c/C c/_db))
(def kotc_re (c/mk c/K c/O c/T c/C c/_re))
(def kotc_rs (c/mk c/K c/O c/T c/C c/_rs))
(def kotc_ro (c/mk c/K c/O c/T c/C c/_ro))
(def kotc_rc (c/mk c/K c/O c/T c/C c/_rc))
(def kotc_sp (c/mk c/K c/O c/T c/C c/_sp))

(def ke_db (c/mk c/K c/E c/_db))
(def ke_re (c/mk c/K c/E c/_re))
(def ke_sp (c/mk c/K c/E c/_sp))
(def ke_lc (c/mk c/K c/E c/_lc))
(def ke_lo (c/mk c/K c/E c/_lo))
(def ke_lt (c/mk c/K c/E c/_lt))
(def ke_ls (c/mk c/K c/E c/_ls))
(def ke_esc (c/mk c/K c/E c/_esc))
(def ke_tab (c/mk c/K c/E c/_tab))

(def kw_db (c/mk c/K c/W c/_db))
(def kw_re (c/mk c/K c/W c/_re))
(def kw_rs (c/mk c/K c/W c/_rs))
(def kw_ro (c/mk c/K c/W c/_ro))
(def kw_rc (c/mk c/K c/W c/_rc))
(def kw_sp (c/mk c/K c/W c/_sp))

(def kq_db (c/mk c/K c/Q c/_db))
(def kq_re (c/mk c/K c/Q c/_re))
(def kq_sp (c/mk c/K c/Q c/_sp))
(def kq_lc (c/mk c/K c/Q c/_lc))
(def kq_lo (c/mk c/K c/Q c/_lo))
(def kq_lt (c/mk c/K c/Q c/_lt))
(def kq_ls (c/mk c/K c/Q c/_ls))
(def kq_esc (c/mk c/K c/Q c/_esc))
(def kq_tab (c/mk c/K c/Q c/_tab))

(def kewq_db (c/mk c/K c/E c/W c/Q c/_db))
(def kewq_re (c/mk c/K c/E c/W c/Q c/_re))
(def kewq_rs (c/mk c/K c/E c/W c/Q c/_rs))
(def kewq_ro (c/mk c/K c/E c/W c/Q c/_ro))
(def kewq_rc (c/mk c/K c/E c/W c/Q c/_rc))
(def kewq_sp (c/mk c/K c/E c/W c/Q c/_sp))

(def ks_db (c/mk c/K c/S c/_db))
(def ks_re (c/mk c/K c/S c/_re))
(def ks_rs (c/mk c/K c/S c/_rs))
(def ks_ro (c/mk c/K c/S c/_ro))
(def ks_rc (c/mk c/K c/S c/_rc))
(def ks_sp (c/mk c/K c/S c/_sp))

(def kos_db (c/mk c/K c/O c/S c/_db))
(def kos_re (c/mk c/K c/O c/S c/_re))
(def kos_rs (c/mk c/K c/O c/S c/_rs))
(def kos_ro (c/mk c/K c/O c/S c/_ro))
(def kos_rc (c/mk c/K c/O c/S c/_rc))
(def kos_sp (c/mk c/K c/O c/S c/_sp))

(def kts_db (c/mk c/K c/T c/S c/_db))
(def kts_re (c/mk c/K c/T c/S c/_re))
(def kts_rs (c/mk c/K c/T c/S c/_rs))
(def kts_ro (c/mk c/K c/T c/S c/_ro))
(def kts_rc (c/mk c/K c/T c/S c/_rc))
(def kts_sp (c/mk c/K c/T c/S c/_sp))

(def kcs_db (c/mk c/K c/C c/S c/_db))
(def kcs_re (c/mk c/K c/C c/S c/_re))
(def kcs_rs (c/mk c/K c/C c/S c/_rs))
(def kcs_ro (c/mk c/K c/C c/S c/_ro))
(def kcs_rc (c/mk c/K c/C c/S c/_rc))
(def kcs_sp (c/mk c/K c/C c/S c/_sp))

(def kots_db (c/mk c/K c/O c/T c/S c/_db))
(def kots_re (c/mk c/K c/O c/T c/S c/_re))
(def kots_rs (c/mk c/K c/O c/T c/S c/_rs))
(def kots_ro (c/mk c/K c/O c/T c/S c/_ro))
(def kots_rc (c/mk c/K c/O c/T c/S c/_rc))
(def kots_sp (c/mk c/K c/O c/T c/S c/_sp))

(def kocs_db (c/mk c/K c/O c/C c/S c/_db))
(def kocs_re (c/mk c/K c/O c/C c/_re))
(def kocs_rs (c/mk c/K c/O c/C c/S c/_rs))
(def kocs_ro (c/mk c/K c/O c/C c/S c/_ro))
(def kocs_rc (c/mk c/K c/O c/C c/S c/_rc))
(def kocs_sp (c/mk c/K c/O c/C c/S c/_sp))

(def ktcs_db (c/mk c/K c/T c/C c/S c/_db))
(def ktcs_re (c/mk c/K c/T c/C c/S c/_re))
(def ktcs_rs (c/mk c/K c/T c/C c/S c/_rs))
(def ktcs_ro (c/mk c/K c/T c/C c/S c/_ro))
(def ktcs_rc (c/mk c/K c/T c/C c/S c/_rc))
(def ktcs_sp (c/mk c/K c/T c/C c/S c/_sp))

(def kotcs_db (c/mk c/K c/O c/T c/C c/R c/_db))
(def kotcs_re (c/mk c/K c/O c/T c/C c/R c/_re))
(def kotcs_rs (c/mk c/K c/O c/T c/C c/R c/_rs))
(def kotcs_ro (c/mk c/K c/O c/T c/C c/R c/_ro))
(def kotcs_rc (c/mk c/K c/O c/T c/C c/R c/_rc))
(def kotcs_sp (c/mk c/K c/O c/T c/C c/R c/_sp))

(def ker_db (c/mk c/K c/E c/R c/_db))
(def ker_re (c/mk c/K c/E c/R c/_re))
(def ker_sp (c/mk c/K c/E c/R c/_sp))
(def ker_lc (c/mk c/K c/E c/R c/_lc))
(def ker_lo (c/mk c/K c/E c/R c/_lo))
(def ker_lt (c/mk c/K c/E c/R c/_lt))
(def ker_ls (c/mk c/K c/E c/R c/_ls))
(def ker_esc (c/mk c/K c/E c/R c/_esc))
(def ker_tab (c/mk c/K c/E c/R c/_tab))

(def kws_db (c/mk c/K c/W c/S c/_db))
(def kws_re (c/mk c/K c/W c/S c/_re))
(def kws_rs (c/mk c/K c/W c/S c/_rs))
(def kws_ro (c/mk c/K c/W c/S c/_ro))
(def kws_rc (c/mk c/K c/W c/S c/_rc))
(def kws_sp (c/mk c/K c/W c/S c/_sp))

(def kqr_db (c/mk c/K c/Q c/R c/_db))
(def kqr_re (c/mk c/K c/Q c/R c/_re))
(def kqr_sp (c/mk c/K c/Q c/R c/_sp))
(def kqr_lc (c/mk c/K c/Q c/R c/_lc))
(def kqr_lo (c/mk c/K c/Q c/R c/_lo))
(def kqr_lt (c/mk c/K c/Q c/R c/_lt))
(def kqr_ls (c/mk c/K c/Q c/R c/_ls))
(def kqr_esc (c/mk c/K c/Q c/R c/_esc))
(def kqr_tab (c/mk c/K c/Q c/R c/_tab))

(def kewqs_db (c/mk c/K c/E c/W c/Q c/S c/_db))
(def kewqs_re (c/mk c/K c/E c/W c/Q c/S c/_re))
(def kewqs_rs (c/mk c/K c/E c/W c/Q c/S c/_rs))
(def kewqs_ro (c/mk c/K c/E c/W c/Q c/S c/_ro))
(def kewqs_rc (c/mk c/K c/E c/W c/Q c/S c/_rc))
(def kewqs_sp (c/mk c/K c/E c/W c/Q c/S c/_sp))

(def kp_db   (c/mk c/P c/_db))
(def kp_re   (c/mk c/P c/_re))
(def kp_rs   (c/mk c/P c/_rs))
(def kp_ro   (c/mk c/P c/_ro))
(def kp_rc   (c/mk c/P c/_rc))
(def kp_sp   (c/mk c/P c/_sp))

(def kop_db  (c/mk c/K c/O c/P c/_db))
(def kop_re  (c/mk c/K c/O c/P c/_re))
(def kop_rs  (c/mk c/K c/O c/P c/_rs))
(def kop_ro  (c/mk c/K c/O c/P c/_ro))
(def kop_rc  (c/mk c/K c/O c/P c/_rc))
(def kop_sp  (c/mk c/K c/O c/P c/_sp))

(def ktp_db  (c/mk c/K c/T c/P c/_db))
(def ktp_re  (c/mk c/K c/T c/P c/_re))
(def ktp_rs  (c/mk c/K c/T c/P c/_rs))
(def ktp_ro  (c/mk c/K c/T c/P c/_ro))
(def ktp_rc  (c/mk c/K c/T c/P c/_rc))
(def ktp_sp  (c/mk c/K c/T c/P c/_sp))

(def kcp_db  (c/mk c/K c/C c/P c/_db))
(def kcp_re  (c/mk c/K c/C c/P c/_re))
(def kcp_rs  (c/mk c/K c/C c/P c/_rs))
(def kcp_ro  (c/mk c/K c/C c/P c/_ro))
(def kcp_rc  (c/mk c/K c/C c/P c/_rc))
(def kcp_sp  (c/mk c/K c/C c/P c/_sp))

(def kotp_db (c/mk c/K c/O c/T c/P c/_db))
(def kotp_re (c/mk c/K c/O c/T c/P c/_re))
(def kotp_rs (c/mk c/K c/O c/T c/P c/_rs))
(def kotp_ro (c/mk c/K c/O c/T c/P c/_ro))
(def kotp_rc (c/mk c/K c/O c/T c/P c/_rc))
(def kotp_sp (c/mk c/K c/O c/T c/P c/_sp))

(def kocp_db (c/mk c/K c/O c/C c/P c/_db))
(def kocp_re (c/mk c/K c/O c/C c/P c/_re))
(def kocp_rs (c/mk c/K c/O c/C c/P c/_rs))
(def kocp_ro (c/mk c/K c/O c/C c/P c/_ro))
(def kocp_rc (c/mk c/K c/O c/C c/P c/_rc))
(def kocp_sp (c/mk c/K c/O c/C c/P c/_sp))

(def ktcp_db (c/mk c/K c/T c/C c/P c/_db))
(def ktcp_re (c/mk c/K c/T c/C c/P c/_re))
(def ktcp_rs (c/mk c/K c/T c/C c/P c/_rs))
(def ktcp_ro (c/mk c/K c/T c/C c/P c/_ro))
(def ktcp_rc (c/mk c/K c/T c/C c/P c/_rc))
(def ktcp_sp (c/mk c/K c/T c/C c/P c/_sp))

(def kotcp_db (c/mk c/K c/O c/T c/C c/P c/_db))
(def kotcp_re (c/mk c/K c/O c/T c/C c/P c/_re))
(def kotcp_rs (c/mk c/K c/O c/T c/C c/P c/_rs))
(def kotcp_ro (c/mk c/K c/O c/T c/C c/P c/_ro))
(def kotcp_rc (c/mk c/K c/O c/T c/C c/P c/_rc))
(def kotcp_sp (c/mk c/K c/O c/T c/C c/P c/_sp))

(def kep_db (c/mk c/K c/E c/P c/_db))
(def kep_re (c/mk c/K c/E c/P c/_re))
(def kep_sp (c/mk c/K c/E c/P c/_sp))
(def kep_lc (c/mk c/K c/E c/P c/_lc))
(def kep_lo (c/mk c/K c/E c/P c/_lo))
(def kep_lt (c/mk c/K c/E c/P c/_lt))
(def kep_ls (c/mk c/K c/E c/P c/_ls))
(def kep_esc (c/mk c/K c/E c/P c/_esc))
(def kep_tab (c/mk c/K c/E c/P c/_tab))

(def kwp_db  (c/mk c/K c/W c/P c/_db))
(def kwp_re  (c/mk c/K c/W c/P c/_re))
(def kwp_rs  (c/mk c/K c/W c/P c/_rs))
(def kwp_ro  (c/mk c/K c/W c/P c/_ro))
(def kwp_rc  (c/mk c/K c/W c/P c/_rc))
(def kwp_sp  (c/mk c/K c/W c/P c/_sp))

(def kqp_db (c/mk c/K c/Q c/P c/_db))
(def kqp_re (c/mk c/K c/Q c/P c/_re))
(def kqp_sp (c/mk c/K c/Q c/P c/_sp))
(def kqp_lc (c/mk c/K c/Q c/P c/_lc))
(def kqp_lo (c/mk c/K c/Q c/P c/_lo))
(def kqp_lt (c/mk c/K c/Q c/P c/_lt))
(def kqp_ls (c/mk c/K c/Q c/P c/_ls))
(def kqp_esc (c/mk c/K c/Q c/P c/_esc))
(def kqp_tab (c/mk c/K c/Q c/P c/_tab))

(def kewqp_db  (c/mk c/K c/E c/W c/Q c/P c/_db))
(def kewqp_re  (c/mk c/K c/E c/W c/Q c/P c/_re))
(def kewqp_rs  (c/mk c/K c/E c/W c/Q c/P c/_rs))
(def kewqp_ro  (c/mk c/K c/E c/W c/Q c/P c/_ro))
(def kewqp_rc  (c/mk c/K c/E c/W c/Q c/P c/_rc))
(def kewqp_sp  (c/mk c/K c/E c/W c/Q c/P c/_sp))

(def ksp_db   (c/mk c/K c/S c/P c/_db))
(def ksp_re   (c/mk c/K c/S c/P c/_re))
(def ksp_rs   (c/mk c/K c/S c/P c/_rs))
(def ksp_ro   (c/mk c/K c/S c/P c/_ro))
(def ksp_rc   (c/mk c/K c/S c/P c/_rc))
(def ksp_sp   (c/mk c/K c/S c/P c/_sp))

(def kosp_db  (c/mk c/K c/O c/S c/P c/_db))
(def kosp_re  (c/mk c/K c/O c/S c/P c/_re))
(def kosp_rs  (c/mk c/K c/O c/S c/P c/_rs))
(def kosp_ro  (c/mk c/K c/O c/S c/P c/_ro))
(def kosp_rc  (c/mk c/K c/O c/S c/P c/_rc))
(def kosp_sp  (c/mk c/K c/O c/S c/P c/_sp))

(def ktsp_db  (c/mk c/K c/T c/S c/P c/_db))
(def ktsp_re  (c/mk c/K c/T c/S c/P c/_re))
(def ktsp_rs  (c/mk c/K c/T c/S c/P c/_rs))
(def ktsp_ro  (c/mk c/K c/T c/S c/P c/_ro))
(def ktsp_rc  (c/mk c/K c/T c/S c/P c/_rc))
(def ktsp_sp  (c/mk c/K c/T c/S c/P c/_sp))

(def kcsp_db  (c/mk c/K c/C c/S c/P c/_db))
(def kcsp_re  (c/mk c/K c/C c/S c/P c/_re))
(def kcsp_rs  (c/mk c/K c/C c/S c/P c/_rs))
(def kcsp_ro  (c/mk c/K c/C c/S c/P c/_ro))
(def kcsp_rc  (c/mk c/K c/C c/S c/P c/_rc))
(def kcsp_sp  (c/mk c/K c/C c/S c/P c/_sp))

(def kotsp_db (c/mk c/K c/O c/T c/S c/P c/_db))
(def kotsp_re (c/mk c/K c/O c/T c/S c/P c/_re))
(def kotsp_rs (c/mk c/K c/O c/T c/S c/P c/_rs))
(def kotsp_ro (c/mk c/K c/O c/T c/S c/P c/_ro))
(def kotsp_rc (c/mk c/K c/O c/T c/S c/P c/_rc))
(def kotsp_sp (c/mk c/K c/O c/T c/S c/P c/_sp))

(def kocsp_db (c/mk c/K c/O c/C c/S c/P c/_db))
(def kocsp_re (c/mk c/K c/O c/C c/S c/P c/_re))
(def kocsp_rs (c/mk c/K c/O c/C c/S c/P c/_rs))
(def kocsp_ro (c/mk c/K c/O c/C c/S c/P c/_ro))
(def kocsp_rc (c/mk c/K c/O c/C c/S c/P c/_rc))
(def kocsp_sp (c/mk c/K c/O c/C c/S c/P c/_sp))

(def ktcsp_db (c/mk c/K c/T c/C c/S c/P c/_db))
(def ktcsp_re (c/mk c/K c/T c/C c/S c/P c/_re))
(def ktcsp_rs (c/mk c/K c/T c/C c/S c/P c/_rs))
(def ktcsp_ro (c/mk c/K c/T c/C c/S c/P c/_ro))
(def ktcsp_rc (c/mk c/K c/T c/C c/S c/P c/_rc))
(def ktcsp_sp (c/mk c/K c/T c/C c/S c/P c/_sp))

(def kotcsp_db (c/mk c/K c/O c/T c/C c/R c/P c/_db))
(def kotcsp_re (c/mk c/K c/O c/T c/C c/R c/P c/_re))
(def kotcsp_rs (c/mk c/K c/O c/T c/C c/R c/P c/_rs))
(def kotcsp_ro (c/mk c/K c/O c/T c/C c/R c/P c/_ro))
(def kotcsp_rc (c/mk c/K c/O c/T c/C c/R c/P c/_rc))
(def kotcsp_sp (c/mk c/K c/O c/T c/C c/R c/P c/_sp))

(def kerp_db (c/mk c/K c/E c/R c/P c/_db))
(def kerp_re (c/mk c/K c/E c/R c/P c/_re))
(def kerp_sp (c/mk c/K c/E c/R c/P c/_sp))
(def kerp_lc (c/mk c/K c/E c/R c/P c/_lc))
(def kerp_lo (c/mk c/K c/E c/R c/P c/_lo))
(def kerp_lt (c/mk c/K c/E c/R c/P c/_lt))
(def kerp_ls (c/mk c/K c/E c/R c/P c/_ls))
(def kerp_esc (c/mk c/K c/E c/R c/P c/_esc))
(def kerp_tab (c/mk c/K c/E c/R c/P c/_tab))

(def kwsp_db  (c/mk c/K c/W c/S c/P c/_db))
(def kwsp_re  (c/mk c/K c/W c/S c/P c/_re))
(def kwsp_rs  (c/mk c/K c/W c/S c/P c/_rs))
(def kwsp_ro  (c/mk c/K c/W c/S c/P c/_ro))
(def kwsp_rc  (c/mk c/K c/W c/S c/P c/_rc))
(def kwsp_sp  (c/mk c/K c/W c/S c/P c/_sp))

(def kqrp_db (c/mk c/K c/Q c/R c/P c/_db))
(def kqrp_re (c/mk c/K c/Q c/R c/P c/_re))
(def kqrp_sp (c/mk c/K c/Q c/R c/P c/_sp))
(def kqrp_lc (c/mk c/K c/Q c/R c/P c/_lc))
(def kqrp_lo (c/mk c/K c/Q c/R c/P c/_lo))
(def kqrp_lt (c/mk c/K c/Q c/R c/P c/_lt))
(def kqrp_ls (c/mk c/K c/Q c/R c/P c/_ls))
(def kqrp_esc (c/mk c/K c/Q c/R c/P c/_esc))
(def kqrp_tab (c/mk c/K c/Q c/R c/P c/_tab))

(def kewqsp_db  (c/mk c/K c/E c/W c/Q c/S c/P c/_db))
(def kewqsp_re  (c/mk c/K c/E c/W c/Q c/S c/P c/_re))
(def kewqsp_rs  (c/mk c/K c/E c/W c/Q c/S c/P c/_rs))
(def kewqsp_ro  (c/mk c/K c/E c/W c/Q c/S c/P c/_ro))
(def kewqsp_rc  (c/mk c/K c/E c/W c/Q c/S c/P c/_rc))
(def kewqsp_sp  (c/mk c/K c/E c/W c/Q c/S c/P c/_sp))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
