;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; alphabetic
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(ns config.alphabetic
(:require
            [config.config :as c]))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; alphabetic glyphs
(def k_a (c/mk c/_a))
(def k_b (c/mk c/_b))
(def k_c (c/mk c/_c))
(def k_d (c/mk c/_d))
(def k_e (c/mk c/_e))
(def k_f (c/mk c/_f))
(def k_g (c/mk c/_g))
(def k_h (c/mk c/_h))
(def k_i (c/mk c/_i))
(def k_j (c/mk c/_j))
(def k_k (c/mk c/_k))
(def k_l (c/mk c/_l))
(def k_m (c/mk c/_m))
(def k_n (c/mk c/_n))
(def k_o (c/mk c/_o))
(def k_p (c/mk c/_p))
(def k_q (c/mk c/_q))
(def k_r (c/mk c/_r))
(def k_s (c/mk c/_s))
(def k_t (c/mk c/_t))
(def k_u (c/mk c/_u))
(def k_v (c/mk c/_v))
(def k_w (c/mk c/_w))
(def k_x (c/mk c/_x))
(def k_y (c/mk c/_y))
(def k_z (c/mk c/_z))
(def k_rt (c/mk c/_rt))

(def ko_a (c/mk c/K c/O c/_a))
(def ko_b (c/mk c/K c/O c/_b))
(def ko_c (c/mk c/K c/O c/_c))
(def ko_d (c/mk c/K c/O c/_d))
(def ko_e (c/mk c/K c/O c/_e))
(def ko_f (c/mk c/K c/O c/_f))
(def ko_g (c/mk c/K c/O c/_g))
(def ko_h (c/mk c/K c/O c/_h))
(def ko_i (c/mk c/K c/O c/_i))
(def ko_j (c/mk c/K c/O c/_j))
(def ko_k (c/mk c/K c/O c/_k))
(def ko_l (c/mk c/K c/O c/_l))
(def ko_m (c/mk c/K c/O c/_m))
(def ko_n (c/mk c/K c/O c/_n))
(def ko_o (c/mk c/K c/O c/_o))
(def ko_p (c/mk c/K c/O c/_p))
(def ko_q (c/mk c/K c/O c/_q))
(def ko_r (c/mk c/K c/O c/_r))
(def ko_s (c/mk c/K c/O c/_s))
(def ko_t (c/mk c/K c/O c/_t))
(def ko_u (c/mk c/K c/O c/_u))
(def ko_v (c/mk c/K c/O c/_v))
(def ko_w (c/mk c/K c/O c/_w))
(def ko_x (c/mk c/K c/O c/_x))
(def ko_y (c/mk c/K c/O c/_y))
(def ko_z (c/mk c/K c/O c/_z))
(def ko_rt (c/mk c/K c/O c/_rt))

(def kt_a (c/mk c/K c/T c/_a))
(def kt_b (c/mk c/K c/T c/_b))
(def kt_c (c/mk c/K c/T c/_c))
(def kt_d (c/mk c/K c/T c/_d))
(def kt_e (c/mk c/K c/T c/_e))
(def kt_f (c/mk c/K c/T c/_f))
(def kt_g (c/mk c/K c/T c/_g))
(def kt_h (c/mk c/K c/T c/_h))
(def kt_i (c/mk c/K c/T c/_i))
(def kt_j (c/mk c/K c/T c/_j))
(def kt_k (c/mk c/K c/T c/_k))
(def kt_l (c/mk c/K c/T c/_l))
(def kt_m (c/mk c/K c/T c/_m))
(def kt_n (c/mk c/K c/T c/_n))
(def kt_o (c/mk c/K c/T c/_o))
(def kt_p (c/mk c/K c/T c/_p))
(def kt_q (c/mk c/K c/T c/_q))
(def kt_r (c/mk c/K c/T c/_r))
(def kt_s (c/mk c/K c/T c/_s))
(def kt_t (c/mk c/K c/T c/_t))
(def kt_u (c/mk c/K c/T c/_u))
(def kt_v (c/mk c/K c/T c/_v))
(def kt_w (c/mk c/K c/T c/_w))
(def kt_x (c/mk c/K c/T c/_x))
(def kt_y (c/mk c/K c/T c/_y))
(def kt_z (c/mk c/K c/T c/_z))
(def kt_rt (c/mk c/K c/T c/_rt))

(def kc_a (c/mk c/K c/C c/_a))
(def kc_b (c/mk c/K c/C c/_b))
(def kc_c (c/mk c/K c/C c/_c))
(def kc_d (c/mk c/K c/C c/_d))
(def kc_e (c/mk c/K c/C c/_e))
(def kc_f (c/mk c/K c/C c/_f))
(def kc_g (c/mk c/K c/C c/_g))
(def kc_h (c/mk c/K c/C c/_h))
(def kc_i (c/mk c/K c/C c/_i))
(def kc_j (c/mk c/K c/C c/_j))
(def kc_k (c/mk c/K c/C c/_k))
(def kc_l (c/mk c/K c/C c/_l))
(def kc_m (c/mk c/K c/C c/_m))
(def kc_n (c/mk c/K c/C c/_n))
(def kc_o (c/mk c/K c/C c/_o))
(def kc_p (c/mk c/K c/C c/_p))
(def kc_q (c/mk c/K c/C c/_q))
(def kc_r (c/mk c/K c/C c/_r))
(def kc_s (c/mk c/K c/C c/_s))
(def kc_t (c/mk c/K c/C c/_t))
(def kc_u (c/mk c/K c/C c/_u))
(def kc_v (c/mk c/K c/C c/_v))
(def kc_w (c/mk c/K c/C c/_w))
(def kc_x (c/mk c/K c/C c/_x))
(def kc_y (c/mk c/K c/C c/_y))
(def kc_z (c/mk c/K c/C c/_z))
(def kc_rt (c/mk c/K c/C c/_rt))

(def kot_a (c/mk c/K c/O c/T c/_a))
(def kot_b (c/mk c/K c/O c/T c/_b))
(def kot_c (c/mk c/K c/O c/T c/_c))
(def kot_d (c/mk c/K c/O c/T c/_d))
(def kot_e (c/mk c/K c/O c/T c/_e))
(def kot_f (c/mk c/K c/O c/T c/_f))
(def kot_g (c/mk c/K c/O c/T c/_g))
(def kot_h (c/mk c/K c/O c/T c/_h))
(def kot_i (c/mk c/K c/O c/T c/_i))
(def kot_j (c/mk c/K c/O c/T c/_j))
(def kot_k (c/mk c/K c/O c/T c/_k))
(def kot_l (c/mk c/K c/O c/T c/_l))
(def kot_m (c/mk c/K c/O c/T c/_m))
(def kot_n (c/mk c/K c/O c/T c/_n))
(def kot_o (c/mk c/K c/O c/T c/_o))
(def kot_p (c/mk c/K c/O c/T c/_p))
(def kot_q (c/mk c/K c/O c/T c/_q))
(def kot_r (c/mk c/K c/O c/T c/_r))
(def kot_s (c/mk c/K c/O c/T c/_s))
(def kot_t (c/mk c/K c/O c/T c/_t))
(def kot_u (c/mk c/K c/O c/T c/_u))
(def kot_v (c/mk c/K c/O c/T c/_v))
(def kot_w (c/mk c/K c/O c/T c/_w))
(def kot_x (c/mk c/K c/O c/T c/_x))
(def kot_y (c/mk c/K c/O c/T c/_y))
(def kot_z (c/mk c/K c/O c/T c/_z))
(def kot_rt (c/mk c/K c/O c/T c/_rt))

(def koc_a (c/mk c/K c/O c/C c/_a))
(def koc_b (c/mk c/K c/O c/C c/_b))
(def koc_c (c/mk c/K c/O c/C c/_c))
(def koc_d (c/mk c/K c/O c/C c/_d))
(def koc_e (c/mk c/K c/O c/C c/_e))
(def koc_f (c/mk c/K c/O c/C c/_f))
(def koc_g (c/mk c/K c/O c/C c/_g))
(def koc_h (c/mk c/K c/O c/C c/_h))
(def koc_i (c/mk c/K c/O c/C c/_i))
(def koc_j (c/mk c/K c/O c/C c/_j))
(def koc_k (c/mk c/K c/O c/C c/_k))
(def koc_l (c/mk c/K c/O c/C c/_l))
(def koc_m (c/mk c/K c/O c/C c/_m))
(def koc_n (c/mk c/K c/O c/C c/_n))
(def koc_o (c/mk c/K c/O c/C c/_o))
(def koc_p (c/mk c/K c/O c/C c/_p))
(def koc_q (c/mk c/K c/O c/C c/_q))
(def koc_r (c/mk c/K c/O c/C c/_r))
(def koc_s (c/mk c/K c/O c/C c/_s))
(def koc_t (c/mk c/K c/O c/C c/_t))
(def koc_u (c/mk c/K c/O c/C c/_u))
(def koc_v (c/mk c/K c/O c/C c/_v))
(def koc_w (c/mk c/K c/O c/C c/_w))
(def koc_x (c/mk c/K c/O c/C c/_x))
(def koc_y (c/mk c/K c/O c/C c/_y))
(def koc_z (c/mk c/K c/O c/C c/_z))
(def koc_rt (c/mk c/K c/O c/C c/_rt))

(def ktc_a (c/mk c/K c/T c/C c/_a))
(def ktc_b (c/mk c/K c/T c/C c/_b))
(def ktc_c (c/mk c/K c/T c/C c/_c))
(def ktc_d (c/mk c/K c/T c/C c/_d))
(def ktc_e (c/mk c/K c/T c/C c/_e))
(def ktc_f (c/mk c/K c/T c/C c/_f))
(def ktc_g (c/mk c/K c/T c/C c/_g))
(def ktc_h (c/mk c/K c/T c/C c/_h))
(def ktc_i (c/mk c/K c/T c/C c/_i))
(def ktc_j (c/mk c/K c/T c/C c/_j))
(def ktc_k (c/mk c/K c/T c/C c/_k))
(def ktc_l (c/mk c/K c/T c/C c/_l))
(def ktc_m (c/mk c/K c/T c/C c/_m))
(def ktc_n (c/mk c/K c/T c/C c/_n))
(def ktc_o (c/mk c/K c/T c/C c/_o))
(def ktc_p (c/mk c/K c/T c/C c/_p))
(def ktc_q (c/mk c/K c/T c/C c/_q))
(def ktc_r (c/mk c/K c/T c/C c/_r))
(def ktc_s (c/mk c/K c/T c/C c/_s))
(def ktc_t (c/mk c/K c/T c/C c/_t))
(def ktc_u (c/mk c/K c/T c/C c/_u))
(def ktc_v (c/mk c/K c/T c/C c/_v))
(def ktc_w (c/mk c/K c/T c/C c/_w))
(def ktc_x (c/mk c/K c/T c/C c/_x))
(def ktc_y (c/mk c/K c/T c/C c/_y))
(def ktc_z (c/mk c/K c/T c/C c/_z))
(def ktc_rt (c/mk c/K c/T c/C c/_rt))

(def kotc_a (c/mk c/K c/O c/T c/C c/_a))
(def kotc_b (c/mk c/K c/O c/T c/C c/_b))
(def kotc_c (c/mk c/K c/O c/T c/C c/_c))
(def kotc_d (c/mk c/K c/O c/T c/C c/_d))
(def kotc_e (c/mk c/K c/O c/T c/C c/_e))
(def kotc_f (c/mk c/K c/O c/T c/C c/_f))
(def kotc_g (c/mk c/K c/O c/T c/C c/_g))
(def kotc_h (c/mk c/K c/O c/T c/C c/_h))
(def kotc_i (c/mk c/K c/O c/T c/C c/_i))
(def kotc_j (c/mk c/K c/O c/T c/C c/_j))
(def kotc_k (c/mk c/K c/O c/T c/C c/_k))
(def kotc_l (c/mk c/K c/O c/T c/C c/_l))
(def kotc_m (c/mk c/K c/O c/T c/C c/_m))
(def kotc_n (c/mk c/K c/O c/T c/C c/_n))
(def kotc_o (c/mk c/K c/O c/T c/C c/_o))
(def kotc_p (c/mk c/K c/O c/T c/C c/_p))
(def kotc_q (c/mk c/K c/O c/T c/C c/_q))
(def kotc_r (c/mk c/K c/O c/T c/C c/_r))
(def kotc_s (c/mk c/K c/O c/T c/C c/_s))
(def kotc_t (c/mk c/K c/O c/T c/C c/_t))
(def kotc_u (c/mk c/K c/O c/T c/C c/_u))
(def kotc_v (c/mk c/K c/O c/T c/C c/_v))
(def kotc_w (c/mk c/K c/O c/T c/C c/_w))
(def kotc_x (c/mk c/K c/O c/T c/C c/_x))
(def kotc_y (c/mk c/K c/O c/T c/C c/_y))
(def kotc_z (c/mk c/K c/O c/T c/C c/_z))
(def kotc_rt (c/mk c/K c/O c/T c/C c/_rt))

(def ke_a (c/mk c/K c/E c/_a))
(def ke_b (c/mk c/K c/E c/_b))
(def ke_c (c/mk c/K c/E c/_c))
(def ke_d (c/mk c/K c/E c/_d))
(def ke_e (c/mk c/K c/E c/_e))
(def ke_f (c/mk c/K c/E c/_f))
(def ke_g (c/mk c/K c/E c/_g))
(def ke_h (c/mk c/K c/E c/_h))
(def ke_i (c/mk c/K c/E c/_i))
(def ke_j (c/mk c/K c/E c/_j))
(def ke_k (c/mk c/K c/E c/_k))
(def ke_l (c/mk c/K c/E c/_l))
(def ke_m (c/mk c/K c/E c/_m))
(def ke_n (c/mk c/K c/E c/_n))
(def ke_o (c/mk c/K c/E c/_o))
(def ke_p (c/mk c/K c/E c/_p))
(def ke_q (c/mk c/K c/E c/_q))
(def ke_r (c/mk c/K c/E c/_r))
(def ke_s (c/mk c/K c/E c/_s))
(def ke_t (c/mk c/K c/E c/_t))
(def ke_u (c/mk c/K c/E c/_u))
(def ke_v (c/mk c/K c/E c/_v))
(def ke_w (c/mk c/K c/E c/_w))
(def ke_x (c/mk c/K c/E c/_x))
(def ke_y (c/mk c/K c/E c/_y))
(def ke_z (c/mk c/K c/E c/_z))
(def ke_rt (c/mk c/K c/E c/_rt))

(def kw_a (c/mk c/K c/W c/_a))
(def kw_b (c/mk c/K c/W c/_b))
(def kw_c (c/mk c/K c/W c/_c))
(def kw_d (c/mk c/K c/W c/_d))
(def kw_e (c/mk c/K c/W c/_e))
(def kw_f (c/mk c/K c/W c/_f))
(def kw_g (c/mk c/K c/W c/_g))
(def kw_h (c/mk c/K c/W c/_h))
(def kw_i (c/mk c/K c/W c/_i))
(def kw_j (c/mk c/K c/W c/_j))
(def kw_k (c/mk c/K c/W c/_k))
(def kw_l (c/mk c/K c/W c/_l))
(def kw_m (c/mk c/K c/W c/_m))
(def kw_n (c/mk c/K c/W c/_n))
(def kw_o (c/mk c/K c/W c/_o))
(def kw_p (c/mk c/K c/W c/_p))
(def kw_q (c/mk c/K c/W c/_q))
(def kw_r (c/mk c/K c/W c/_r))
(def kw_s (c/mk c/K c/W c/_s))
(def kw_t (c/mk c/K c/W c/_t))
(def kw_u (c/mk c/K c/W c/_u))
(def kw_v (c/mk c/K c/W c/_v))
(def kw_w (c/mk c/K c/W c/_w))
(def kw_x (c/mk c/K c/W c/_x))
(def kw_y (c/mk c/K c/W c/_y))
(def kw_z (c/mk c/K c/W c/_z))
(def kw_rt (c/mk c/K c/W c/_rt))

(def kq_a (c/mk c/K c/Q c/_a))
(def kq_b (c/mk c/K c/Q c/_b))
(def kq_c (c/mk c/K c/Q c/_c))
(def kq_d (c/mk c/K c/Q c/_d))
(def kq_e (c/mk c/K c/Q c/_e))
(def kq_f (c/mk c/K c/Q c/_f))
(def kq_g (c/mk c/K c/Q c/_g))
(def kq_h (c/mk c/K c/Q c/_h))
(def kq_i (c/mk c/K c/Q c/_i))
(def kq_j (c/mk c/K c/Q c/_j))
(def kq_k (c/mk c/K c/Q c/_k))
(def kq_l (c/mk c/K c/Q c/_l))
(def kq_m (c/mk c/K c/Q c/_m))
(def kq_n (c/mk c/K c/Q c/_n))
(def kq_o (c/mk c/K c/Q c/_o))
(def kq_p (c/mk c/K c/Q c/_p))
(def kq_q (c/mk c/K c/Q c/_q))
(def kq_r (c/mk c/K c/Q c/_r))
(def kq_s (c/mk c/K c/Q c/_s))
(def kq_t (c/mk c/K c/Q c/_t))
(def kq_u (c/mk c/K c/Q c/_u))
(def kq_v (c/mk c/K c/Q c/_v))
(def kq_w (c/mk c/K c/Q c/_w))
(def kq_x (c/mk c/K c/Q c/_x))
(def kq_y (c/mk c/K c/Q c/_y))
(def kq_z (c/mk c/K c/Q c/_z))
(def kq_rt (c/mk c/K c/Q c/_rt))

(def kewq_a (c/mk c/K c/E c/W c/Q c/_a))
(def kewq_b (c/mk c/K c/E c/W c/Q c/_b))
(def kewq_c (c/mk c/K c/E c/W c/Q c/_c))
(def kewq_d (c/mk c/K c/E c/W c/Q c/_d))
(def kewq_e (c/mk c/K c/E c/W c/Q c/_e))
(def kewq_f (c/mk c/K c/E c/W c/Q c/_f))
(def kewq_g (c/mk c/K c/E c/W c/Q c/_g))
(def kewq_h (c/mk c/K c/E c/W c/Q c/_h))
(def kewq_i (c/mk c/K c/E c/W c/Q c/_i))
(def kewq_j (c/mk c/K c/E c/W c/Q c/_j))
(def kewq_k (c/mk c/K c/E c/W c/Q c/_k))
(def kewq_l (c/mk c/K c/E c/W c/Q c/_l))
(def kewq_m (c/mk c/K c/E c/W c/Q c/_m))
(def kewq_n (c/mk c/K c/E c/W c/Q c/_n))
(def kewq_o (c/mk c/K c/E c/W c/Q c/_o))
(def kewq_p (c/mk c/K c/E c/W c/Q c/_p))
(def kewq_q (c/mk c/K c/E c/W c/Q c/_q))
(def kewq_r (c/mk c/K c/E c/W c/Q c/_r))
(def kewq_s (c/mk c/K c/E c/W c/Q c/_s))
(def kewq_t (c/mk c/K c/E c/W c/Q c/_t))
(def kewq_u (c/mk c/K c/E c/W c/Q c/_u))
(def kewq_v (c/mk c/K c/E c/W c/Q c/_v))
(def kewq_w (c/mk c/K c/E c/W c/Q c/_w))
(def kewq_x (c/mk c/K c/E c/W c/Q c/_x))
(def kewq_y (c/mk c/K c/E c/W c/Q c/_y))
(def kewq_z (c/mk c/K c/E c/W c/Q c/_z))
(def kewq_rt (c/mk c/K c/E c/W c/Q c/_rt))

(def ks_a (c/mk c/K c/S c/_a))
(def ks_b (c/mk c/K c/S c/_b))
(def ks_c (c/mk c/K c/S c/_c))
(def ks_d (c/mk c/K c/S c/_d))
(def ks_e (c/mk c/K c/S c/_e))
(def ks_f (c/mk c/K c/S c/_f))
(def ks_g (c/mk c/K c/S c/_g))
(def ks_h (c/mk c/K c/S c/_h))
(def ks_i (c/mk c/K c/S c/_i))
(def ks_j (c/mk c/K c/S c/_j))
(def ks_k (c/mk c/K c/S c/_k))
(def ks_l (c/mk c/K c/S c/_l))
(def ks_m (c/mk c/K c/S c/_m))
(def ks_n (c/mk c/K c/S c/_n))
(def ks_o (c/mk c/K c/S c/_o))
(def ks_p (c/mk c/K c/S c/_p))
(def ks_q (c/mk c/K c/S c/_q))
(def ks_r (c/mk c/K c/S c/_r))
(def ks_s (c/mk c/K c/S c/_s))
(def ks_t (c/mk c/K c/S c/_t))
(def ks_u (c/mk c/K c/S c/_u))
(def ks_v (c/mk c/K c/S c/_v))
(def ks_w (c/mk c/K c/S c/_w))
(def ks_x (c/mk c/K c/S c/_x))
(def ks_y (c/mk c/K c/S c/_y))
(def ks_z (c/mk c/K c/S c/_z))
(def ks_rt (c/mk c/K c/S c/_rt))

(def kos_a (c/mk c/K c/O c/S c/_a))
(def kos_b (c/mk c/K c/O c/S c/_b))
(def kos_c (c/mk c/K c/O c/S c/_c))
(def kos_d (c/mk c/K c/O c/S c/_d))
(def kos_e (c/mk c/K c/O c/S c/_e))
(def kos_f (c/mk c/K c/O c/S c/_f))
(def kos_g (c/mk c/K c/O c/S c/_g))
(def kos_h (c/mk c/K c/O c/S c/_h))
(def kos_i (c/mk c/K c/O c/S c/_i))
(def kos_j (c/mk c/K c/O c/S c/_j))
(def kos_k (c/mk c/K c/O c/S c/_k))
(def kos_l (c/mk c/K c/O c/S c/_l))
(def kos_m (c/mk c/K c/O c/S c/_m))
(def kos_n (c/mk c/K c/O c/S c/_n))
(def kos_o (c/mk c/K c/O c/S c/_o))
(def kos_p (c/mk c/K c/O c/S c/_p))
(def kos_q (c/mk c/K c/O c/S c/_q))
(def kos_r (c/mk c/K c/O c/S c/_r))
(def kos_s (c/mk c/K c/O c/S c/_s))
(def kos_t (c/mk c/K c/O c/S c/_t))
(def kos_u (c/mk c/K c/O c/S c/_u))
(def kos_v (c/mk c/K c/O c/S c/_v))
(def kos_w (c/mk c/K c/O c/S c/_w))
(def kos_x (c/mk c/K c/O c/S c/_x))
(def kos_y (c/mk c/K c/O c/S c/_y))
(def kos_z (c/mk c/K c/O c/S c/_z))
(def kos_rt (c/mk c/K c/O c/S c/_rt))

(def kts_a (c/mk c/K c/T c/S c/_a))
(def kts_b (c/mk c/K c/T c/S c/_b))
(def kts_c (c/mk c/K c/T c/S c/_c))
(def kts_d (c/mk c/K c/T c/S c/_d))
(def kts_e (c/mk c/K c/T c/S c/_e))
(def kts_f (c/mk c/K c/T c/S c/_f))
(def kts_g (c/mk c/K c/T c/S c/_g))
(def kts_h (c/mk c/K c/T c/S c/_h))
(def kts_i (c/mk c/K c/T c/S c/_i))
(def kts_j (c/mk c/K c/T c/S c/_j))
(def kts_k (c/mk c/K c/T c/S c/_k))
(def kts_l (c/mk c/K c/T c/S c/_l))
(def kts_m (c/mk c/K c/T c/S c/_m))
(def kts_n (c/mk c/K c/T c/S c/_n))
(def kts_o (c/mk c/K c/T c/S c/_o))
(def kts_p (c/mk c/K c/T c/S c/_p))
(def kts_q (c/mk c/K c/T c/S c/_q))
(def kts_r (c/mk c/K c/T c/S c/_r))
(def kts_s (c/mk c/K c/T c/S c/_s))
(def kts_t (c/mk c/K c/T c/S c/_t))
(def kts_u (c/mk c/K c/T c/S c/_u))
(def kts_v (c/mk c/K c/T c/S c/_v))
(def kts_w (c/mk c/K c/T c/S c/_w))
(def kts_x (c/mk c/K c/T c/S c/_x))
(def kts_y (c/mk c/K c/T c/S c/_y))
(def kts_z (c/mk c/K c/T c/S c/_z))
(def kts_rt (c/mk c/K c/T c/S c/_rt))

(def kcs_a (c/mk c/K c/C c/S c/_a))
(def kcs_b (c/mk c/K c/C c/S c/_b))
(def kcs_c (c/mk c/K c/C c/S c/_c))
(def kcs_d (c/mk c/K c/C c/S c/_d))
(def kcs_e (c/mk c/K c/C c/S c/_e))
(def kcs_f (c/mk c/K c/C c/S c/_f))
(def kcs_g (c/mk c/K c/C c/S c/_g))
(def kcs_h (c/mk c/K c/C c/S c/_h))
(def kcs_i (c/mk c/K c/C c/S c/_i))
(def kcs_j (c/mk c/K c/C c/S c/_j))
(def kcs_k (c/mk c/K c/C c/S c/_k))
(def kcs_l (c/mk c/K c/C c/S c/_l))
(def kcs_m (c/mk c/K c/C c/S c/_m))
(def kcs_n (c/mk c/K c/C c/S c/_n))
(def kcs_o (c/mk c/K c/C c/S c/_o))
(def kcs_p (c/mk c/K c/C c/S c/_p))
(def kcs_q (c/mk c/K c/C c/S c/_q))
(def kcs_r (c/mk c/K c/C c/S c/_r))
(def kcs_s (c/mk c/K c/C c/S c/_s))
(def kcs_t (c/mk c/K c/C c/S c/_t))
(def kcs_u (c/mk c/K c/C c/S c/_u))
(def kcs_v (c/mk c/K c/C c/S c/_v))
(def kcs_w (c/mk c/K c/C c/S c/_w))
(def kcs_x (c/mk c/K c/C c/S c/_x))
(def kcs_y (c/mk c/K c/C c/S c/_y))
(def kcs_z (c/mk c/K c/C c/S c/_z))
(def kcs_rt (c/mk c/K c/C c/S c/_rt))

(def kots_a (c/mk c/K c/O c/T c/S c/_a))
(def kots_b (c/mk c/K c/O c/T c/S c/_b))
(def kots_c (c/mk c/K c/O c/T c/S c/_c))
(def kots_d (c/mk c/K c/O c/T c/S c/_d))
(def kots_e (c/mk c/K c/O c/T c/S c/_e))
(def kots_f (c/mk c/K c/O c/T c/S c/_f))
(def kots_g (c/mk c/K c/O c/T c/S c/_g))
(def kots_h (c/mk c/K c/O c/T c/S c/_h))
(def kots_i (c/mk c/K c/O c/T c/S c/_i))
(def kots_j (c/mk c/K c/O c/T c/S c/_j))
(def kots_k (c/mk c/K c/O c/T c/S c/_k))
(def kots_l (c/mk c/K c/O c/T c/S c/_l))
(def kots_m (c/mk c/K c/O c/T c/S c/_m))
(def kots_n (c/mk c/K c/O c/T c/S c/_n))
(def kots_o (c/mk c/K c/O c/T c/S c/_o))
(def kots_p (c/mk c/K c/O c/T c/S c/_p))
(def kots_q (c/mk c/K c/O c/T c/S c/_q))
(def kots_r (c/mk c/K c/O c/T c/S c/_r))
(def kots_s (c/mk c/K c/O c/T c/S c/_s))
(def kots_t (c/mk c/K c/O c/T c/S c/_t))
(def kots_u (c/mk c/K c/O c/T c/S c/_u))
(def kots_v (c/mk c/K c/O c/T c/S c/_v))
(def kots_w (c/mk c/K c/O c/T c/S c/_w))
(def kots_x (c/mk c/K c/O c/T c/S c/_x))
(def kots_y (c/mk c/K c/O c/T c/S c/_y))
(def kots_z (c/mk c/K c/O c/T c/S c/_z))
(def kots_rt (c/mk c/K c/O c/T c/S c/_rt))

(def kocs_a (c/mk c/K c/O c/C c/S c/_a))
(def kocs_b (c/mk c/K c/O c/C c/S c/_b))
(def kocs_c (c/mk c/K c/O c/C c/S c/_c))
(def kocs_d (c/mk c/K c/O c/C c/S c/_d))
(def kocs_e (c/mk c/K c/O c/C c/S c/_e))
(def kocs_f (c/mk c/K c/O c/C c/S c/_f))
(def kocs_g (c/mk c/K c/O c/C c/S c/_g))
(def kocs_h (c/mk c/K c/O c/C c/S c/_h))
(def kocs_i (c/mk c/K c/O c/C c/S c/_i))
(def kocs_j (c/mk c/K c/O c/C c/S c/_j))
(def kocs_k (c/mk c/K c/O c/C c/S c/_k))
(def kocs_l (c/mk c/K c/O c/C c/S c/_l))
(def kocs_m (c/mk c/K c/O c/C c/S c/_m))
(def kocs_n (c/mk c/K c/O c/C c/S c/_n))
(def kocs_o (c/mk c/K c/O c/C c/S c/_o))
(def kocs_p (c/mk c/K c/O c/C c/S c/_p))
(def kocs_q (c/mk c/K c/O c/C c/S c/_q))
(def kocs_r (c/mk c/K c/O c/C c/S c/_r))
(def kocs_s (c/mk c/K c/O c/C c/S c/_s))
(def kocs_t (c/mk c/K c/O c/C c/S c/_t))
(def kocs_u (c/mk c/K c/O c/C c/S c/_u))
(def kocs_v (c/mk c/K c/O c/C c/S c/_v))
(def kocs_w (c/mk c/K c/O c/C c/S c/_w))
(def kocs_x (c/mk c/K c/O c/C c/S c/_x))
(def kocs_y (c/mk c/K c/O c/C c/S c/_y))
(def kocs_z (c/mk c/K c/O c/C c/S c/_z))
(def kocs_rt (c/mk c/K c/O c/C c/S c/_rt))

(def ktcs_a (c/mk c/K c/T c/C c/S c/_a))
(def ktcs_b (c/mk c/K c/T c/C c/S c/_b))
(def ktcs_c (c/mk c/K c/T c/C c/S c/_c))
(def ktcs_d (c/mk c/K c/T c/C c/S c/_d))
(def ktcs_e (c/mk c/K c/T c/C c/S c/_e))
(def ktcs_f (c/mk c/K c/T c/C c/S c/_f))
(def ktcs_g (c/mk c/K c/T c/C c/S c/_g))
(def ktcs_h (c/mk c/K c/T c/C c/S c/_h))
(def ktcs_i (c/mk c/K c/T c/C c/S c/_i))
(def ktcs_j (c/mk c/K c/T c/C c/S c/_j))
(def ktcs_k (c/mk c/K c/T c/C c/S c/_k))
(def ktcs_l (c/mk c/K c/T c/C c/S c/_l))
(def ktcs_m (c/mk c/K c/T c/C c/S c/_m))
(def ktcs_n (c/mk c/K c/T c/C c/S c/_n))
(def ktcs_o (c/mk c/K c/T c/C c/S c/_o))
(def ktcs_p (c/mk c/K c/T c/C c/S c/_p))
(def ktcs_q (c/mk c/K c/T c/C c/S c/_q))
(def ktcs_r (c/mk c/K c/T c/C c/S c/_r))
(def ktcs_s (c/mk c/K c/T c/C c/S c/_s))
(def ktcs_t (c/mk c/K c/T c/C c/S c/_t))
(def ktcs_u (c/mk c/K c/T c/C c/S c/_u))
(def ktcs_v (c/mk c/K c/T c/C c/S c/_v))
(def ktcs_w (c/mk c/K c/T c/C c/S c/_w))
(def ktcs_x (c/mk c/K c/T c/C c/S c/_x))
(def ktcs_y (c/mk c/K c/T c/C c/S c/_y))
(def ktcs_z (c/mk c/K c/T c/C c/S c/_z))
(def ktcs_rt (c/mk c/K c/T c/C c/S c/_rt))

(def kotcs_a (c/mk c/K c/O c/T c/C c/R c/_a))
(def kotcs_b (c/mk c/K c/O c/T c/C c/R c/_b))
(def kotcs_c (c/mk c/K c/O c/T c/C c/R c/_c))
(def kotcs_d (c/mk c/K c/O c/T c/C c/R c/_d))
(def kotcs_e (c/mk c/K c/O c/T c/C c/R c/_e))
(def kotcs_f (c/mk c/K c/O c/T c/C c/R c/_f))
(def kotcs_g (c/mk c/K c/O c/T c/C c/R c/_g))
(def kotcs_h (c/mk c/K c/O c/T c/C c/R c/_h))
(def kotcs_i (c/mk c/K c/O c/T c/C c/R c/_i))
(def kotcs_j (c/mk c/K c/O c/T c/C c/R c/_j))
(def kotcs_k (c/mk c/K c/O c/T c/C c/R c/_k))
(def kotcs_l (c/mk c/K c/O c/T c/C c/R c/_l))
(def kotcs_m (c/mk c/K c/O c/T c/C c/R c/_m))
(def kotcs_n (c/mk c/K c/O c/T c/C c/R c/_n))
(def kotcs_o (c/mk c/K c/O c/T c/C c/R c/_o))
(def kotcs_p (c/mk c/K c/O c/T c/C c/R c/_p))
(def kotcs_q (c/mk c/K c/O c/T c/C c/R c/_q))
(def kotcs_r (c/mk c/K c/O c/T c/C c/R c/_r))
(def kotcs_s (c/mk c/K c/O c/T c/C c/R c/_s))
(def kotcs_t (c/mk c/K c/O c/T c/C c/R c/_t))
(def kotcs_u (c/mk c/K c/O c/T c/C c/R c/_u))
(def kotcs_v (c/mk c/K c/O c/T c/C c/R c/_v))
(def kotcs_w (c/mk c/K c/O c/T c/C c/R c/_w))
(def kotcs_x (c/mk c/K c/O c/T c/C c/R c/_x))
(def kotcs_y (c/mk c/K c/O c/T c/C c/R c/_y))
(def kotcs_z (c/mk c/K c/O c/T c/C c/R c/_z))
(def kotcs_rt (c/mk c/K c/O c/T c/C c/R c/_rt))

(def ker_a (c/mk c/K c/E c/R c/_a))
(def ker_b (c/mk c/K c/E c/R c/_b))
(def ker_c (c/mk c/K c/E c/R c/_c))
(def ker_d (c/mk c/K c/E c/R c/_d))
(def ker_e (c/mk c/K c/E c/R c/_e))
(def ker_f (c/mk c/K c/E c/R c/_f))
(def ker_g (c/mk c/K c/E c/R c/_g))
(def ker_h (c/mk c/K c/E c/R c/_h))
(def ker_i (c/mk c/K c/E c/R c/_i))
(def ker_j (c/mk c/K c/E c/R c/_j))
(def ker_k (c/mk c/K c/E c/R c/_k))
(def ker_l (c/mk c/K c/E c/R c/_l))
(def ker_m (c/mk c/K c/E c/R c/_m))
(def ker_n (c/mk c/K c/E c/R c/_n))
(def ker_o (c/mk c/K c/E c/R c/_o))
(def ker_p (c/mk c/K c/E c/R c/_p))
(def ker_q (c/mk c/K c/E c/R c/_q))
(def ker_r (c/mk c/K c/E c/R c/_r))
(def ker_s (c/mk c/K c/E c/R c/_s))
(def ker_t (c/mk c/K c/E c/R c/_t))
(def ker_u (c/mk c/K c/E c/R c/_u))
(def ker_v (c/mk c/K c/E c/R c/_v))
(def ker_w (c/mk c/K c/E c/R c/_w))
(def ker_x (c/mk c/K c/E c/R c/_x))
(def ker_y (c/mk c/K c/E c/R c/_y))
(def ker_z (c/mk c/K c/E c/R c/_z))
(def ker_rt (c/mk c/K c/E c/R c/_rt))

(def kws_a (c/mk c/K c/W c/S c/_a))
(def kws_b (c/mk c/K c/W c/S c/_b))
(def kws_c (c/mk c/K c/W c/S c/_c))
(def kws_d (c/mk c/K c/W c/S c/_d))
(def kws_e (c/mk c/K c/W c/S c/_e))
(def kws_f (c/mk c/K c/W c/S c/_f))
(def kws_g (c/mk c/K c/W c/S c/_g))
(def kws_h (c/mk c/K c/W c/S c/_h))
(def kws_i (c/mk c/K c/W c/S c/_i))
(def kws_j (c/mk c/K c/W c/S c/_j))
(def kws_k (c/mk c/K c/W c/S c/_k))
(def kws_l (c/mk c/K c/W c/S c/_l))
(def kws_m (c/mk c/K c/W c/S c/_m))
(def kws_n (c/mk c/K c/W c/S c/_n))
(def kws_o (c/mk c/K c/W c/S c/_o))
(def kws_p (c/mk c/K c/W c/S c/_p))
(def kws_q (c/mk c/K c/W c/S c/_q))
(def kws_r (c/mk c/K c/W c/S c/_r))
(def kws_s (c/mk c/K c/W c/S c/_s))
(def kws_t (c/mk c/K c/W c/S c/_t))
(def kws_u (c/mk c/K c/W c/S c/_u))
(def kws_v (c/mk c/K c/W c/S c/_v))
(def kws_w (c/mk c/K c/W c/S c/_w))
(def kws_x (c/mk c/K c/W c/S c/_x))
(def kws_y (c/mk c/K c/W c/S c/_y))
(def kws_z (c/mk c/K c/W c/S c/_z))
(def kws_rt (c/mk c/K c/W c/S c/_rt))

(def kqr_a (c/mk c/K c/Q c/R c/_a))
(def kqr_b (c/mk c/K c/Q c/R c/_b))
(def kqr_c (c/mk c/K c/Q c/R c/_c))
(def kqr_d (c/mk c/K c/Q c/R c/_d))
(def kqr_e (c/mk c/K c/Q c/R c/_e))
(def kqr_f (c/mk c/K c/Q c/R c/_f))
(def kqr_g (c/mk c/K c/Q c/R c/_g))
(def kqr_h (c/mk c/K c/Q c/R c/_h))
(def kqr_i (c/mk c/K c/Q c/R c/_i))
(def kqr_j (c/mk c/K c/Q c/R c/_j))
(def kqr_k (c/mk c/K c/Q c/R c/_k))
(def kqr_l (c/mk c/K c/Q c/R c/_l))
(def kqr_m (c/mk c/K c/Q c/R c/_m))
(def kqr_n (c/mk c/K c/Q c/R c/_n))
(def kqr_o (c/mk c/K c/Q c/R c/_o))
(def kqr_p (c/mk c/K c/Q c/R c/_p))
(def kqr_q (c/mk c/K c/Q c/R c/_q))
(def kqr_r (c/mk c/K c/Q c/R c/_r))
(def kqr_s (c/mk c/K c/Q c/R c/_s))
(def kqr_t (c/mk c/K c/Q c/R c/_t))
(def kqr_u (c/mk c/K c/Q c/R c/_u))
(def kqr_v (c/mk c/K c/Q c/R c/_v))
(def kqr_w (c/mk c/K c/Q c/R c/_w))
(def kqr_x (c/mk c/K c/Q c/R c/_x))
(def kqr_y (c/mk c/K c/Q c/R c/_y))
(def kqr_z (c/mk c/K c/Q c/R c/_z))
(def kqr_rt (c/mk c/K c/Q c/R c/_rt))

(def kewqs_a (c/mk c/K c/E c/W c/Q c/S c/_a))
(def kewqs_b (c/mk c/K c/E c/W c/Q c/S c/_b))
(def kewqs_c (c/mk c/K c/E c/W c/Q c/S c/_c))
(def kewqs_d (c/mk c/K c/E c/W c/Q c/S c/_d))
(def kewqs_e (c/mk c/K c/E c/W c/Q c/S c/_e))
(def kewqs_f (c/mk c/K c/E c/W c/Q c/S c/_f))
(def kewqs_g (c/mk c/K c/E c/W c/Q c/S c/_g))
(def kewqs_h (c/mk c/K c/E c/W c/Q c/S c/_h))
(def kewqs_i (c/mk c/K c/E c/W c/Q c/S c/_i))
(def kewqs_j (c/mk c/K c/E c/W c/Q c/S c/_j))
(def kewqs_k (c/mk c/K c/E c/W c/Q c/S c/_k))
(def kewqs_l (c/mk c/K c/E c/W c/Q c/S c/_l))
(def kewqs_m (c/mk c/K c/E c/W c/Q c/S c/_m))
(def kewqs_n (c/mk c/K c/E c/W c/Q c/S c/_n))
(def kewqs_o (c/mk c/K c/E c/W c/Q c/S c/_o))
(def kewqs_p (c/mk c/K c/E c/W c/Q c/S c/_p))
(def kewqs_q (c/mk c/K c/E c/W c/Q c/S c/_q))
(def kewqs_r (c/mk c/K c/E c/W c/Q c/S c/_r))
(def kewqs_s (c/mk c/K c/E c/W c/Q c/S c/_s))
(def kewqs_t (c/mk c/K c/E c/W c/Q c/S c/_t))
(def kewqs_u (c/mk c/K c/E c/W c/Q c/S c/_u))
(def kewqs_v (c/mk c/K c/E c/W c/Q c/S c/_v))
(def kewqs_w (c/mk c/K c/E c/W c/Q c/S c/_w))
(def kewqs_x (c/mk c/K c/E c/W c/Q c/S c/_x))
(def kewqs_y (c/mk c/K c/E c/W c/Q c/S c/_y))
(def kewqs_z (c/mk c/K c/E c/W c/Q c/S c/_z))
(def kewqs_rt (c/mk c/K c/E c/W c/Q c/S c/_rt))

(def kp_a (c/mk c/P c/_a))
(def kp_b (c/mk c/P c/_b))
(def kp_c (c/mk c/P c/_c))
(def kp_d (c/mk c/P c/_d))
(def kp_e (c/mk c/P c/_e))
(def kp_f (c/mk c/P c/_f))
(def kp_g (c/mk c/P c/_g))
(def kp_h (c/mk c/P c/_h))
(def kp_i (c/mk c/P c/_i))
(def kp_j (c/mk c/P c/_j))
(def kp_k (c/mk c/P c/_k))
(def kp_l (c/mk c/P c/_l))
(def kp_m (c/mk c/P c/_m))
(def kp_n (c/mk c/P c/_n))
(def kp_o (c/mk c/P c/_o))
(def kp_p (c/mk c/P c/_p))
(def kp_q (c/mk c/P c/_q))
(def kp_r (c/mk c/P c/_r))
(def kp_s (c/mk c/P c/_s))
(def kp_t (c/mk c/P c/_t))
(def kp_u (c/mk c/P c/_u))
(def kp_v (c/mk c/P c/_v))
(def kp_w (c/mk c/P c/_w))
(def kp_x (c/mk c/P c/_x))
(def kp_y (c/mk c/P c/_y))
(def kp_z (c/mk c/P c/_z))
(def kp_rt (c/mk c/P c/_rt))

(def kop_a (c/mk c/K c/O c/P c/_a))
(def kop_b (c/mk c/K c/O c/P c/_b))
(def kop_c (c/mk c/K c/O c/P c/_c))
(def kop_d (c/mk c/K c/O c/P c/_d))
(def kop_e (c/mk c/K c/O c/P c/_e))
(def kop_f (c/mk c/K c/O c/P c/_f))
(def kop_g (c/mk c/K c/O c/P c/_g))
(def kop_h (c/mk c/K c/O c/P c/_h))
(def kop_i (c/mk c/K c/O c/P c/_i))
(def kop_j (c/mk c/K c/O c/P c/_j))
(def kop_k (c/mk c/K c/O c/P c/_k))
(def kop_l (c/mk c/K c/O c/P c/_l))
(def kop_m (c/mk c/K c/O c/P c/_m))
(def kop_n (c/mk c/K c/O c/P c/_n))
(def kop_o (c/mk c/K c/O c/P c/_o))
(def kop_p (c/mk c/K c/O c/P c/_p))
(def kop_q (c/mk c/K c/O c/P c/_q))
(def kop_r (c/mk c/K c/O c/P c/_r))
(def kop_s (c/mk c/K c/O c/P c/_s))
(def kop_t (c/mk c/K c/O c/P c/_t))
(def kop_u (c/mk c/K c/O c/P c/_u))
(def kop_v (c/mk c/K c/O c/P c/_v))
(def kop_w (c/mk c/K c/O c/P c/_w))
(def kop_x (c/mk c/K c/O c/P c/_x))
(def kop_y (c/mk c/K c/O c/P c/_y))
(def kop_z (c/mk c/K c/O c/P c/_z))
(def kop_rt (c/mk c/K c/O c/P c/_rt))

(def ktp_a (c/mk c/K c/T c/P c/_a))
(def ktp_b (c/mk c/K c/T c/P c/_b))
(def ktp_c (c/mk c/K c/T c/P c/_c))
(def ktp_d (c/mk c/K c/T c/P c/_d))
(def ktp_e (c/mk c/K c/T c/P c/_e))
(def ktp_f (c/mk c/K c/T c/P c/_f))
(def ktp_g (c/mk c/K c/T c/P c/_g))
(def ktp_h (c/mk c/K c/T c/P c/_h))
(def ktp_i (c/mk c/K c/T c/P c/_i))
(def ktp_j (c/mk c/K c/T c/P c/_j))
(def ktp_k (c/mk c/K c/T c/P c/_k))
(def ktp_l (c/mk c/K c/T c/P c/_l))
(def ktp_m (c/mk c/K c/T c/P c/_m))
(def ktp_n (c/mk c/K c/T c/P c/_n))
(def ktp_o (c/mk c/K c/T c/P c/_o))
(def ktp_p (c/mk c/K c/T c/P c/_p))
(def ktp_q (c/mk c/K c/T c/P c/_q))
(def ktp_r (c/mk c/K c/T c/P c/_r))
(def ktp_s (c/mk c/K c/T c/P c/_s))
(def ktp_t (c/mk c/K c/T c/P c/_t))
(def ktp_u (c/mk c/K c/T c/P c/_u))
(def ktp_v (c/mk c/K c/T c/P c/_v))
(def ktp_w (c/mk c/K c/T c/P c/_w))
(def ktp_x (c/mk c/K c/T c/P c/_x))
(def ktp_y (c/mk c/K c/T c/P c/_y))
(def ktp_z (c/mk c/K c/T c/P c/_z))
(def ktp_rt (c/mk c/K c/T c/P c/_rt))

(def kcp_a (c/mk c/K c/C c/P c/_a))
(def kcp_b (c/mk c/K c/C c/P c/_b))
(def kcp_c (c/mk c/K c/C c/P c/_c))
(def kcp_d (c/mk c/K c/C c/P c/_d))
(def kcp_e (c/mk c/K c/C c/P c/_e))
(def kcp_f (c/mk c/K c/C c/P c/_f))
(def kcp_g (c/mk c/K c/C c/P c/_g))
(def kcp_h (c/mk c/K c/C c/P c/_h))
(def kcp_i (c/mk c/K c/C c/P c/_i))
(def kcp_j (c/mk c/K c/C c/P c/_j))
(def kcp_k (c/mk c/K c/C c/P c/_k))
(def kcp_l (c/mk c/K c/C c/P c/_l))
(def kcp_m (c/mk c/K c/C c/P c/_m))
(def kcp_n (c/mk c/K c/C c/P c/_n))
(def kcp_o (c/mk c/K c/C c/P c/_o))
(def kcp_p (c/mk c/K c/C c/P c/_p))
(def kcp_q (c/mk c/K c/C c/P c/_q))
(def kcp_r (c/mk c/K c/C c/P c/_r))
(def kcp_s (c/mk c/K c/C c/P c/_s))
(def kcp_t (c/mk c/K c/C c/P c/_t))
(def kcp_u (c/mk c/K c/C c/P c/_u))
(def kcp_v (c/mk c/K c/C c/P c/_v))
(def kcp_w (c/mk c/K c/C c/P c/_w))
(def kcp_x (c/mk c/K c/C c/P c/_x))
(def kcp_y (c/mk c/K c/C c/P c/_y))
(def kcp_z (c/mk c/K c/C c/P c/_z))
(def kcp_rt (c/mk c/K c/C c/P c/_rt))

(def kotp_a (c/mk c/K c/O c/T c/P c/_a))
(def kotp_b (c/mk c/K c/O c/T c/P c/_b))
(def kotp_c (c/mk c/K c/O c/T c/P c/_c))
(def kotp_d (c/mk c/K c/O c/T c/P c/_d))
(def kotp_e (c/mk c/K c/O c/T c/P c/_e))
(def kotp_f (c/mk c/K c/O c/T c/P c/_f))
(def kotp_g (c/mk c/K c/O c/T c/P c/_g))
(def kotp_h (c/mk c/K c/O c/T c/P c/_h))
(def kotp_i (c/mk c/K c/O c/T c/P c/_i))
(def kotp_j (c/mk c/K c/O c/T c/P c/_j))
(def kotp_k (c/mk c/K c/O c/T c/P c/_k))
(def kotp_l (c/mk c/K c/O c/T c/P c/_l))
(def kotp_m (c/mk c/K c/O c/T c/P c/_m))
(def kotp_n (c/mk c/K c/O c/T c/P c/_n))
(def kotp_o (c/mk c/K c/O c/T c/P c/_o))
(def kotp_p (c/mk c/K c/O c/T c/P c/_p))
(def kotp_q (c/mk c/K c/O c/T c/P c/_q))
(def kotp_r (c/mk c/K c/O c/T c/P c/_r))
(def kotp_s (c/mk c/K c/O c/T c/P c/_s))
(def kotp_t (c/mk c/K c/O c/T c/P c/_t))
(def kotp_u (c/mk c/K c/O c/T c/P c/_u))
(def kotp_v (c/mk c/K c/O c/T c/P c/_v))
(def kotp_w (c/mk c/K c/O c/T c/P c/_w))
(def kotp_x (c/mk c/K c/O c/T c/P c/_x))
(def kotp_y (c/mk c/K c/O c/T c/P c/_y))
(def kotp_z (c/mk c/K c/O c/T c/P c/_z))
(def kotp_rt (c/mk c/K c/O c/T c/P c/_rt))

(def kocp_a (c/mk c/K c/O c/C c/P c/_a))
(def kocp_b (c/mk c/K c/O c/C c/P c/_b))
(def kocp_c (c/mk c/K c/O c/C c/P c/_c))
(def kocp_d (c/mk c/K c/O c/C c/P c/_d))
(def kocp_e (c/mk c/K c/O c/C c/P c/_e))
(def kocp_f (c/mk c/K c/O c/C c/P c/_f))
(def kocp_g (c/mk c/K c/O c/C c/P c/_g))
(def kocp_h (c/mk c/K c/O c/C c/P c/_h))
(def kocp_i (c/mk c/K c/O c/C c/P c/_i))
(def kocp_j (c/mk c/K c/O c/C c/P c/_j))
(def kocp_k (c/mk c/K c/O c/C c/P c/_k))
(def kocp_l (c/mk c/K c/O c/C c/P c/_l))
(def kocp_m (c/mk c/K c/O c/C c/P c/_m))
(def kocp_n (c/mk c/K c/O c/C c/P c/_n))
(def kocp_o (c/mk c/K c/O c/C c/P c/_o))
(def kocp_p (c/mk c/K c/O c/C c/P c/_p))
(def kocp_q (c/mk c/K c/O c/C c/P c/_q))
(def kocp_r (c/mk c/K c/O c/C c/P c/_r))
(def kocp_s (c/mk c/K c/O c/C c/P c/_s))
(def kocp_t (c/mk c/K c/O c/C c/P c/_t))
(def kocp_u (c/mk c/K c/O c/C c/P c/_u))
(def kocp_v (c/mk c/K c/O c/C c/P c/_v))
(def kocp_w (c/mk c/K c/O c/C c/P c/_w))
(def kocp_x (c/mk c/K c/O c/C c/P c/_x))
(def kocp_y (c/mk c/K c/O c/C c/P c/_y))
(def kocp_z (c/mk c/K c/O c/C c/P c/_z))
(def kocp_rt (c/mk c/K c/O c/C c/P c/_rt))

(def ktcp_a (c/mk c/K c/T c/C c/P c/_a))
(def ktcp_b (c/mk c/K c/T c/C c/P c/_b))
(def ktcp_c (c/mk c/K c/T c/C c/P c/_c))
(def ktcp_d (c/mk c/K c/T c/C c/P c/_d))
(def ktcp_e (c/mk c/K c/T c/C c/P c/_e))
(def ktcp_f (c/mk c/K c/T c/C c/P c/_f))
(def ktcp_g (c/mk c/K c/T c/C c/P c/_g))
(def ktcp_h (c/mk c/K c/T c/C c/P c/_h))
(def ktcp_i (c/mk c/K c/T c/C c/P c/_i))
(def ktcp_j (c/mk c/K c/T c/C c/P c/_j))
(def ktcp_k (c/mk c/K c/T c/C c/P c/_k))
(def ktcp_l (c/mk c/K c/T c/C c/P c/_l))
(def ktcp_m (c/mk c/K c/T c/C c/P c/_m))
(def ktcp_n (c/mk c/K c/T c/C c/P c/_n))
(def ktcp_o (c/mk c/K c/T c/C c/P c/_o))
(def ktcp_p (c/mk c/K c/T c/C c/P c/_p))
(def ktcp_q (c/mk c/K c/T c/C c/P c/_q))
(def ktcp_r (c/mk c/K c/T c/C c/P c/_r))
(def ktcp_s (c/mk c/K c/T c/C c/P c/_s))
(def ktcp_t (c/mk c/K c/T c/C c/P c/_t))
(def ktcp_u (c/mk c/K c/T c/C c/P c/_u))
(def ktcp_v (c/mk c/K c/T c/C c/P c/_v))
(def ktcp_w (c/mk c/K c/T c/C c/P c/_w))
(def ktcp_x (c/mk c/K c/T c/C c/P c/_x))
(def ktcp_y (c/mk c/K c/T c/C c/P c/_y))
(def ktcp_z (c/mk c/K c/T c/C c/P c/_z))
(def ktcp_rt (c/mk c/K c/T c/C c/P c/_rt))

(def kotcp_a (c/mk c/K c/O c/T c/C c/P c/_a))
(def kotcp_b (c/mk c/K c/O c/T c/C c/P c/_b))
(def kotcp_c (c/mk c/K c/O c/T c/C c/P c/_c))
(def kotcp_d (c/mk c/K c/O c/T c/C c/P c/_d))
(def kotcp_e (c/mk c/K c/O c/T c/C c/P c/_e))
(def kotcp_f (c/mk c/K c/O c/T c/C c/P c/_f))
(def kotcp_g (c/mk c/K c/O c/T c/C c/P c/_g))
(def kotcp_h (c/mk c/K c/O c/T c/C c/P c/_h))
(def kotcp_i (c/mk c/K c/O c/T c/C c/P c/_i))
(def kotcp_j (c/mk c/K c/O c/T c/C c/P c/_j))
(def kotcp_k (c/mk c/K c/O c/T c/C c/P c/_k))
(def kotcp_l (c/mk c/K c/O c/T c/C c/P c/_l))
(def kotcp_m (c/mk c/K c/O c/T c/C c/P c/_m))
(def kotcp_n (c/mk c/K c/O c/T c/C c/P c/_n))
(def kotcp_o (c/mk c/K c/O c/T c/C c/P c/_o))
(def kotcp_p (c/mk c/K c/O c/T c/C c/P c/_p))
(def kotcp_q (c/mk c/K c/O c/T c/C c/P c/_q))
(def kotcp_r (c/mk c/K c/O c/T c/C c/P c/_r))
(def kotcp_s (c/mk c/K c/O c/T c/C c/P c/_s))
(def kotcp_t (c/mk c/K c/O c/T c/C c/P c/_t))
(def kotcp_u (c/mk c/K c/O c/T c/C c/P c/_u))
(def kotcp_v (c/mk c/K c/O c/T c/C c/P c/_v))
(def kotcp_w (c/mk c/K c/O c/T c/C c/P c/_w))
(def kotcp_x (c/mk c/K c/O c/T c/C c/P c/_x))
(def kotcp_y (c/mk c/K c/O c/T c/C c/P c/_y))
(def kotcp_z (c/mk c/K c/O c/T c/C c/P c/_z))
(def kotcp_rt (c/mk c/K c/O c/T c/C c/P c/_rt))

(def kep_a (c/mk c/K c/E c/P c/_a))
(def kep_b (c/mk c/K c/E c/P c/_b))
(def kep_c (c/mk c/K c/E c/P c/_c))
(def kep_d (c/mk c/K c/E c/P c/_d))
(def kep_e (c/mk c/K c/E c/P c/_e))
(def kep_f (c/mk c/K c/E c/P c/_f))
(def kep_g (c/mk c/K c/E c/P c/_g))
(def kep_h (c/mk c/K c/E c/P c/_h))
(def kep_i (c/mk c/K c/E c/P c/_i))
(def kep_j (c/mk c/K c/E c/P c/_j))
(def kep_k (c/mk c/K c/E c/P c/_k))
(def kep_l (c/mk c/K c/E c/P c/_l))
(def kep_m (c/mk c/K c/E c/P c/_m))
(def kep_n (c/mk c/K c/E c/P c/_n))
(def kep_o (c/mk c/K c/E c/P c/_o))
(def kep_p (c/mk c/K c/E c/P c/_p))
(def kep_q (c/mk c/K c/E c/P c/_q))
(def kep_r (c/mk c/K c/E c/P c/_r))
(def kep_s (c/mk c/K c/E c/P c/_s))
(def kep_t (c/mk c/K c/E c/P c/_t))
(def kep_u (c/mk c/K c/E c/P c/_u))
(def kep_v (c/mk c/K c/E c/P c/_v))
(def kep_w (c/mk c/K c/E c/P c/_w))
(def kep_x (c/mk c/K c/E c/P c/_x))
(def kep_y (c/mk c/K c/E c/P c/_y))
(def kep_z (c/mk c/K c/E c/P c/_z))
(def kep_rt (c/mk c/K c/E c/P c/_rt))

(def kwp_a (c/mk c/K c/W c/P c/_a))
(def kwp_b (c/mk c/K c/W c/P c/_b))
(def kwp_c (c/mk c/K c/W c/P c/_c))
(def kwp_d (c/mk c/K c/W c/P c/_d))
(def kwp_e (c/mk c/K c/W c/P c/_e))
(def kwp_f (c/mk c/K c/W c/P c/_f))
(def kwp_g (c/mk c/K c/W c/P c/_g))
(def kwp_h (c/mk c/K c/W c/P c/_h))
(def kwp_i (c/mk c/K c/W c/P c/_i))
(def kwp_j (c/mk c/K c/W c/P c/_j))
(def kwp_k (c/mk c/K c/W c/P c/_k))
(def kwp_l (c/mk c/K c/W c/P c/_l))
(def kwp_m (c/mk c/K c/W c/P c/_m))
(def kwp_n (c/mk c/K c/W c/P c/_n))
(def kwp_o (c/mk c/K c/W c/P c/_o))
(def kwp_p (c/mk c/K c/W c/P c/_p))
(def kwp_q (c/mk c/K c/W c/P c/_q))
(def kwp_r (c/mk c/K c/W c/P c/_r))
(def kwp_s (c/mk c/K c/W c/P c/_s))
(def kwp_t (c/mk c/K c/W c/P c/_t))
(def kwp_u (c/mk c/K c/W c/P c/_u))
(def kwp_v (c/mk c/K c/W c/P c/_v))
(def kwp_w (c/mk c/K c/W c/P c/_w))
(def kwp_x (c/mk c/K c/W c/P c/_x))
(def kwp_y (c/mk c/K c/W c/P c/_y))
(def kwp_z (c/mk c/K c/W c/P c/_z))
(def kwp_rt (c/mk c/K c/W c/P c/_rt))

(def kqp_a (c/mk c/K c/Q c/P c/_a))
(def kqp_b (c/mk c/K c/Q c/P c/_b))
(def kqp_c (c/mk c/K c/Q c/P c/_c))
(def kqp_d (c/mk c/K c/Q c/P c/_d))
(def kqp_e (c/mk c/K c/Q c/P c/_e))
(def kqp_f (c/mk c/K c/Q c/P c/_f))
(def kqp_g (c/mk c/K c/Q c/P c/_g))
(def kqp_h (c/mk c/K c/Q c/P c/_h))
(def kqp_i (c/mk c/K c/Q c/P c/_i))
(def kqp_j (c/mk c/K c/Q c/P c/_j))
(def kqp_k (c/mk c/K c/Q c/P c/_k))
(def kqp_l (c/mk c/K c/Q c/P c/_l))
(def kqp_m (c/mk c/K c/Q c/P c/_m))
(def kqp_n (c/mk c/K c/Q c/P c/_n))
(def kqp_o (c/mk c/K c/Q c/P c/_o))
(def kqp_p (c/mk c/K c/Q c/P c/_p))
(def kqp_q (c/mk c/K c/Q c/P c/_q))
(def kqp_r (c/mk c/K c/Q c/P c/_r))
(def kqp_s (c/mk c/K c/Q c/P c/_s))
(def kqp_t (c/mk c/K c/Q c/P c/_t))
(def kqp_u (c/mk c/K c/Q c/P c/_u))
(def kqp_v (c/mk c/K c/Q c/P c/_v))
(def kqp_w (c/mk c/K c/Q c/P c/_w))
(def kqp_x (c/mk c/K c/Q c/P c/_x))
(def kqp_y (c/mk c/K c/Q c/P c/_y))
(def kqp_z (c/mk c/K c/Q c/P c/_z))
(def kqp_rt (c/mk c/K c/Q c/P c/_rt))

(def kewqp_a (c/mk c/K c/E c/W c/Q c/P c/_a))
(def kewqp_b (c/mk c/K c/E c/W c/Q c/P c/_b))
(def kewqp_c (c/mk c/K c/E c/W c/Q c/P c/_c))
(def kewqp_d (c/mk c/K c/E c/W c/Q c/P c/_d))
(def kewqp_e (c/mk c/K c/E c/W c/Q c/P c/_e))
(def kewqp_f (c/mk c/K c/E c/W c/Q c/P c/_f))
(def kewqp_g (c/mk c/K c/E c/W c/Q c/P c/_g))
(def kewqp_h (c/mk c/K c/E c/W c/Q c/P c/_h))
(def kewqp_i (c/mk c/K c/E c/W c/Q c/P c/_i))
(def kewqp_j (c/mk c/K c/E c/W c/Q c/P c/_j))
(def kewqp_k (c/mk c/K c/E c/W c/Q c/P c/_k))
(def kewqp_l (c/mk c/K c/E c/W c/Q c/P c/_l))
(def kewqp_m (c/mk c/K c/E c/W c/Q c/P c/_m))
(def kewqp_n (c/mk c/K c/E c/W c/Q c/P c/_n))
(def kewqp_o (c/mk c/K c/E c/W c/Q c/P c/_o))
(def kewqp_p (c/mk c/K c/E c/W c/Q c/P c/_p))
(def kewqp_q (c/mk c/K c/E c/W c/Q c/P c/_q))
(def kewqp_r (c/mk c/K c/E c/W c/Q c/P c/_r))
(def kewqp_s (c/mk c/K c/E c/W c/Q c/P c/_s))
(def kewqp_t (c/mk c/K c/E c/W c/Q c/P c/_t))
(def kewqp_u (c/mk c/K c/E c/W c/Q c/P c/_u))
(def kewqp_v (c/mk c/K c/E c/W c/Q c/P c/_v))
(def kewqp_w (c/mk c/K c/E c/W c/Q c/P c/_w))
(def kewqp_x (c/mk c/K c/E c/W c/Q c/P c/_x))
(def kewqp_y (c/mk c/K c/E c/W c/Q c/P c/_y))
(def kewqp_z (c/mk c/K c/E c/W c/Q c/P c/_z))
(def kewqp_rt (c/mk c/K c/E c/W c/Q c/P c/_rt))

(def ksp_a (c/mk c/K c/S c/P c/_a))
(def ksp_b (c/mk c/K c/S c/P c/_b))
(def ksp_c (c/mk c/K c/S c/P c/_c))
(def ksp_d (c/mk c/K c/S c/P c/_d))
(def ksp_e (c/mk c/K c/S c/P c/_e))
(def ksp_f (c/mk c/K c/S c/P c/_f))
(def ksp_g (c/mk c/K c/S c/P c/_g))
(def ksp_h (c/mk c/K c/S c/P c/_h))
(def ksp_i (c/mk c/K c/S c/P c/_i))
(def ksp_j (c/mk c/K c/S c/P c/_j))
(def ksp_k (c/mk c/K c/S c/P c/_k))
(def ksp_l (c/mk c/K c/S c/P c/_l))
(def ksp_m (c/mk c/K c/S c/P c/_m))
(def ksp_n (c/mk c/K c/S c/P c/_n))
(def ksp_o (c/mk c/K c/S c/P c/_o))
(def ksp_p (c/mk c/K c/S c/P c/_p))
(def ksp_q (c/mk c/K c/S c/P c/_q))
(def ksp_r (c/mk c/K c/S c/P c/_r))
(def ksp_s (c/mk c/K c/S c/P c/_s))
(def ksp_t (c/mk c/K c/S c/P c/_t))
(def ksp_u (c/mk c/K c/S c/P c/_u))
(def ksp_v (c/mk c/K c/S c/P c/_v))
(def ksp_w (c/mk c/K c/S c/P c/_w))
(def ksp_x (c/mk c/K c/S c/P c/_x))
(def ksp_y (c/mk c/K c/S c/P c/_y))
(def ksp_z (c/mk c/K c/S c/P c/_z))
(def ksp_rt (c/mk c/K c/S c/P c/_rt))

(def kosp_a (c/mk c/K c/O c/S c/P c/_a))
(def kosp_b (c/mk c/K c/O c/S c/P c/_b))
(def kosp_c (c/mk c/K c/O c/S c/P c/_c))
(def kosp_d (c/mk c/K c/O c/S c/P c/_d))
(def kosp_e (c/mk c/K c/O c/S c/P c/_e))
(def kosp_f (c/mk c/K c/O c/S c/P c/_f))
(def kosp_g (c/mk c/K c/O c/S c/P c/_g))
(def kosp_h (c/mk c/K c/O c/S c/P c/_h))
(def kosp_i (c/mk c/K c/O c/S c/P c/_i))
(def kosp_j (c/mk c/K c/O c/S c/P c/_j))
(def kosp_k (c/mk c/K c/O c/S c/P c/_k))
(def kosp_l (c/mk c/K c/O c/S c/P c/_l))
(def kosp_m (c/mk c/K c/O c/S c/P c/_m))
(def kosp_n (c/mk c/K c/O c/S c/P c/_n))
(def kosp_o (c/mk c/K c/O c/S c/P c/_o))
(def kosp_p (c/mk c/K c/O c/S c/P c/_p))
(def kosp_q (c/mk c/K c/O c/S c/P c/_q))
(def kosp_r (c/mk c/K c/O c/S c/P c/_r))
(def kosp_s (c/mk c/K c/O c/S c/P c/_s))
(def kosp_t (c/mk c/K c/O c/S c/P c/_t))
(def kosp_u (c/mk c/K c/O c/S c/P c/_u))
(def kosp_v (c/mk c/K c/O c/S c/P c/_v))
(def kosp_w (c/mk c/K c/O c/S c/P c/_w))
(def kosp_x (c/mk c/K c/O c/S c/P c/_x))
(def kosp_y (c/mk c/K c/O c/S c/P c/_y))
(def kosp_z (c/mk c/K c/O c/S c/P c/_z))
(def kosp_rt (c/mk c/K c/O c/S c/P c/_rt))

(def ktsp_a (c/mk c/K c/T c/S c/P c/_a))
(def ktsp_b (c/mk c/K c/T c/S c/P c/_b))
(def ktsp_c (c/mk c/K c/T c/S c/P c/_c))
(def ktsp_d (c/mk c/K c/T c/S c/P c/_d))
(def ktsp_e (c/mk c/K c/T c/S c/P c/_e))
(def ktsp_f (c/mk c/K c/T c/S c/P c/_f))
(def ktsp_g (c/mk c/K c/T c/S c/P c/_g))
(def ktsp_h (c/mk c/K c/T c/S c/P c/_h))
(def ktsp_i (c/mk c/K c/T c/S c/P c/_i))
(def ktsp_j (c/mk c/K c/T c/S c/P c/_j))
(def ktsp_k (c/mk c/K c/T c/S c/P c/_k))
(def ktsp_l (c/mk c/K c/T c/S c/P c/_l))
(def ktsp_m (c/mk c/K c/T c/S c/P c/_m))
(def ktsp_n (c/mk c/K c/T c/S c/P c/_n))
(def ktsp_o (c/mk c/K c/T c/S c/P c/_o))
(def ktsp_p (c/mk c/K c/T c/S c/P c/_p))
(def ktsp_q (c/mk c/K c/T c/S c/P c/_q))
(def ktsp_r (c/mk c/K c/T c/S c/P c/_r))
(def ktsp_s (c/mk c/K c/T c/S c/P c/_s))
(def ktsp_t (c/mk c/K c/T c/S c/P c/_t))
(def ktsp_u (c/mk c/K c/T c/S c/P c/_u))
(def ktsp_v (c/mk c/K c/T c/S c/P c/_v))
(def ktsp_w (c/mk c/K c/T c/S c/P c/_w))
(def ktsp_x (c/mk c/K c/T c/S c/P c/_x))
(def ktsp_y (c/mk c/K c/T c/S c/P c/_y))
(def ktsp_z (c/mk c/K c/T c/S c/P c/_z))
(def ktsp_rt (c/mk c/K c/T c/S c/P c/_rt))

(def kcsp_a (c/mk c/K c/C c/S c/P c/_a))
(def kcsp_b (c/mk c/K c/C c/S c/P c/_b))
(def kcsp_c (c/mk c/K c/C c/S c/P c/_c))
(def kcsp_d (c/mk c/K c/C c/S c/P c/_d))
(def kcsp_e (c/mk c/K c/C c/S c/P c/_e))
(def kcsp_f (c/mk c/K c/C c/S c/P c/_f))
(def kcsp_g (c/mk c/K c/C c/S c/P c/_g))
(def kcsp_h (c/mk c/K c/C c/S c/P c/_h))
(def kcsp_i (c/mk c/K c/C c/S c/P c/_i))
(def kcsp_j (c/mk c/K c/C c/S c/P c/_j))
(def kcsp_k (c/mk c/K c/C c/S c/P c/_k))
(def kcsp_l (c/mk c/K c/C c/S c/P c/_l))
(def kcsp_m (c/mk c/K c/C c/S c/P c/_m))
(def kcsp_n (c/mk c/K c/C c/S c/P c/_n))
(def kcsp_o (c/mk c/K c/C c/S c/P c/_o))
(def kcsp_p (c/mk c/K c/C c/S c/P c/_p))
(def kcsp_q (c/mk c/K c/C c/S c/P c/_q))
(def kcsp_r (c/mk c/K c/C c/S c/P c/_r))
(def kcsp_s (c/mk c/K c/C c/S c/P c/_s))
(def kcsp_t (c/mk c/K c/C c/S c/P c/_t))
(def kcsp_u (c/mk c/K c/C c/S c/P c/_u))
(def kcsp_v (c/mk c/K c/C c/S c/P c/_v))
(def kcsp_w (c/mk c/K c/C c/S c/P c/_w))
(def kcsp_x (c/mk c/K c/C c/S c/P c/_x))
(def kcsp_y (c/mk c/K c/C c/S c/P c/_y))
(def kcsp_z (c/mk c/K c/C c/S c/P c/_z))
(def kcsp_rt (c/mk c/K c/C c/S c/P c/_rt))

(def kotsp_a (c/mk c/K c/O c/T c/S c/P c/_a))
(def kotsp_b (c/mk c/K c/O c/T c/S c/P c/_b))
(def kotsp_c (c/mk c/K c/O c/T c/S c/P c/_c))
(def kotsp_d (c/mk c/K c/O c/T c/S c/P c/_d))
(def kotsp_e (c/mk c/K c/O c/T c/S c/P c/_e))
(def kotsp_f (c/mk c/K c/O c/T c/S c/P c/_f))
(def kotsp_g (c/mk c/K c/O c/T c/S c/P c/_g))
(def kotsp_h (c/mk c/K c/O c/T c/S c/P c/_h))
(def kotsp_i (c/mk c/K c/O c/T c/S c/P c/_i))
(def kotsp_j (c/mk c/K c/O c/T c/S c/P c/_j))
(def kotsp_k (c/mk c/K c/O c/T c/S c/P c/_k))
(def kotsp_l (c/mk c/K c/O c/T c/S c/P c/_l))
(def kotsp_m (c/mk c/K c/O c/T c/S c/P c/_m))
(def kotsp_n (c/mk c/K c/O c/T c/S c/P c/_n))
(def kotsp_o (c/mk c/K c/O c/T c/S c/P c/_o))
(def kotsp_p (c/mk c/K c/O c/T c/S c/P c/_p))
(def kotsp_q (c/mk c/K c/O c/T c/S c/P c/_q))
(def kotsp_r (c/mk c/K c/O c/T c/S c/P c/_r))
(def kotsp_s (c/mk c/K c/O c/T c/S c/P c/_s))
(def kotsp_t (c/mk c/K c/O c/T c/S c/P c/_t))
(def kotsp_u (c/mk c/K c/O c/T c/S c/P c/_u))
(def kotsp_v (c/mk c/K c/O c/T c/S c/P c/_v))
(def kotsp_w (c/mk c/K c/O c/T c/S c/P c/_w))
(def kotsp_x (c/mk c/K c/O c/T c/S c/P c/_x))
(def kotsp_y (c/mk c/K c/O c/T c/S c/P c/_y))
(def kotsp_z (c/mk c/K c/O c/T c/S c/P c/_z))
(def kotsp_rt (c/mk c/K c/O c/T c/S c/P c/_rt))

(def kocsp_a (c/mk c/K c/O c/C c/S c/P c/_a))
(def kocsp_b (c/mk c/K c/O c/C c/S c/P c/_b))
(def kocsp_c (c/mk c/K c/O c/C c/S c/P c/_c))
(def kocsp_d (c/mk c/K c/O c/C c/S c/P c/_d))
(def kocsp_e (c/mk c/K c/O c/C c/S c/P c/_e))
(def kocsp_f (c/mk c/K c/O c/C c/S c/P c/_f))
(def kocsp_g (c/mk c/K c/O c/C c/S c/P c/_g))
(def kocsp_h (c/mk c/K c/O c/C c/S c/P c/_h))
(def kocsp_i (c/mk c/K c/O c/C c/S c/P c/_i))
(def kocsp_j (c/mk c/K c/O c/C c/S c/P c/_j))
(def kocsp_k (c/mk c/K c/O c/C c/S c/P c/_k))
(def kocsp_l (c/mk c/K c/O c/C c/S c/P c/_l))
(def kocsp_m (c/mk c/K c/O c/C c/S c/P c/_m))
(def kocsp_n (c/mk c/K c/O c/C c/S c/P c/_n))
(def kocsp_o (c/mk c/K c/O c/C c/S c/P c/_o))
(def kocsp_p (c/mk c/K c/O c/C c/S c/P c/_p))
(def kocsp_q (c/mk c/K c/O c/C c/S c/P c/_q))
(def kocsp_r (c/mk c/K c/O c/C c/S c/P c/_r))
(def kocsp_s (c/mk c/K c/O c/C c/S c/P c/_s))
(def kocsp_t (c/mk c/K c/O c/C c/S c/P c/_t))
(def kocsp_u (c/mk c/K c/O c/C c/S c/P c/_u))
(def kocsp_v (c/mk c/K c/O c/C c/S c/P c/_v))
(def kocsp_w (c/mk c/K c/O c/C c/S c/P c/_w))
(def kocsp_x (c/mk c/K c/O c/C c/S c/P c/_x))
(def kocsp_y (c/mk c/K c/O c/C c/S c/P c/_y))
(def kocsp_z (c/mk c/K c/O c/C c/S c/P c/_z))
(def kocsp_rt (c/mk c/K c/O c/C c/S c/P c/_rt))

(def ktcsp_a (c/mk c/K c/T c/C c/S c/P c/_a))
(def ktcsp_b (c/mk c/K c/T c/C c/S c/P c/_b))
(def ktcsp_c (c/mk c/K c/T c/C c/S c/P c/_c))
(def ktcsp_d (c/mk c/K c/T c/C c/S c/P c/_d))
(def ktcsp_e (c/mk c/K c/T c/C c/S c/P c/_e))
(def ktcsp_f (c/mk c/K c/T c/C c/S c/P c/_f))
(def ktcsp_g (c/mk c/K c/T c/C c/S c/P c/_g))
(def ktcsp_h (c/mk c/K c/T c/C c/S c/P c/_h))
(def ktcsp_i (c/mk c/K c/T c/C c/S c/P c/_i))
(def ktcsp_j (c/mk c/K c/T c/C c/S c/P c/_j))
(def ktcsp_k (c/mk c/K c/T c/C c/S c/P c/_k))
(def ktcsp_l (c/mk c/K c/T c/C c/S c/P c/_l))
(def ktcsp_m (c/mk c/K c/T c/C c/S c/P c/_m))
(def ktcsp_n (c/mk c/K c/T c/C c/S c/P c/_n))
(def ktcsp_o (c/mk c/K c/T c/C c/S c/P c/_o))
(def ktcsp_p (c/mk c/K c/T c/C c/S c/P c/_p))
(def ktcsp_q (c/mk c/K c/T c/C c/S c/P c/_q))
(def ktcsp_r (c/mk c/K c/T c/C c/S c/P c/_r))
(def ktcsp_s (c/mk c/K c/T c/C c/S c/P c/_s))
(def ktcsp_t (c/mk c/K c/T c/C c/S c/P c/_t))
(def ktcsp_u (c/mk c/K c/T c/C c/S c/P c/_u))
(def ktcsp_v (c/mk c/K c/T c/C c/S c/P c/_v))
(def ktcsp_w (c/mk c/K c/T c/C c/S c/P c/_w))
(def ktcsp_x (c/mk c/K c/T c/C c/S c/P c/_x))
(def ktcsp_y (c/mk c/K c/T c/C c/S c/P c/_y))
(def ktcsp_z (c/mk c/K c/T c/C c/S c/P c/_z))
(def ktcsp_rt (c/mk c/K c/T c/C c/S c/P c/_rt))

(def kotcsp_a (c/mk c/K c/O c/T c/C c/R c/P c/_a))
(def kotcsp_b (c/mk c/K c/O c/T c/C c/R c/P c/_b))
(def kotcsp_c (c/mk c/K c/O c/T c/C c/R c/P c/_c))
(def kotcsp_d (c/mk c/K c/O c/T c/C c/R c/P c/_d))
(def kotcsp_e (c/mk c/K c/O c/T c/C c/R c/P c/_e))
(def kotcsp_f (c/mk c/K c/O c/T c/C c/R c/P c/_f))
(def kotcsp_g (c/mk c/K c/O c/T c/C c/R c/P c/_g))
(def kotcsp_h (c/mk c/K c/O c/T c/C c/R c/P c/_h))
(def kotcsp_i (c/mk c/K c/O c/T c/C c/R c/P c/_i))
(def kotcsp_j (c/mk c/K c/O c/T c/C c/R c/P c/_j))
(def kotcsp_k (c/mk c/K c/O c/T c/C c/R c/P c/_k))
(def kotcsp_l (c/mk c/K c/O c/T c/C c/R c/P c/_l))
(def kotcsp_m (c/mk c/K c/O c/T c/C c/R c/P c/_m))
(def kotcsp_n (c/mk c/K c/O c/T c/C c/R c/P c/_n))
(def kotcsp_o (c/mk c/K c/O c/T c/C c/R c/P c/_o))
(def kotcsp_p (c/mk c/K c/O c/T c/C c/R c/P c/_p))
(def kotcsp_q (c/mk c/K c/O c/T c/C c/R c/P c/_q))
(def kotcsp_r (c/mk c/K c/O c/T c/C c/R c/P c/_r))
(def kotcsp_s (c/mk c/K c/O c/T c/C c/R c/P c/_s))
(def kotcsp_t (c/mk c/K c/O c/T c/C c/R c/P c/_t))
(def kotcsp_u (c/mk c/K c/O c/T c/C c/R c/P c/_u))
(def kotcsp_v (c/mk c/K c/O c/T c/C c/R c/P c/_v))
(def kotcsp_w (c/mk c/K c/O c/T c/C c/R c/P c/_w))
(def kotcsp_x (c/mk c/K c/O c/T c/C c/R c/P c/_x))
(def kotcsp_y (c/mk c/K c/O c/T c/C c/R c/P c/_y))
(def kotcsp_z (c/mk c/K c/O c/T c/C c/R c/P c/_z))
(def kotcsp_rt (c/mk c/K c/O c/T c/C c/R c/P c/_rt))

(def kerp_a (c/mk c/K c/E c/R c/P c/_a))
(def kerp_b (c/mk c/K c/E c/R c/P c/_b))
(def kerp_c (c/mk c/K c/E c/R c/P c/_c))
(def kerp_d (c/mk c/K c/E c/R c/P c/_d))
(def kerp_e (c/mk c/K c/E c/R c/P c/_e))
(def kerp_f (c/mk c/K c/E c/R c/P c/_f))
(def kerp_g (c/mk c/K c/E c/R c/P c/_g))
(def kerp_h (c/mk c/K c/E c/R c/P c/_h))
(def kerp_i (c/mk c/K c/E c/R c/P c/_i))
(def kerp_j (c/mk c/K c/E c/R c/P c/_j))
(def kerp_k (c/mk c/K c/E c/R c/P c/_k))
(def kerp_l (c/mk c/K c/E c/R c/P c/_l))
(def kerp_m (c/mk c/K c/E c/R c/P c/_m))
(def kerp_n (c/mk c/K c/E c/R c/P c/_n))
(def kerp_o (c/mk c/K c/E c/R c/P c/_o))
(def kerp_p (c/mk c/K c/E c/R c/P c/_p))
(def kerp_q (c/mk c/K c/E c/R c/P c/_q))
(def kerp_r (c/mk c/K c/E c/R c/P c/_r))
(def kerp_s (c/mk c/K c/E c/R c/P c/_s))
(def kerp_t (c/mk c/K c/E c/R c/P c/_t))
(def kerp_u (c/mk c/K c/E c/R c/P c/_u))
(def kerp_v (c/mk c/K c/E c/R c/P c/_v))
(def kerp_w (c/mk c/K c/E c/R c/P c/_w))
(def kerp_x (c/mk c/K c/E c/R c/P c/_x))
(def kerp_y (c/mk c/K c/E c/R c/P c/_y))
(def kerp_z (c/mk c/K c/E c/R c/P c/_z))
(def kerp_rt (c/mk c/K c/E c/R c/P c/_rt))

(def kwsp_a (c/mk c/K c/W c/S c/P c/_a))
(def kwsp_b (c/mk c/K c/W c/S c/P c/_b))
(def kwsp_c (c/mk c/K c/W c/S c/P c/_c))
(def kwsp_d (c/mk c/K c/W c/S c/P c/_d))
(def kwsp_e (c/mk c/K c/W c/S c/P c/_e))
(def kwsp_f (c/mk c/K c/W c/S c/P c/_f))
(def kwsp_g (c/mk c/K c/W c/S c/P c/_g))
(def kwsp_h (c/mk c/K c/W c/S c/P c/_h))
(def kwsp_i (c/mk c/K c/W c/S c/P c/_i))
(def kwsp_j (c/mk c/K c/W c/S c/P c/_j))
(def kwsp_k (c/mk c/K c/W c/S c/P c/_k))
(def kwsp_l (c/mk c/K c/W c/S c/P c/_l))
(def kwsp_m (c/mk c/K c/W c/S c/P c/_m))
(def kwsp_n (c/mk c/K c/W c/S c/P c/_n))
(def kwsp_o (c/mk c/K c/W c/S c/P c/_o))
(def kwsp_p (c/mk c/K c/W c/S c/P c/_p))
(def kwsp_q (c/mk c/K c/W c/S c/P c/_q))
(def kwsp_r (c/mk c/K c/W c/S c/P c/_r))
(def kwsp_s (c/mk c/K c/W c/S c/P c/_s))
(def kwsp_t (c/mk c/K c/W c/S c/P c/_t))
(def kwsp_u (c/mk c/K c/W c/S c/P c/_u))
(def kwsp_v (c/mk c/K c/W c/S c/P c/_v))
(def kwsp_w (c/mk c/K c/W c/S c/P c/_w))
(def kwsp_x (c/mk c/K c/W c/S c/P c/_x))
(def kwsp_y (c/mk c/K c/W c/S c/P c/_y))
(def kwsp_z (c/mk c/K c/W c/S c/P c/_z))
(def kwsp_rt (c/mk c/K c/W c/S c/P c/_rt))

(def kqrp_a (c/mk c/K c/Q c/R c/P c/_a))
(def kqrp_b (c/mk c/K c/Q c/R c/P c/_b))
(def kqrp_c (c/mk c/K c/Q c/R c/P c/_c))
(def kqrp_d (c/mk c/K c/Q c/R c/P c/_d))
(def kqrp_e (c/mk c/K c/Q c/R c/P c/_e))
(def kqrp_f (c/mk c/K c/Q c/R c/P c/_f))
(def kqrp_g (c/mk c/K c/Q c/R c/P c/_g))
(def kqrp_h (c/mk c/K c/Q c/R c/P c/_h))
(def kqrp_i (c/mk c/K c/Q c/R c/P c/_i))
(def kqrp_j (c/mk c/K c/Q c/R c/P c/_j))
(def kqrp_k (c/mk c/K c/Q c/R c/P c/_k))
(def kqrp_l (c/mk c/K c/Q c/R c/P c/_l))
(def kqrp_m (c/mk c/K c/Q c/R c/P c/_m))
(def kqrp_n (c/mk c/K c/Q c/R c/P c/_n))
(def kqrp_o (c/mk c/K c/Q c/R c/P c/_o))
(def kqrp_p (c/mk c/K c/Q c/R c/P c/_p))
(def kqrp_q (c/mk c/K c/Q c/R c/P c/_q))
(def kqrp_r (c/mk c/K c/Q c/R c/P c/_r))
(def kqrp_s (c/mk c/K c/Q c/R c/P c/_s))
(def kqrp_t (c/mk c/K c/Q c/R c/P c/_t))
(def kqrp_u (c/mk c/K c/Q c/R c/P c/_u))
(def kqrp_v (c/mk c/K c/Q c/R c/P c/_v))
(def kqrp_w (c/mk c/K c/Q c/R c/P c/_w))
(def kqrp_x (c/mk c/K c/Q c/R c/P c/_x))
(def kqrp_y (c/mk c/K c/Q c/R c/P c/_y))
(def kqrp_z (c/mk c/K c/Q c/R c/P c/_z))
(def kqrp_rt (c/mk c/K c/Q c/R c/P c/_rt))

(def kewqsp_a (c/mk c/K c/E c/W c/Q c/S c/P c/_a))
(def kewqsp_b (c/mk c/K c/E c/W c/Q c/S c/P c/_b))
(def kewqsp_c (c/mk c/K c/E c/W c/Q c/S c/P c/_c))
(def kewqsp_d (c/mk c/K c/E c/W c/Q c/S c/P c/_d))
(def kewqsp_e (c/mk c/K c/E c/W c/Q c/S c/P c/_e))
(def kewqsp_f (c/mk c/K c/E c/W c/Q c/S c/P c/_f))
(def kewqsp_g (c/mk c/K c/E c/W c/Q c/S c/P c/_g))
(def kewqsp_h (c/mk c/K c/E c/W c/Q c/S c/P c/_h))
(def kewqsp_i (c/mk c/K c/E c/W c/Q c/S c/P c/_i))
(def kewqsp_j (c/mk c/K c/E c/W c/Q c/S c/P c/_j))
(def kewqsp_k (c/mk c/K c/E c/W c/Q c/S c/P c/_k))
(def kewqsp_l (c/mk c/K c/E c/W c/Q c/S c/P c/_l))
(def kewqsp_m (c/mk c/K c/E c/W c/Q c/S c/P c/_m))
(def kewqsp_n (c/mk c/K c/E c/W c/Q c/S c/P c/_n))
(def kewqsp_o (c/mk c/K c/E c/W c/Q c/S c/P c/_o))
(def kewqsp_p (c/mk c/K c/E c/W c/Q c/S c/P c/_p))
(def kewqsp_q (c/mk c/K c/E c/W c/Q c/S c/P c/_q))
(def kewqsp_r (c/mk c/K c/E c/W c/Q c/S c/P c/_r))
(def kewqsp_s (c/mk c/K c/E c/W c/Q c/S c/P c/_s))
(def kewqsp_t (c/mk c/K c/E c/W c/Q c/S c/P c/_t))
(def kewqsp_u (c/mk c/K c/E c/W c/Q c/S c/P c/_u))
(def kewqsp_v (c/mk c/K c/E c/W c/Q c/S c/P c/_v))
(def kewqsp_w (c/mk c/K c/E c/W c/Q c/S c/P c/_w))
(def kewqsp_x (c/mk c/K c/E c/W c/Q c/S c/P c/_x))
(def kewqsp_y (c/mk c/K c/E c/W c/Q c/S c/P c/_y))
(def kewqsp_z (c/mk c/K c/E c/W c/Q c/S c/P c/_z))
(def kewqsp_rt (c/mk c/K c/E c/W c/Q c/S c/P c/_rt))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
