;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; config
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(ns config.function
(:require
            [config.config :as c]))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; function
(def ks_f1  (c/mk c/K c/S c/_f1))
(def ks_f2  (c/mk c/K c/S c/_f2))
(def ks_f3  (c/mk c/K c/S c/_f3))
(def ks_f4  (c/mk c/K c/S c/_f4))
(def ks_f5  (c/mk c/K c/S c/_f5))
(def ks_f6  (c/mk c/K c/S c/_f6))
(def ks_f7  (c/mk c/K c/S c/_f7))
(def ks_f8  (c/mk c/K c/S c/_f8))
(def ks_f9  (c/mk c/K c/S c/_f9))
(def ks_f10 (c/mk c/K c/S c/_f10))
(def ks_f11 (c/mk c/K c/S c/_f11))
(def ks_f12 (c/mk c/K c/S c/_f12))

(def ko_f1  (c/mk c/K c/O c/_f1))
(def ko_f2  (c/mk c/K c/O c/_f2))
(def ko_f3  (c/mk c/K c/O c/_f3))
(def ko_f4  (c/mk c/K c/O c/_f4))
(def ko_f5  (c/mk c/K c/O c/_f5))
(def ko_f6  (c/mk c/K c/O c/_f6))
(def ko_f7  (c/mk c/K c/O c/_f7))
(def ko_f8  (c/mk c/K c/O c/_f8))
(def ko_f9  (c/mk c/K c/O c/_f9))
(def ko_f10 (c/mk c/K c/O c/_f10))
(def ko_f11 (c/mk c/K c/O c/_f11))
(def ko_f12 (c/mk c/K c/O c/_f12))

(def kt_f1  (c/mk c/K c/T c/_f1))
(def kt_f2  (c/mk c/K c/T c/_f2))
(def kt_f3  (c/mk c/K c/T c/_f3))
(def kt_f4  (c/mk c/K c/T c/_f4))
(def kt_f5  (c/mk c/K c/T c/_f5))
(def kt_f6  (c/mk c/K c/T c/_f6))
(def kt_f7  (c/mk c/K c/T c/_f7))
(def kt_f8  (c/mk c/K c/T c/_f8))
(def kt_f9  (c/mk c/K c/T c/_f9))
(def kt_f10 (c/mk c/K c/T c/_f10))
(def kt_f11 (c/mk c/K c/T c/_f11))
(def kt_f12 (c/mk c/K c/T c/_f12))

(def kts_f1  (c/mk c/K c/T c/S c/_f1))
(def kts_f2  (c/mk c/K c/T c/S c/_f2))
(def kts_f3  (c/mk c/K c/T c/S c/_f3))
(def kts_f4  (c/mk c/K c/T c/S c/_f4))
(def kts_f5  (c/mk c/K c/T c/S c/_f5))
(def kts_f6  (c/mk c/K c/T c/S c/_f6))
(def kts_f7  (c/mk c/K c/T c/S c/_f7))
(def kts_f8  (c/mk c/K c/T c/S c/_f8))
(def kts_f9  (c/mk c/K c/T c/S c/_f9))
(def kts_f10 (c/mk c/K c/T c/S c/_f10))
(def kts_f11 (c/mk c/K c/T c/S c/_f11))
(def kts_f12 (c/mk c/K c/T c/S c/_f12))

(def kos_f1  (c/mk c/K c/O c/S c/_f1))
(def kos_f2  (c/mk c/K c/O c/S c/_f2))
(def kos_f3  (c/mk c/K c/O c/S c/_f3))
(def kos_f4  (c/mk c/K c/O c/S c/_f4))
(def kos_f5  (c/mk c/K c/O c/S c/_f5))
(def kos_f6  (c/mk c/K c/O c/S c/_f6))
(def kos_f7  (c/mk c/K c/O c/S c/_f7))
(def kos_f8  (c/mk c/K c/O c/S c/_f8))
(def kos_f9  (c/mk c/K c/O c/S c/_f9))
(def kos_f10 (c/mk c/K c/O c/S c/_f10))
(def kos_f11 (c/mk c/K c/O c/S c/_f11))
(def kos_f12 (c/mk c/K c/O c/S c/_f12))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(def ks_f13 (c/mk c/K c/S c/_f13))
(def ks_f14 (c/mk c/K c/S c/_f14))
(def ks_f15 (c/mk c/K c/S c/_f15))
(def ks_f16 (c/mk c/K c/S c/_f16))
(def ks_f17 (c/mk c/K c/S c/_f17))
(def ks_f18 (c/mk c/K c/S c/_f18))
(def ks_f19 (c/mk c/K c/S c/_f19))
(def ks_f20 (c/mk c/K c/S c/_f20))

(def ko_f13 (c/mk c/K c/O c/_f13))
(def ko_f14 (c/mk c/K c/O c/_f14))
(def ko_f15 (c/mk c/K c/O c/_f15))
(def ko_f16 (c/mk c/K c/O c/_f16))
(def ko_f17 (c/mk c/K c/O c/_f17))
(def ko_f18 (c/mk c/K c/O c/_f18))
(def ko_f19 (c/mk c/K c/O c/_f19))
(def ko_f20 (c/mk c/K c/O c/_f20))

(def kt_f13 (c/mk c/K c/T c/_f13))
(def kt_f14 (c/mk c/K c/T c/_f14))
(def kt_f15 (c/mk c/K c/T c/_f15))
(def kt_f16 (c/mk c/K c/T c/_f16))
(def kt_f17 (c/mk c/K c/T c/_f17))
(def kt_f18 (c/mk c/K c/T c/_f18))
(def kt_f19 (c/mk c/K c/T c/_f19))
(def kt_f20 (c/mk c/K c/T c/_f20))

(def kts_f13 (c/mk c/K c/T c/S c/_f13))
(def kts_f14 (c/mk c/K c/T c/S c/_f14))
(def kts_f15 (c/mk c/K c/T c/S c/_f15))
(def kts_f16 (c/mk c/K c/T c/S c/_f16))
(def kts_f17 (c/mk c/K c/T c/S c/_f17))
(def kts_f18 (c/mk c/K c/T c/S c/_f18))
(def kts_f19 (c/mk c/K c/T c/S c/_f19))
(def kts_f20 (c/mk c/K c/T c/S c/_f20))

(def kos_f13 (c/mk c/K c/O c/S c/_f13))
(def kos_f14 (c/mk c/K c/O c/S c/_f14))
(def kos_f15 (c/mk c/K c/O c/S c/_f15))
(def kos_f16 (c/mk c/K c/O c/S c/_f16))
(def kos_f17 (c/mk c/K c/O c/S c/_f17))
(def kos_f18 (c/mk c/K c/O c/S c/_f18))
(def kos_f19 (c/mk c/K c/O c/S c/_f19))
(def kos_f20 (c/mk c/K c/O c/S c/_f20))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
