;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(ns config.helix)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(def line-start              ["goto_line_start"])
(def line-end                ["goto_line_end", "move_char_right"])
(def file-start              ["goto_file_start"])
(def file-end                ["goto_last_line"])
(def select-line-start       ["select_mode", "goto_line_start", "MODE"])
(def select-line-end         ["select_mode", "goto_line_end", "MODE"])
(def select-file-start       ["extend_to_file_start"])
(def select-file-end         ["extend_to_file_end"])
(def scroll-up               ["scroll_up"])
(def scroll-down             ["scroll_down"])

(def split-left              ["jump_view_left"])
(def split-right             ["jump_view_right"])
(def split-up                ["jump_view_up"])
(def split-down              ["jump_view_down"])
(def jump                    ["goto_word"])

(def prev-word               ["move_prev_word_start", "collapse_selection"])
(def next-word               ["move_next_word_end", "collapse_selection"])
(def prev-para               ["goto_prev_paragraph"  "collapse_selection"])
(def next-para               ["goto_next_paragraph"  "collapse_selection"])
(def select-prev-word        ["extend_prev_word_start"])
(def select-next-word        ["extend_next_word_end"])
(def format-hx               [":format"])
(def git-blame               [":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"])
(def copy                    ["yank_to_clipboard"])
(def spawn-multi             ["search_selection", "extend_search_next"])
(def comment-hx              ["toggle_comments"])
(def search                  ["search"])
(def find-prev               ["search_prev"])
(def spawn-down              ["normal_mode", "copy_selection_on_next_line", "MODE"])
(def spawn-up                ["normal_mode", "copy_selection_on_prev_line", "MODE"])
(def find-next               ["search_next"])
(def record                  ["record_macro"])
(def new                     [":new"])
(def quit                    ["normal_mode", ":quit-all"])
(def reload                  ["normal_mode", ":reload-all", "MODE"])
(def write-quit              ["normal_mode", ":write-quit-all"])
(def paste                   ["paste_clipboard_before"])
(def write                   ["normal_mode", ":write"])
(def todor-compile           [":sh roadmap"])
(def cut                     ["yank_to_clipboard", "delete_selection_noyank"])
(def skip-multi              ["search_selection", "search_next"])
(def rm-multi                ["search_selection", "search_prev"])
(def cmd                     ["command_mode"])
(def select-all              ["select_all"])
(def copy-line               ["extend_to_line_bounds", "yank_to_clipboard"])
(def dup-line                ["extend_to_line_bounds", "yank", "paste_after", "goto_line_start"])
(def global-search           ["global_search"])
(def indent                  ["indent"])
(def line-down               ["normal_mode", "extend_to_line_bounds", "delete_selection", "paste_after", "MODE"])
(def line-up                 ["normal_mode", "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "MODE"])
(def select-line             ["extend_to_line_bounds", "MODE"])
(def play                    ["replay_macro"])
(def unindent                ["unindent"])
(def paste-in-place          ["replace_selections_with_clipboard"])
(def cut-line                ["extend_to_line_bounds", "delete_selection_noyank"])
(def copy-diag               [":yank-diagnostic"])
(def git-diff                [":sh zellij run --name git-diff --pinned true                  --floating  --width 100%% --height 100%% --x    0 --y    0 -- git diff %{buffer_name} | delta --paging=always > /dev/null 2>&1"])
(def yazi                    [":sh zellij run --name explorer --pinned true  --close-on-exit --floating  --width 100%% --height 100%% --x    0 --y    0 -- yazi $(pwd) > /dev/null 2>&1"])
(def lazygit                 [":sh zellij run --name lazygit  --pinned true  --close-on-exit --floating  --width 100%% --height 100%% --x    0 --y    0 -- lazygit > /dev/null 2>&1"])
(def serpl                   [":sh zellij run --name serpl    --pinned true  --close-on-exit --floating  --width 100%% --height 100%% --x    0 --y    0 -- serpl > /dev/null 2>&1"])
(def todor-interactive       [":sh zellij run --name todor    --pinned true  --close-on-exit --floating  --width  50%% --height 100%% --x 50%% --y    0 -- todor --delete > /dev/null 2>&1"])
(def install                 [":sh zellij run --name install  --pinned true                  --floating  --width  50%% --height  50%% --x 50%% --y    0 -- just install > /dev/null 2>&1"])
(def watch                   [":sh zellij run --name watch    --pinned true                  --floating  --width  50%% --height  50%% --x 50%% --y    0 -- just watch > /dev/null 2>&1"])
(def btm                     [":sh zellij run --name bottom   --pinned true  --close-on-exit --floating  --width  50%% --height 100%% --x 50%% --y    0 -- btm > /dev/null 2>&1"])
(def shell                   [":sh zellij run --name canvas   --pinned false --close-on-exit --floating  --width 100%% --height 100%% --x    0 --y    0 -- zsh > /dev/null 2>&1"])
(def buffer-copy             [":sh copy2clipboard %{buffer_name}"])

(def change-picker           ["changed_file_picker"])
(def file-picker-hx             ["file_explorer"])
(def buffer-picker           ["buffer_picker"])

(def select-left             ["extend_char_left"])
(def select-right            ["extend_char_right"])
(def select-up               ["extend_line_up"])
(def select-down             ["extend_line_down"])
(def delete                  ["delete_selection_noyank"])
(def delete-word-right       ["delete_word_forward"])
(def delete-line-end         ["kill_to_line_end"])

(def last-mod                ["goto_last_modification"])
(def del-char-back           ["delete_char_backward"])
(def del-word-back           ["delete_word_backward"])
(def del-start-line          ["kill_to_line_start"])

(def close-tab               [":buffer-close"])
(def decrement               ["decrement"])
(def file-picker-hx          ["file_picker"])
(def hsplit                  ["hsplit"])
(def increment               ["increment"])
(def last-move               ["repeat_last_motion"])
(def last-tab                ["goto_last_accessed_file"])
(def lower-case              ["switch_to_lowercase"])
(def next-comm               ["goto_next_comment"])
(def next-diff               ["goto_next_change"])
(def next-move               ["normal_mode", "find_till_char", "MODE"])
(def next-tab                ["goto_next_buffer"])
(def prev-comm               ["goto_prev_comment"])
(def prev-diff               ["goto_prev_change"])
(def prev-move               ["normal_mode", "till_prev_char", "MODE"])
(def prev-tab                ["goto_previous_buffer"])
(def redo                    ["redo"])
(def switch-case             ["switch_case"])
(def undo                    ["undo"])
(def wclose                  ["wclose"])
(def wonly                   ["wonly"])
(def upper-case              ["switch_to_uppercase"])
(def vsplit                  ["vsplit"])

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(def i-completion            ["completion"])
(def n-hover                 ["hover"])
(def s-hover                 ["hover"])

(def i-normal                ["normal_mode"])
(def n-insert                ["insert_mode"])
(def s-normal                ["normal_mode"])

; TODO: refactor as one command => hi-select, hn-select & hs-select, etc
(def i-select-prev-para      ["select_mode" "goto_prev_paragraph" "insert_mode"])
(def i-select-next-para      ["select_mode" "goto_next_paragraph" "append_mode" "extend_char_left"])
(def i-select-para           ["goto_next_paragraph" "collapse_selection" "select_mode" "goto_prev_paragraph" "trim_selections" "insert_mode"])

(def n-select-prev-para      ["select_mode" "goto_prev_paragraph" "normal_mode"])
(def n-select-next-para      ["select_mode" "goto_next_paragraph" "normal_mode"])
(def n-select-para           ["goto_next_paragraph" "collapse_selection" "select_mode" "goto_prev_paragraph" "trim_selections" "normal_mode"])

(def s-select-prev-para      ["select_mode" "goto_prev_paragraph" "select_mode"])
(def s-select-next-para      ["select_mode" "goto_next_paragraph" "select_mode"])
(def s-select-para           ["goto_next_paragraph" "collapse_selection" "select_mode" "goto_prev_paragraph" "trim_selections" "select_mode"])

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
