;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(ns config.micro)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(def line-start              ["StartOfLine"])
(def line-end                ["EndOfLine"])
(def file-start              ["CursorStart"])
(def file-end                ["CursorEnd"])
(def select-line-start       ["SelectToStartOfLine"])
(def select-line-end         ["SelectToEndOfLine"])
(def select-file-start       ["SelectToStart"])
(def select-file-end         ["SelectToEnd"])

(def prev-split              ["PreviousSplit"])
(def next-split              ["NextSplit"])
(def jump                    ["JumpLine"])

(def prev-para               ["ParagraphPrevious"])
(def next-para               ["ParagraphNext"])
(def select-prev-word        ["SelectWordLeft"])
(def select-next-word        ["SelectWordRight"])
(def select-prev-para        ["SelectToParagraphPrevious"])
(def select-next-para        ["SelectToParagraphNext"])
(def copy                    ["Copy"])
(def spawn-multi             ["SpawnMultiCursor"])
(def comment-mc              ["lua:comment.comment"])
(def search                  ["FindLiteral"])
(def find-prev               ["FindPrevious"])
(def spawn-down              ["SpawnMultiCursorDown"])
(def spawn-up                ["SpawnMultiCursorUp"])
(def find-next               ["FindNext"])
(def record                  ["ToggleMacro"])
(def new                     ["AddTab"])
(def quit                    ["QuitAll"])
(def write-quit              ["Save,QuitAll"])
(def paste                   ["Paste"])
(def write                   ["Save"])
(def cut                     ["Cut"])
(def skip-multi              ["SkipMultiCursor"])
(def rm-multi                ["RemoveMultiCursor"])
(def cmd                     ["CommandMode"])
(def select-all              ["SelectAll"])
(def copy-line               ["CopyLine"])
(def dup-line                ["DuplicateLine"])
(def global-search           ["Find"])
(def indent                  ["IndentSelection"])
(def line-down               ["MoveLinesDown"])
(def line-up                 ["MoveLinesUp"])
(def select-line             ["SelectLine"])
(def play                    ["PlayMacro"])
(def unindent                ["OutdentSelection"])
(def cut-line                ["CutLine"])
(def shell                   ["ShellMode"])

(def delete-word-right       ["DeleteWordRight"])
(def delete-line-end         ["SelectToEndOfLine,Delete"])

(def del-word-back           ["DeleteWordLeft"])
(def del-start-line          ["SelectToStartOfLine,Delete"])

(def close-tab               ["Quit"])
(def hsplit                  ["HSplit"])
(def next-diff               ["DiffNext"])
(def next-tab                ["NextTab"])
(def open-file               ["OpenFile"])
(def prev-diff               ["DiffPrevious"])
(def prev-tab                ["PreviousTab"])
(def redo                    ["Redo"])
(def undo                    ["Undo"])
(def unsplit                 ["Unsplit"])
(def vsplit                  ["VSplit"])

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
