;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; numeric
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(ns config.numeric
(:require
            [config.config :as c]))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; numeric glyphs
(def k_1 (c/mk c/_1))
(def k_2 (c/mk c/_2))
(def k_3 (c/mk c/_3))
(def k_4 (c/mk c/_4))
(def k_5 (c/mk c/_5))
(def k_6 (c/mk c/_6))
(def k_7 (c/mk c/_7))
(def k_8 (c/mk c/_8))
(def k_9 (c/mk c/_9))
(def k_0 (c/mk c/_0))
(def k_hy (c/mk c/_hy))
(def k_eq (c/mk c/_eq))

(def ko_1  (c/mk c/K c/O c/_1))
(def ko_2  (c/mk c/K c/O c/_2))
(def ko_3  (c/mk c/K c/O c/_3))
(def ko_4  (c/mk c/K c/O c/_4))
(def ko_5  (c/mk c/K c/O c/_5))
(def ko_6  (c/mk c/K c/O c/_6))
(def ko_7  (c/mk c/K c/O c/_7))
(def ko_8  (c/mk c/K c/O c/_8))
(def ko_9  (c/mk c/K c/O c/_9))
(def ko_0  (c/mk c/K c/O c/_0))
(def ko_hy (c/mk c/K c/O c/_hy))
(def ko_eq (c/mk c/K c/O c/_eq))

(def kt_1  (c/mk c/K c/T c/_1))
(def kt_2  (c/mk c/K c/T c/_2))
(def kt_3  (c/mk c/K c/T c/_3))
(def kt_4  (c/mk c/K c/T c/_4))
(def kt_5  (c/mk c/K c/T c/_5))
(def kt_6  (c/mk c/K c/T c/_6))
(def kt_7  (c/mk c/K c/T c/_7))
(def kt_8  (c/mk c/K c/T c/_8))
(def kt_9  (c/mk c/K c/T c/_9))
(def kt_0  (c/mk c/K c/T c/_0))
(def kt_hy (c/mk c/K c/T c/_hy))
(def kt_eq (c/mk c/K c/T c/_eq))

(def kc_1  (c/mk c/K c/C c/_1))
(def kc_2  (c/mk c/K c/C c/_2))
(def kc_3  (c/mk c/K c/C c/_3))
(def kc_4  (c/mk c/K c/C c/_4))
(def kc_5  (c/mk c/K c/C c/_5))
(def kc_6  (c/mk c/K c/C c/_6))
(def kc_7  (c/mk c/K c/C c/_7))
(def kc_8  (c/mk c/K c/C c/_8))
(def kc_9  (c/mk c/K c/C c/_9))
(def kc_0  (c/mk c/K c/C c/_0))
(def kc_hy (c/mk c/K c/C c/_hy))
(def kc_eq (c/mk c/K c/C c/_eq))

(def kot_1  (c/mk c/K c/O c/T c/_1))
(def kot_2  (c/mk c/K c/O c/T c/_2))
(def kot_3  (c/mk c/K c/O c/T c/_3))
(def kot_4  (c/mk c/K c/O c/T c/_4))
(def kot_5  (c/mk c/K c/O c/T c/_5))
(def kot_6  (c/mk c/K c/O c/T c/_6))
(def kot_7  (c/mk c/K c/O c/T c/_7))
(def kot_8  (c/mk c/K c/O c/T c/_8))
(def kot_9  (c/mk c/K c/O c/T c/_9))
(def kot_0  (c/mk c/K c/O c/T c/_0))
(def kot_hy (c/mk c/K c/O c/T c/_hy))
(def kot_eq (c/mk c/K c/O c/T c/_eq))

(def koc_1  (c/mk c/K c/O c/C c/_1))
(def koc_2  (c/mk c/K c/O c/C c/_2))
(def koc_3  (c/mk c/K c/O c/C c/_3))
(def koc_4  (c/mk c/K c/O c/C c/_4))
(def koc_5  (c/mk c/K c/O c/C c/_5))
(def koc_6  (c/mk c/K c/O c/C c/_6))
(def koc_7  (c/mk c/K c/O c/C c/_7))
(def koc_8  (c/mk c/K c/O c/C c/_8))
(def koc_9  (c/mk c/K c/O c/C c/_9))
(def koc_0  (c/mk c/K c/O c/C c/_0))
(def koc_hy (c/mk c/K c/O c/C c/_hy))
(def koc_eq (c/mk c/K c/O c/C c/_eq))

(def ktc_1  (c/mk c/K c/T c/C c/_1))
(def ktc_2  (c/mk c/K c/T c/C c/_2))
(def ktc_3  (c/mk c/K c/T c/C c/_3))
(def ktc_4  (c/mk c/K c/T c/C c/_4))
(def ktc_5  (c/mk c/K c/T c/C c/_5))
(def ktc_6  (c/mk c/K c/T c/C c/_6))
(def ktc_7  (c/mk c/K c/T c/C c/_7))
(def ktc_8  (c/mk c/K c/T c/C c/_8))
(def ktc_9  (c/mk c/K c/T c/C c/_9))
(def ktc_0  (c/mk c/K c/T c/C c/_0))
(def ktc_hy (c/mk c/K c/T c/C c/_hy))
(def ktc_eq (c/mk c/K c/T c/C c/_eq))

(def kotc_1  (c/mk c/K c/O c/T c/C c/_1))
(def kotc_2  (c/mk c/K c/O c/T c/C c/_2))
(def kotc_3  (c/mk c/K c/O c/T c/C c/_3))
(def kotc_4  (c/mk c/K c/O c/T c/C c/_4))
(def kotc_5  (c/mk c/K c/O c/T c/C c/_5))
(def kotc_6  (c/mk c/K c/O c/T c/C c/_6))
(def kotc_7  (c/mk c/K c/O c/T c/C c/_7))
(def kotc_8  (c/mk c/K c/O c/T c/C c/_8))
(def kotc_9  (c/mk c/K c/O c/T c/C c/_9))
(def kotc_0  (c/mk c/K c/O c/T c/C c/_0))
(def kotc_hy (c/mk c/K c/O c/T c/C c/_hy))
(def kotc_eq (c/mk c/K c/O c/T c/C c/_eq))

(def ke_1  (c/mk c/K c/E c/_1))
(def ke_2  (c/mk c/K c/E c/_2))
(def ke_3  (c/mk c/K c/E c/_3))
(def ke_4  (c/mk c/K c/E c/_4))
(def ke_5  (c/mk c/K c/E c/_5))
(def ke_6  (c/mk c/K c/E c/_6))
(def ke_7  (c/mk c/K c/E c/_7))
(def ke_8  (c/mk c/K c/E c/_8))
(def ke_9  (c/mk c/K c/E c/_9))
(def ke_0  (c/mk c/K c/E c/_0))
(def ke_hy (c/mk c/K c/E c/_hy))
(def ke_eq (c/mk c/K c/E c/_eq))

(def kw_1  (c/mk c/K c/W c/_1))
(def kw_2  (c/mk c/K c/W c/_2))
(def kw_3  (c/mk c/K c/W c/_3))
(def kw_4  (c/mk c/K c/W c/_4))
(def kw_5  (c/mk c/K c/W c/_5))
(def kw_6  (c/mk c/K c/W c/_6))
(def kw_7  (c/mk c/K c/W c/_7))
(def kw_8  (c/mk c/K c/W c/_8))
(def kw_9  (c/mk c/K c/W c/_9))
(def kw_0  (c/mk c/K c/W c/_0))
(def kw_hy (c/mk c/K c/W c/_hy))
(def kw_eq (c/mk c/K c/W c/_eq))

(def kq_1  (c/mk c/K c/Q c/_1))
(def kq_2  (c/mk c/K c/Q c/_2))
(def kq_3  (c/mk c/K c/Q c/_3))
(def kq_4  (c/mk c/K c/Q c/_4))
(def kq_5  (c/mk c/K c/Q c/_5))
(def kq_6  (c/mk c/K c/Q c/_6))
(def kq_7  (c/mk c/K c/Q c/_7))
(def kq_8  (c/mk c/K c/Q c/_8))
(def kq_9  (c/mk c/K c/Q c/_9))
(def kq_0  (c/mk c/K c/Q c/_0))
(def kq_hy (c/mk c/K c/Q c/_hy))
(def kq_eq (c/mk c/K c/Q c/_eq))

(def kewq_1  (c/mk c/K c/E c/W c/Q c/_1))
(def kewq_2  (c/mk c/K c/E c/W c/Q c/_2))
(def kewq_3  (c/mk c/K c/E c/W c/Q c/_3))
(def kewq_4  (c/mk c/K c/E c/W c/Q c/_4))
(def kewq_5  (c/mk c/K c/E c/W c/Q c/_5))
(def kewq_6  (c/mk c/K c/E c/W c/Q c/_6))
(def kewq_7  (c/mk c/K c/E c/W c/Q c/_7))
(def kewq_8  (c/mk c/K c/E c/W c/Q c/_8))
(def kewq_9  (c/mk c/K c/E c/W c/Q c/_9))
(def kewq_0  (c/mk c/K c/E c/W c/Q c/_0))
(def kewq_hy (c/mk c/K c/E c/W c/Q c/_hy))
(def kewq_eq (c/mk c/K c/E c/W c/Q c/_eq))

(def ks_1  (c/mk c/K c/S c/_1))
(def ks_2  (c/mk c/K c/S c/_2))
(def ks_3  (c/mk c/K c/S c/_3))
(def ks_4  (c/mk c/K c/S c/_4))
(def ks_5  (c/mk c/K c/S c/_5))
(def ks_6  (c/mk c/K c/S c/_6))
(def ks_7  (c/mk c/K c/S c/_7))
(def ks_8  (c/mk c/K c/S c/_8))
(def ks_9  (c/mk c/K c/S c/_9))
(def ks_0  (c/mk c/K c/S c/_0))
(def ks_hy (c/mk c/K c/S c/_hy))
(def ks_eq (c/mk c/K c/S c/_eq))

(def kos_1  (c/mk c/K c/O c/S c/_1))
(def kos_2  (c/mk c/K c/O c/S c/_2))
(def kos_3  (c/mk c/K c/O c/S c/_3))
(def kos_4  (c/mk c/K c/O c/S c/_4))
(def kos_5  (c/mk c/K c/O c/S c/_5))
(def kos_6  (c/mk c/K c/O c/S c/_6))
(def kos_7  (c/mk c/K c/O c/S c/_7))
(def kos_8  (c/mk c/K c/O c/S c/_8))
(def kos_9  (c/mk c/K c/O c/S c/_9))
(def kos_0  (c/mk c/K c/O c/S c/_0))
(def kos_hy (c/mk c/K c/O c/S c/_hy))
(def kos_eq (c/mk c/K c/O c/S c/_eq))

(def kts_1  (c/mk c/K c/T c/S c/_1))
(def kts_2  (c/mk c/K c/T c/S c/_2))
(def kts_3  (c/mk c/K c/T c/S c/_3))
(def kts_4  (c/mk c/K c/T c/S c/_4))
(def kts_5  (c/mk c/K c/T c/S c/_5))
(def kts_6  (c/mk c/K c/T c/S c/_6))
(def kts_7  (c/mk c/K c/T c/S c/_7))
(def kts_8  (c/mk c/K c/T c/S c/_8))
(def kts_9  (c/mk c/K c/T c/S c/_9))
(def kts_0  (c/mk c/K c/T c/S c/_0))
(def kts_hy (c/mk c/K c/T c/S c/_hy))
(def kts_eq (c/mk c/K c/T c/S c/_eq))

(def kcs_1  (c/mk c/K c/C c/S c/_1))
(def kcs_2  (c/mk c/K c/C c/S c/_2))
(def kcs_3  (c/mk c/K c/C c/S c/_3))
(def kcs_4  (c/mk c/K c/C c/S c/_4))
(def kcs_5  (c/mk c/K c/C c/S c/_5))
(def kcs_6  (c/mk c/K c/C c/S c/_6))
(def kcs_7  (c/mk c/K c/C c/S c/_7))
(def kcs_8  (c/mk c/K c/C c/S c/_8))
(def kcs_9  (c/mk c/K c/C c/S c/_9))
(def kcs_0  (c/mk c/K c/C c/S c/_0))
(def kcs_hy (c/mk c/K c/C c/S c/_hy))
(def kcs_eq (c/mk c/K c/C c/S c/_eq))

(def kots_1  (c/mk c/K c/O c/T c/S c/_1))
(def kots_2  (c/mk c/K c/O c/T c/S c/_2))
(def kots_3  (c/mk c/K c/O c/T c/S c/_3))
(def kots_4  (c/mk c/K c/O c/T c/S c/_4))
(def kots_5  (c/mk c/K c/O c/T c/S c/_5))
(def kots_6  (c/mk c/K c/O c/T c/S c/_6))
(def kots_7  (c/mk c/K c/O c/T c/S c/_7))
(def kots_8  (c/mk c/K c/O c/T c/S c/_8))
(def kots_9  (c/mk c/K c/O c/T c/S c/_9))
(def kots_0  (c/mk c/K c/O c/T c/S c/_0))
(def kots_hy (c/mk c/K c/O c/T c/S c/_hy))
(def kots_eq (c/mk c/K c/O c/T c/S c/_eq))

(def kocs_1  (c/mk c/K c/O c/C c/S c/_1))
(def kocs_2  (c/mk c/K c/O c/C c/S c/_2))
(def kocs_3  (c/mk c/K c/O c/C c/S c/_3))
(def kocs_4  (c/mk c/K c/O c/C c/S c/_4))
(def kocs_5  (c/mk c/K c/O c/C c/S c/_5))
(def kocs_6  (c/mk c/K c/O c/C c/S c/_6))
(def kocs_7  (c/mk c/K c/O c/C c/S c/_7))
(def kocs_8  (c/mk c/K c/O c/C c/S c/_8))
(def kocs_9  (c/mk c/K c/O c/C c/S c/_9))
(def kocs_0  (c/mk c/K c/O c/C c/S c/_0))
(def kocs_hy (c/mk c/K c/O c/C c/S c/_hy))
(def kocs_eq (c/mk c/K c/O c/C c/S c/_eq))

(def ktcs_1  (c/mk c/K c/T c/C c/S c/_1))
(def ktcs_2  (c/mk c/K c/T c/C c/S c/_2))
(def ktcs_3  (c/mk c/K c/T c/C c/S c/_3))
(def ktcs_4  (c/mk c/K c/T c/C c/S c/_4))
(def ktcs_5  (c/mk c/K c/T c/C c/S c/_5))
(def ktcs_6  (c/mk c/K c/T c/C c/S c/_6))
(def ktcs_7  (c/mk c/K c/T c/C c/S c/_7))
(def ktcs_8  (c/mk c/K c/T c/C c/S c/_8))
(def ktcs_9  (c/mk c/K c/T c/C c/S c/_9))
(def ktcs_0  (c/mk c/K c/T c/C c/S c/_0))
(def ktcs_hy (c/mk c/K c/T c/C c/S c/_hy))
(def ktcs_eq (c/mk c/K c/T c/C c/S c/_eq))

(def kotcs_1  (c/mk c/K c/O c/T c/C c/R c/_1))
(def kotcs_2  (c/mk c/K c/O c/T c/C c/R c/_2))
(def kotcs_3  (c/mk c/K c/O c/T c/C c/R c/_3))
(def kotcs_4  (c/mk c/K c/O c/T c/C c/R c/_4))
(def kotcs_5  (c/mk c/K c/O c/T c/C c/R c/_5))
(def kotcs_6  (c/mk c/K c/O c/T c/C c/R c/_6))
(def kotcs_7  (c/mk c/K c/O c/T c/C c/R c/_7))
(def kotcs_8  (c/mk c/K c/O c/T c/C c/R c/_8))
(def kotcs_9  (c/mk c/K c/O c/T c/C c/R c/_9))
(def kotcs_0  (c/mk c/K c/O c/T c/C c/R c/_0))
(def kotcs_hy (c/mk c/K c/O c/T c/C c/R c/_hy))
(def kotcs_eq (c/mk c/K c/O c/T c/C c/R c/_eq))

(def ker_1  (c/mk c/K c/E c/R c/_1))
(def ker_2  (c/mk c/K c/E c/R c/_2))
(def ker_3  (c/mk c/K c/E c/R c/_3))
(def ker_4  (c/mk c/K c/E c/R c/_4))
(def ker_5  (c/mk c/K c/E c/R c/_5))
(def ker_6  (c/mk c/K c/E c/R c/_6))
(def ker_7  (c/mk c/K c/E c/R c/_7))
(def ker_8  (c/mk c/K c/E c/R c/_8))
(def ker_9  (c/mk c/K c/E c/R c/_9))
(def ker_0  (c/mk c/K c/E c/R c/_0))
(def ker_hy (c/mk c/K c/E c/R c/_hy))
(def ker_eq (c/mk c/K c/E c/R c/_eq))

(def kws_1  (c/mk c/K c/W c/S c/_1))
(def kws_2  (c/mk c/K c/W c/S c/_2))
(def kws_3  (c/mk c/K c/W c/S c/_3))
(def kws_4  (c/mk c/K c/W c/S c/_4))
(def kws_5  (c/mk c/K c/W c/S c/_5))
(def kws_6  (c/mk c/K c/W c/S c/_6))
(def kws_7  (c/mk c/K c/W c/S c/_7))
(def kws_8  (c/mk c/K c/W c/S c/_8))
(def kws_9  (c/mk c/K c/W c/S c/_9))
(def kws_0  (c/mk c/K c/W c/S c/_0))
(def kws_hy (c/mk c/K c/W c/S c/_hy))
(def kws_eq (c/mk c/K c/W c/S c/_eq))

(def kqr_1  (c/mk c/K c/Q c/R c/_1))
(def kqr_2  (c/mk c/K c/Q c/R c/_2))
(def kqr_3  (c/mk c/K c/Q c/R c/_3))
(def kqr_4  (c/mk c/K c/Q c/R c/_4))
(def kqr_5  (c/mk c/K c/Q c/R c/_5))
(def kqr_6  (c/mk c/K c/Q c/R c/_6))
(def kqr_7  (c/mk c/K c/Q c/R c/_7))
(def kqr_8  (c/mk c/K c/Q c/R c/_8))
(def kqr_9  (c/mk c/K c/Q c/R c/_9))
(def kqr_0  (c/mk c/K c/Q c/R c/_0))
(def kqr_hy (c/mk c/K c/Q c/R c/_hy))
(def kqr_eq (c/mk c/K c/Q c/R c/_eq))

(def kewqs_1  (c/mk c/K c/E c/W c/Q c/S c/_1))
(def kewqs_2  (c/mk c/K c/E c/W c/Q c/S c/_2))
(def kewqs_3  (c/mk c/K c/E c/W c/Q c/S c/_3))
(def kewqs_4  (c/mk c/K c/E c/W c/Q c/S c/_4))
(def kewqs_5  (c/mk c/K c/E c/W c/Q c/S c/_5))
(def kewqs_6  (c/mk c/K c/E c/W c/Q c/S c/_6))
(def kewqs_7  (c/mk c/K c/E c/W c/Q c/S c/_7))
(def kewqs_8  (c/mk c/K c/E c/W c/Q c/S c/_8))
(def kewqs_9  (c/mk c/K c/E c/W c/Q c/S c/_9))
(def kewqs_0  (c/mk c/K c/E c/W c/Q c/S c/_0))
(def kewqs_hy (c/mk c/K c/E c/W c/Q c/S c/_hy))
(def kewqs_eq (c/mk c/K c/E c/W c/Q c/S c/_eq))

(def kp_1  (c/mk c/P c/_1))
(def kp_2  (c/mk c/P c/_2))
(def kp_3  (c/mk c/P c/_3))
(def kp_4  (c/mk c/P c/_4))
(def kp_5  (c/mk c/P c/_5))
(def kp_6  (c/mk c/P c/_6))
(def kp_7  (c/mk c/P c/_7))
(def kp_8  (c/mk c/P c/_8))
(def kp_9  (c/mk c/P c/_9))
(def kp_0  (c/mk c/P c/_0))
(def kp_hy (c/mk c/P c/_hy))
(def kp_eq (c/mk c/P c/_eq))

(def kop_1  (c/mk c/K c/O c/P c/_1))
(def kop_2  (c/mk c/K c/O c/P c/_2))
(def kop_3  (c/mk c/K c/O c/P c/_3))
(def kop_4  (c/mk c/K c/O c/P c/_4))
(def kop_5  (c/mk c/K c/O c/P c/_5))
(def kop_6  (c/mk c/K c/O c/P c/_6))
(def kop_7  (c/mk c/K c/O c/P c/_7))
(def kop_8  (c/mk c/K c/O c/P c/_8))
(def kop_9  (c/mk c/K c/O c/P c/_9))
(def kop_0  (c/mk c/K c/O c/P c/_0))
(def kop_hy (c/mk c/K c/O c/P c/_hy))
(def kop_eq (c/mk c/K c/O c/P c/_eq))

(def ktp_1  (c/mk c/K c/T c/P c/_1))
(def ktp_2  (c/mk c/K c/T c/P c/_2))
(def ktp_3  (c/mk c/K c/T c/P c/_3))
(def ktp_4  (c/mk c/K c/T c/P c/_4))
(def ktp_5  (c/mk c/K c/T c/P c/_5))
(def ktp_6  (c/mk c/K c/T c/P c/_6))
(def ktp_7  (c/mk c/K c/T c/P c/_7))
(def ktp_8  (c/mk c/K c/T c/P c/_8))
(def ktp_9  (c/mk c/K c/T c/P c/_9))
(def ktp_0  (c/mk c/K c/T c/P c/_0))
(def ktp_hy (c/mk c/K c/T c/P c/_hy))
(def ktp_eq (c/mk c/K c/T c/P c/_eq))

(def kcp_1  (c/mk c/K c/C c/P c/_1))
(def kcp_2  (c/mk c/K c/C c/P c/_2))
(def kcp_3  (c/mk c/K c/C c/P c/_3))
(def kcp_4  (c/mk c/K c/C c/P c/_4))
(def kcp_5  (c/mk c/K c/C c/P c/_5))
(def kcp_6  (c/mk c/K c/C c/P c/_6))
(def kcp_7  (c/mk c/K c/C c/P c/_7))
(def kcp_8  (c/mk c/K c/C c/P c/_8))
(def kcp_9  (c/mk c/K c/C c/P c/_9))
(def kcp_0  (c/mk c/K c/C c/P c/_0))
(def kcp_hy (c/mk c/K c/C c/P c/_hy))
(def kcp_eq (c/mk c/K c/C c/P c/_eq))

(def kotp_1  (c/mk c/K c/O c/T c/P c/_1))
(def kotp_2  (c/mk c/K c/O c/T c/P c/_2))
(def kotp_3  (c/mk c/K c/O c/T c/P c/_3))
(def kotp_4  (c/mk c/K c/O c/T c/P c/_4))
(def kotp_5  (c/mk c/K c/O c/T c/P c/_5))
(def kotp_6  (c/mk c/K c/O c/T c/P c/_6))
(def kotp_7  (c/mk c/K c/O c/T c/P c/_7))
(def kotp_8  (c/mk c/K c/O c/T c/P c/_8))
(def kotp_9  (c/mk c/K c/O c/T c/P c/_9))
(def kotp_0  (c/mk c/K c/O c/T c/P c/_0))
(def kotp_hy (c/mk c/K c/O c/T c/P c/_hy))
(def kotp_eq (c/mk c/K c/O c/T c/P c/_eq))

(def kocp_1  (c/mk c/K c/O c/C c/P c/_1))
(def kocp_2  (c/mk c/K c/O c/C c/P c/_2))
(def kocp_3  (c/mk c/K c/O c/C c/P c/_3))
(def kocp_4  (c/mk c/K c/O c/C c/P c/_4))
(def kocp_5  (c/mk c/K c/O c/C c/P c/_5))
(def kocp_6  (c/mk c/K c/O c/C c/P c/_6))
(def kocp_7  (c/mk c/K c/O c/C c/P c/_7))
(def kocp_8  (c/mk c/K c/O c/C c/P c/_8))
(def kocp_9  (c/mk c/K c/O c/C c/P c/_9))
(def kocp_0  (c/mk c/K c/O c/C c/P c/_0))
(def kocp_hy (c/mk c/K c/O c/C c/P c/_hy))
(def kocp_eq (c/mk c/K c/O c/C c/P c/_eq))

(def ktcp_1  (c/mk c/K c/T c/C c/P c/_1))
(def ktcp_2  (c/mk c/K c/T c/C c/P c/_2))
(def ktcp_3  (c/mk c/K c/T c/C c/P c/_3))
(def ktcp_4  (c/mk c/K c/T c/C c/P c/_4))
(def ktcp_5  (c/mk c/K c/T c/C c/P c/_5))
(def ktcp_6  (c/mk c/K c/T c/C c/P c/_6))
(def ktcp_7  (c/mk c/K c/T c/C c/P c/_7))
(def ktcp_8  (c/mk c/K c/T c/C c/P c/_8))
(def ktcp_9  (c/mk c/K c/T c/C c/P c/_9))
(def ktcp_0  (c/mk c/K c/T c/C c/P c/_0))
(def ktcp_hy (c/mk c/K c/T c/C c/P c/_hy))
(def ktcp_eq (c/mk c/K c/T c/C c/P c/_eq))

(def kotcp_1  (c/mk c/K c/O c/T c/C c/P c/_1))
(def kotcp_2  (c/mk c/K c/O c/T c/C c/P c/_2))
(def kotcp_3  (c/mk c/K c/O c/T c/C c/P c/_3))
(def kotcp_4  (c/mk c/K c/O c/T c/C c/P c/_4))
(def kotcp_5  (c/mk c/K c/O c/T c/C c/P c/_5))
(def kotcp_6  (c/mk c/K c/O c/T c/C c/P c/_6))
(def kotcp_7  (c/mk c/K c/O c/T c/C c/P c/_7))
(def kotcp_8  (c/mk c/K c/O c/T c/C c/P c/_8))
(def kotcp_9  (c/mk c/K c/O c/T c/C c/P c/_9))
(def kotcp_0  (c/mk c/K c/O c/T c/C c/P c/_0))
(def kotcp_hy (c/mk c/K c/O c/T c/C c/P c/_hy))
(def kotcp_eq (c/mk c/K c/O c/T c/C c/P c/_eq))

(def kep_1  (c/mk c/K c/E c/P c/_1))
(def kep_2  (c/mk c/K c/E c/P c/_2))
(def kep_3  (c/mk c/K c/E c/P c/_3))
(def kep_4  (c/mk c/K c/E c/P c/_4))
(def kep_5  (c/mk c/K c/E c/P c/_5))
(def kep_6  (c/mk c/K c/E c/P c/_6))
(def kep_7  (c/mk c/K c/E c/P c/_7))
(def kep_8  (c/mk c/K c/E c/P c/_8))
(def kep_9  (c/mk c/K c/E c/P c/_9))
(def kep_0  (c/mk c/K c/E c/P c/_0))
(def kep_hy (c/mk c/K c/E c/P c/_hy))
(def kep_eq (c/mk c/K c/E c/P c/_eq))

(def kwp_1  (c/mk c/K c/W c/P c/_1))
(def kwp_2  (c/mk c/K c/W c/P c/_2))
(def kwp_3  (c/mk c/K c/W c/P c/_3))
(def kwp_4  (c/mk c/K c/W c/P c/_4))
(def kwp_5  (c/mk c/K c/W c/P c/_5))
(def kwp_6  (c/mk c/K c/W c/P c/_6))
(def kwp_7  (c/mk c/K c/W c/P c/_7))
(def kwp_8  (c/mk c/K c/W c/P c/_8))
(def kwp_9  (c/mk c/K c/W c/P c/_9))
(def kwp_0  (c/mk c/K c/W c/P c/_0))
(def kwp_hy (c/mk c/K c/W c/P c/_hy))
(def kwp_eq (c/mk c/K c/W c/P c/_eq))

(def kqp_1  (c/mk c/K c/Q c/P c/_1))
(def kqp_2  (c/mk c/K c/Q c/P c/_2))
(def kqp_3  (c/mk c/K c/Q c/P c/_3))
(def kqp_4  (c/mk c/K c/Q c/P c/_4))
(def kqp_5  (c/mk c/K c/Q c/P c/_5))
(def kqp_6  (c/mk c/K c/Q c/P c/_6))
(def kqp_7  (c/mk c/K c/Q c/P c/_7))
(def kqp_8  (c/mk c/K c/Q c/P c/_8))
(def kqp_9  (c/mk c/K c/Q c/P c/_9))
(def kqp_0  (c/mk c/K c/Q c/P c/_0))
(def kqp_hy (c/mk c/K c/Q c/P c/_hy))
(def kqp_eq (c/mk c/K c/Q c/P c/_eq))

(def kewqp_1  (c/mk c/K c/E c/W c/Q c/P c/_1))
(def kewqp_2  (c/mk c/K c/E c/W c/Q c/P c/_2))
(def kewqp_3  (c/mk c/K c/E c/W c/Q c/P c/_3))
(def kewqp_4  (c/mk c/K c/E c/W c/Q c/P c/_4))
(def kewqp_5  (c/mk c/K c/E c/W c/Q c/P c/_5))
(def kewqp_6  (c/mk c/K c/E c/W c/Q c/P c/_6))
(def kewqp_7  (c/mk c/K c/E c/W c/Q c/P c/_7))
(def kewqp_8  (c/mk c/K c/E c/W c/Q c/P c/_8))
(def kewqp_9  (c/mk c/K c/E c/W c/Q c/P c/_9))
(def kewqp_0  (c/mk c/K c/E c/W c/Q c/P c/_0))
(def kewqp_hy (c/mk c/K c/E c/W c/Q c/P c/_hy))
(def kewqp_eq (c/mk c/K c/E c/W c/Q c/P c/_eq))

(def ksp_1  (c/mk c/K c/S c/P c/_1))
(def ksp_2  (c/mk c/K c/S c/P c/_2))
(def ksp_3  (c/mk c/K c/S c/P c/_3))
(def ksp_4  (c/mk c/K c/S c/P c/_4))
(def ksp_5  (c/mk c/K c/S c/P c/_5))
(def ksp_6  (c/mk c/K c/S c/P c/_6))
(def ksp_7  (c/mk c/K c/S c/P c/_7))
(def ksp_8  (c/mk c/K c/S c/P c/_8))
(def ksp_9  (c/mk c/K c/S c/P c/_9))
(def ksp_0  (c/mk c/K c/S c/P c/_0))
(def ksp_hy (c/mk c/K c/S c/P c/_hy))
(def ksp_eq (c/mk c/K c/S c/P c/_eq))

(def kosp_1  (c/mk c/K c/O c/S c/P c/_1))
(def kosp_2  (c/mk c/K c/O c/S c/P c/_2))
(def kosp_3  (c/mk c/K c/O c/S c/P c/_3))
(def kosp_4  (c/mk c/K c/O c/S c/P c/_4))
(def kosp_5  (c/mk c/K c/O c/S c/P c/_5))
(def kosp_6  (c/mk c/K c/O c/S c/P c/_6))
(def kosp_7  (c/mk c/K c/O c/S c/P c/_7))
(def kosp_8  (c/mk c/K c/O c/S c/P c/_8))
(def kosp_9  (c/mk c/K c/O c/S c/P c/_9))
(def kosp_0  (c/mk c/K c/O c/S c/P c/_0))
(def kosp_hy (c/mk c/K c/O c/S c/P c/_hy))
(def kosp_eq (c/mk c/K c/O c/S c/P c/_eq))

(def ktsp_1  (c/mk c/K c/T c/S c/P c/_1))
(def ktsp_2  (c/mk c/K c/T c/S c/P c/_2))
(def ktsp_3  (c/mk c/K c/T c/S c/P c/_3))
(def ktsp_4  (c/mk c/K c/T c/S c/P c/_4))
(def ktsp_5  (c/mk c/K c/T c/S c/P c/_5))
(def ktsp_6  (c/mk c/K c/T c/S c/P c/_6))
(def ktsp_7  (c/mk c/K c/T c/S c/P c/_7))
(def ktsp_8  (c/mk c/K c/T c/S c/P c/_8))
(def ktsp_9  (c/mk c/K c/T c/S c/P c/_9))
(def ktsp_0  (c/mk c/K c/T c/S c/P c/_0))
(def ktsp_hy (c/mk c/K c/T c/S c/P c/_hy))
(def ktsp_eq (c/mk c/K c/T c/S c/P c/_eq))

(def kcsp_1  (c/mk c/K c/C c/S c/P c/_1))
(def kcsp_2  (c/mk c/K c/C c/S c/P c/_2))
(def kcsp_3  (c/mk c/K c/C c/S c/P c/_3))
(def kcsp_4  (c/mk c/K c/C c/S c/P c/_4))
(def kcsp_5  (c/mk c/K c/C c/S c/P c/_5))
(def kcsp_6  (c/mk c/K c/C c/S c/P c/_6))
(def kcsp_7  (c/mk c/K c/C c/S c/P c/_7))
(def kcsp_8  (c/mk c/K c/C c/S c/P c/_8))
(def kcsp_9  (c/mk c/K c/C c/S c/P c/_9))
(def kcsp_0  (c/mk c/K c/C c/S c/P c/_0))
(def kcsp_hy (c/mk c/K c/C c/S c/P c/_hy))
(def kcsp_eq (c/mk c/K c/C c/S c/P c/_eq))

(def kotsp_1  (c/mk c/K c/O c/T c/S c/P c/_1))
(def kotsp_2  (c/mk c/K c/O c/T c/S c/P c/_2))
(def kotsp_3  (c/mk c/K c/O c/T c/S c/P c/_3))
(def kotsp_4  (c/mk c/K c/O c/T c/S c/P c/_4))
(def kotsp_5  (c/mk c/K c/O c/T c/S c/P c/_5))
(def kotsp_6  (c/mk c/K c/O c/T c/S c/P c/_6))
(def kotsp_7  (c/mk c/K c/O c/T c/S c/P c/_7))
(def kotsp_8  (c/mk c/K c/O c/T c/S c/P c/_8))
(def kotsp_9  (c/mk c/K c/O c/T c/S c/P c/_9))
(def kotsp_0  (c/mk c/K c/O c/T c/S c/P c/_0))
(def kotsp_hy (c/mk c/K c/O c/T c/S c/P c/_hy))
(def kotsp_eq (c/mk c/K c/O c/T c/S c/P c/_eq))

(def kocsp_1  (c/mk c/K c/O c/C c/S c/P c/_1))
(def kocsp_2  (c/mk c/K c/O c/C c/S c/P c/_2))
(def kocsp_3  (c/mk c/K c/O c/C c/S c/P c/_3))
(def kocsp_4  (c/mk c/K c/O c/C c/S c/P c/_4))
(def kocsp_5  (c/mk c/K c/O c/C c/S c/P c/_5))
(def kocsp_6  (c/mk c/K c/O c/C c/S c/P c/_6))
(def kocsp_7  (c/mk c/K c/O c/C c/S c/P c/_7))
(def kocsp_8  (c/mk c/K c/O c/C c/S c/P c/_8))
(def kocsp_9  (c/mk c/K c/O c/C c/S c/P c/_9))
(def kocsp_0  (c/mk c/K c/O c/C c/S c/P c/_0))
(def kocsp_hy (c/mk c/K c/O c/C c/S c/P c/_hy))
(def kocsp_eq (c/mk c/K c/O c/C c/S c/P c/_eq))

(def ktcsp_1  (c/mk c/K c/T c/C c/S c/P c/_1))
(def ktcsp_2  (c/mk c/K c/T c/C c/S c/P c/_2))
(def ktcsp_3  (c/mk c/K c/T c/C c/S c/P c/_3))
(def ktcsp_4  (c/mk c/K c/T c/C c/S c/P c/_4))
(def ktcsp_5  (c/mk c/K c/T c/C c/S c/P c/_5))
(def ktcsp_6  (c/mk c/K c/T c/C c/S c/P c/_6))
(def ktcsp_7  (c/mk c/K c/T c/C c/S c/P c/_7))
(def ktcsp_8  (c/mk c/K c/T c/C c/S c/P c/_8))
(def ktcsp_9  (c/mk c/K c/T c/C c/S c/P c/_9))
(def ktcsp_0  (c/mk c/K c/T c/C c/S c/P c/_0))
(def ktcsp_hy (c/mk c/K c/T c/C c/S c/P c/_hy))
(def ktcsp_eq (c/mk c/K c/T c/C c/S c/P c/_eq))

(def kotcsp_1  (c/mk c/K c/O c/T c/C c/R c/P c/_1))
(def kotcsp_2  (c/mk c/K c/O c/T c/C c/R c/P c/_2))
(def kotcsp_3  (c/mk c/K c/O c/T c/C c/R c/P c/_3))
(def kotcsp_4  (c/mk c/K c/O c/T c/C c/R c/P c/_4))
(def kotcsp_5  (c/mk c/K c/O c/T c/C c/R c/P c/_5))
(def kotcsp_6  (c/mk c/K c/O c/T c/C c/R c/P c/_6))
(def kotcsp_7  (c/mk c/K c/O c/T c/C c/R c/P c/_7))
(def kotcsp_8  (c/mk c/K c/O c/T c/C c/R c/P c/_8))
(def kotcsp_9  (c/mk c/K c/O c/T c/C c/R c/P c/_9))
(def kotcsp_0  (c/mk c/K c/O c/T c/C c/R c/P c/_0))
(def kotcsp_hy (c/mk c/K c/O c/T c/C c/R c/P c/_hy))
(def kotcsp_eq (c/mk c/K c/O c/T c/C c/R c/P c/_eq))

(def kerp_1  (c/mk c/K c/E c/R c/P c/_1))
(def kerp_2  (c/mk c/K c/E c/R c/P c/_2))
(def kerp_3  (c/mk c/K c/E c/R c/P c/_3))
(def kerp_4  (c/mk c/K c/E c/R c/P c/_4))
(def kerp_5  (c/mk c/K c/E c/R c/P c/_5))
(def kerp_6  (c/mk c/K c/E c/R c/P c/_6))
(def kerp_7  (c/mk c/K c/E c/R c/P c/_7))
(def kerp_8  (c/mk c/K c/E c/R c/P c/_8))
(def kerp_9  (c/mk c/K c/E c/R c/P c/_9))
(def kerp_0  (c/mk c/K c/E c/R c/P c/_0))
(def kerp_hy (c/mk c/K c/E c/R c/P c/_hy))
(def kerp_eq (c/mk c/K c/E c/R c/P c/_eq))

(def kwsp_1  (c/mk c/K c/W c/S c/P c/_1))
(def kwsp_2  (c/mk c/K c/W c/S c/P c/_2))
(def kwsp_3  (c/mk c/K c/W c/S c/P c/_3))
(def kwsp_4  (c/mk c/K c/W c/S c/P c/_4))
(def kwsp_5  (c/mk c/K c/W c/S c/P c/_5))
(def kwsp_6  (c/mk c/K c/W c/S c/P c/_6))
(def kwsp_7  (c/mk c/K c/W c/S c/P c/_7))
(def kwsp_8  (c/mk c/K c/W c/S c/P c/_8))
(def kwsp_9  (c/mk c/K c/W c/S c/P c/_9))
(def kwsp_0  (c/mk c/K c/W c/S c/P c/_0))
(def kwsp_hy (c/mk c/K c/W c/S c/P c/_hy))
(def kwsp_eq (c/mk c/K c/W c/S c/P c/_eq))

(def kqrp_1  (c/mk c/K c/Q c/R c/P c/_1))
(def kqrp_2  (c/mk c/K c/Q c/R c/P c/_2))
(def kqrp_3  (c/mk c/K c/Q c/R c/P c/_3))
(def kqrp_4  (c/mk c/K c/Q c/R c/P c/_4))
(def kqrp_5  (c/mk c/K c/Q c/R c/P c/_5))
(def kqrp_6  (c/mk c/K c/Q c/R c/P c/_6))
(def kqrp_7  (c/mk c/K c/Q c/R c/P c/_7))
(def kqrp_8  (c/mk c/K c/Q c/R c/P c/_8))
(def kqrp_9  (c/mk c/K c/Q c/R c/P c/_9))
(def kqrp_0  (c/mk c/K c/Q c/R c/P c/_0))
(def kqrp_hy (c/mk c/K c/Q c/R c/P c/_hy))
(def kqrp_eq (c/mk c/K c/Q c/R c/P c/_eq))

(def kewqsp_1  (c/mk c/K c/E c/W c/Q c/S c/P c/_1))
(def kewqsp_2  (c/mk c/K c/E c/W c/Q c/S c/P c/_2))
(def kewqsp_3  (c/mk c/K c/E c/W c/Q c/S c/P c/_3))
(def kewqsp_4  (c/mk c/K c/E c/W c/Q c/S c/P c/_4))
(def kewqsp_5  (c/mk c/K c/E c/W c/Q c/S c/P c/_5))
(def kewqsp_6  (c/mk c/K c/E c/W c/Q c/S c/P c/_6))
(def kewqsp_7  (c/mk c/K c/E c/W c/Q c/S c/P c/_7))
(def kewqsp_8  (c/mk c/K c/E c/W c/Q c/S c/P c/_8))
(def kewqsp_9  (c/mk c/K c/E c/W c/Q c/S c/P c/_9))
(def kewqsp_0  (c/mk c/K c/E c/W c/Q c/S c/P c/_0))
(def kewqsp_hy (c/mk c/K c/E c/W c/Q c/S c/P c/_hy))
(def kewqsp_eq (c/mk c/K c/E c/W c/Q c/S c/P c/_eq))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
