;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; technical
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(ns config.technical
(:require
            [config.config :as c]))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; technical glyphs
(def k_ob   (c/mk c/_ob))
(def k_cb   (c/mk c/_cb))
(def k_sc   (c/mk c/_sc))
(def k_qu   (c/mk c/_qu))
(def k_bl   (c/mk c/_bl))
(def k_cm   (c/mk c/_cm))
(def k_pe   (c/mk c/_pe))
(def k_sl   (c/mk c/_sl))

(def ko_ob  (c/mk c/K c/O c/_ob))
(def ko_cb  (c/mk c/K c/O c/_cb))
(def ko_sc  (c/mk c/K c/O c/_sc))
(def ko_qu  (c/mk c/K c/O c/_qu))
(def ko_bl  (c/mk c/K c/O c/_bl))
(def ko_cm  (c/mk c/K c/O c/_cm))
(def ko_pe  (c/mk c/K c/O c/_pe))
(def ko_sl  (c/mk c/K c/O c/_sl))

(def kt_ob  (c/mk c/K c/T c/_ob))
(def kt_cb  (c/mk c/K c/T c/_cb))
(def kt_sc  (c/mk c/K c/T c/_sc))
(def kt_qu  (c/mk c/K c/T c/_qu))
(def kt_bl  (c/mk c/K c/T c/_bl))
(def kt_cm  (c/mk c/K c/T c/_cm))
(def kt_pe  (c/mk c/K c/T c/_pe))
(def kt_sl  (c/mk c/K c/T c/_sl))

(def kc_ob  (c/mk c/K c/C c/_ob))
(def kc_cb  (c/mk c/K c/C c/_cb))
(def kc_sc  (c/mk c/K c/C c/_sc))
(def kc_qu  (c/mk c/K c/C c/_qu))
(def kc_bl  (c/mk c/K c/C c/_bl))
(def kc_cm  (c/mk c/K c/C c/_cm))
(def kc_pe  (c/mk c/K c/C c/_pe))
(def kc_sl  (c/mk c/K c/C c/_sl))

(def kot_ob (c/mk c/K c/O c/T c/_ob))
(def kot_cb (c/mk c/K c/O c/T c/_cb))
(def kot_sc (c/mk c/K c/O c/T c/_sc))
(def kot_qu (c/mk c/K c/O c/T c/_qu))
(def kot_bl (c/mk c/K c/O c/T c/_bl))
(def kot_cm (c/mk c/K c/O c/T c/_cm))
(def kot_pe (c/mk c/K c/O c/T c/_pe))
(def kot_sl (c/mk c/K c/O c/T c/_sl))

(def koc_ob (c/mk c/K c/O c/C c/_ob))
(def koc_cb (c/mk c/K c/O c/C c/_cb))
(def koc_sc (c/mk c/K c/O c/C c/_sc))
(def koc_qu (c/mk c/K c/O c/C c/_qu))
(def koc_bl (c/mk c/K c/O c/C c/_bl))
(def koc_cm (c/mk c/K c/O c/C c/_cm))
(def koc_pe (c/mk c/K c/O c/C c/_pe))
(def koc_sl (c/mk c/K c/O c/C c/_sl))

(def ktc_ob (c/mk c/K c/T c/C c/_ob))
(def ktc_cb (c/mk c/K c/T c/C c/_cb))
(def ktc_sc (c/mk c/K c/T c/C c/_sc))
(def ktc_qu (c/mk c/K c/T c/C c/_qu))
(def ktc_bl (c/mk c/K c/T c/C c/_bl))
(def ktc_cm (c/mk c/K c/T c/C c/_cm))
(def ktc_pe (c/mk c/K c/T c/C c/_pe))
(def ktc_sl (c/mk c/K c/T c/C c/_sl))

(def kotc_ob (c/mk c/K c/O c/T c/C c/_ob))
(def kotc_cb (c/mk c/K c/O c/T c/C c/_cb))
(def kotc_sc (c/mk c/K c/O c/T c/C c/_sc))
(def kotc_qu (c/mk c/K c/O c/T c/C c/_qu))
(def kotc_bl (c/mk c/K c/O c/T c/C c/_bl))
(def kotc_cm (c/mk c/K c/O c/T c/C c/_cm))
(def kotc_pe (c/mk c/K c/O c/T c/C c/_pe))
(def kotc_sl (c/mk c/K c/O c/T c/C c/_sl))

(def ke_ob  (c/mk c/K c/E c/_ob))
(def ke_cb  (c/mk c/K c/E c/_cb))
(def ke_sc  (c/mk c/K c/E c/_sc))
(def ke_qu  (c/mk c/K c/E c/_qu))
(def ke_bl  (c/mk c/K c/E c/_bl))
(def ke_cm  (c/mk c/K c/E c/_cm))
(def ke_pe  (c/mk c/K c/E c/_pe))
(def ke_sl  (c/mk c/K c/E c/_sl))

(def kw_ob  (c/mk c/K c/W c/_ob))
(def kw_cb  (c/mk c/K c/W c/_cb))
(def kw_sc  (c/mk c/K c/W c/_sc))
(def kw_qu  (c/mk c/K c/W c/_qu))
(def kw_bl  (c/mk c/K c/W c/_bl))
(def kw_cm  (c/mk c/K c/W c/_cm))
(def kw_pe  (c/mk c/K c/W c/_pe))
(def kw_sl  (c/mk c/K c/W c/_sl))

(def kq_ob  (c/mk c/K c/Q c/_ob))
(def kq_cb  (c/mk c/K c/Q c/_cb))
(def kq_sc  (c/mk c/K c/Q c/_sc))
(def kq_qu  (c/mk c/K c/Q c/_qu))
(def kq_bl  (c/mk c/K c/Q c/_bl))
(def kq_cm  (c/mk c/K c/Q c/_cm))
(def kq_pe  (c/mk c/K c/Q c/_pe))
(def kq_sl  (c/mk c/K c/Q c/_sl))

(def kewq_ob  (c/mk c/K c/E c/W c/Q c/_ob))
(def kewq_cb  (c/mk c/K c/E c/W c/Q c/_cb))
(def kewq_sc  (c/mk c/K c/E c/W c/Q c/_sc))
(def kewq_qu  (c/mk c/K c/E c/W c/Q c/_qu))
(def kewq_bl  (c/mk c/K c/E c/W c/Q c/_bl))
(def kewq_cm  (c/mk c/K c/E c/W c/Q c/_cm))
(def kewq_pe  (c/mk c/K c/E c/W c/Q c/_pe))
(def kewq_sl  (c/mk c/K c/E c/W c/Q c/_sl))

(def ks_ob   (c/mk c/K c/S c/_ob))
(def ks_cb   (c/mk c/K c/S c/_cb))
(def ks_sc   (c/mk c/K c/S c/_sc))
(def ks_qu   (c/mk c/K c/S c/_qu))
(def ks_bl   (c/mk c/K c/S c/_bl))
(def ks_cm   (c/mk c/K c/S c/_cm))
(def ks_pe   (c/mk c/K c/S c/_pe))
(def ks_sl   (c/mk c/K c/S c/_sl))

(def kos_ob  (c/mk c/K c/O c/S c/_ob))
(def kos_cb  (c/mk c/K c/O c/S c/_cb))
(def kos_sc  (c/mk c/K c/O c/S c/_sc))
(def kos_qu  (c/mk c/K c/O c/S c/_qu))
(def kos_bl  (c/mk c/K c/O c/S c/_bl))
(def kos_cm  (c/mk c/K c/O c/S c/_cm))
(def kos_pe  (c/mk c/K c/O c/S c/_pe))
(def kos_sl  (c/mk c/K c/O c/S c/_sl))

(def kts_ob  (c/mk c/K c/T c/S c/_ob))
(def kts_cb  (c/mk c/K c/T c/S c/_cb))
(def kts_sc  (c/mk c/K c/T c/S c/_sc))
(def kts_qu  (c/mk c/K c/T c/S c/_qu))
(def kts_bl  (c/mk c/K c/T c/S c/_bl))
(def kts_cm  (c/mk c/K c/T c/S c/_cm))
(def kts_pe  (c/mk c/K c/T c/S c/_pe))
(def kts_sl  (c/mk c/K c/T c/S c/_sl))

(def kcs_ob  (c/mk c/K c/C c/S c/_ob))
(def kcs_cb  (c/mk c/K c/C c/S c/_cb))
(def kcs_sc  (c/mk c/K c/C c/S c/_sc))
(def kcs_qu  (c/mk c/K c/C c/S c/_qu))
(def kcs_bl  (c/mk c/K c/C c/S c/_bl))
(def kcs_cm  (c/mk c/K c/C c/S c/_cm))
(def kcs_pe  (c/mk c/K c/C c/S c/_pe))
(def kcs_sl  (c/mk c/K c/C c/S c/_sl))

(def kots_ob (c/mk c/K c/O c/T c/S c/_ob))
(def kots_cb (c/mk c/K c/O c/T c/S c/_cb))
(def kots_sc (c/mk c/K c/O c/T c/S c/_sc))
(def kots_qu (c/mk c/K c/O c/T c/S c/_qu))
(def kots_bl (c/mk c/K c/O c/T c/S c/_bl))
(def kots_cm (c/mk c/K c/O c/T c/S c/_cm))
(def kots_pe (c/mk c/K c/O c/T c/S c/_pe))
(def kots_sl (c/mk c/K c/O c/T c/S c/_sl))

(def kocs_ob (c/mk c/K c/O c/C c/S c/_ob))
(def kocs_cb (c/mk c/K c/O c/C c/S c/_cb))
(def kocs_sc (c/mk c/K c/O c/C c/S c/_sc))
(def kocs_qu (c/mk c/K c/O c/C c/S c/_qu))
(def kocs_bl (c/mk c/K c/O c/C c/S c/_bl))
(def kocs_cm (c/mk c/K c/O c/C c/S c/_cm))
(def kocs_pe (c/mk c/K c/O c/C c/S c/_pe))
(def kocs_sl (c/mk c/K c/O c/C c/S c/_sl))

(def ktcs_ob (c/mk c/K c/T c/C c/S c/_ob))
(def ktcs_cb (c/mk c/K c/T c/C c/S c/_cb))
(def ktcs_sc (c/mk c/K c/T c/C c/S c/_sc))
(def ktcs_qu (c/mk c/K c/T c/C c/S c/_qu))
(def ktcs_bl (c/mk c/K c/T c/C c/S c/_bl))
(def ktcs_cm (c/mk c/K c/T c/C c/S c/_cm))
(def ktcs_pe (c/mk c/K c/T c/C c/S c/_pe))
(def ktcs_sl (c/mk c/K c/T c/C c/S c/_sl))

(def kotcs_ob (c/mk c/K c/O c/T c/C c/R c/_ob))
(def kotcs_cb (c/mk c/K c/O c/T c/C c/R c/_cb))
(def kotcs_sc (c/mk c/K c/O c/T c/C c/R c/_sc))
(def kotcs_qu (c/mk c/K c/O c/T c/C c/R c/_qu))
(def kotcs_bl (c/mk c/K c/O c/T c/C c/R c/_bl))
(def kotcs_cm (c/mk c/K c/O c/T c/C c/R c/_cm))
(def kotcs_pe (c/mk c/K c/O c/T c/C c/R c/_pe))
(def kotcs_sl (c/mk c/K c/O c/T c/C c/R c/_sl))

(def ker_ob  (c/mk c/K c/E c/R c/_ob))
(def ker_cb  (c/mk c/K c/E c/R c/_cb))
(def ker_sc  (c/mk c/K c/E c/R c/_sc))
(def ker_qu  (c/mk c/K c/E c/R c/_qu))
(def ker_bl  (c/mk c/K c/E c/R c/_bl))
(def ker_cm  (c/mk c/K c/E c/R c/_cm))
(def ker_pe  (c/mk c/K c/E c/R c/_pe))
(def ker_sl  (c/mk c/K c/E c/R c/_sl))

(def kws_ob  (c/mk c/K c/W c/S c/_ob))
(def kws_cb  (c/mk c/K c/W c/S c/_cb))
(def kws_sc  (c/mk c/K c/W c/S c/_sc))
(def kws_qu  (c/mk c/K c/W c/S c/_qu))
(def kws_bl  (c/mk c/K c/W c/S c/_bl))
(def kws_cm  (c/mk c/K c/W c/S c/_cm))
(def kws_pe  (c/mk c/K c/W c/S c/_pe))
(def kws_sl  (c/mk c/K c/W c/S c/_sl))

(def kqr_ob  (c/mk c/K c/Q c/R c/_ob))
(def kqr_cb  (c/mk c/K c/Q c/R c/_cb))
(def kqr_sc  (c/mk c/K c/Q c/R c/_sc))
(def kqr_qu  (c/mk c/K c/Q c/R c/_qu))
(def kqr_bl  (c/mk c/K c/Q c/R c/_bl))
(def kqr_cm  (c/mk c/K c/Q c/R c/_cm))
(def kqr_pe  (c/mk c/K c/Q c/R c/_pe))
(def kqr_sl  (c/mk c/K c/Q c/R c/_sl))

(def kewqs_ob  (c/mk c/K c/E c/W c/Q c/S c/_ob))
(def kewqs_cb  (c/mk c/K c/E c/W c/Q c/S c/_cb))
(def kewqs_sc  (c/mk c/K c/E c/W c/Q c/S c/_sc))
(def kewqs_qu  (c/mk c/K c/E c/W c/Q c/S c/_qu))
(def kewqs_bl  (c/mk c/K c/E c/W c/Q c/S c/_bl))
(def kewqs_cm  (c/mk c/K c/E c/W c/Q c/S c/_cm))
(def kewqs_pe  (c/mk c/K c/E c/W c/Q c/S c/_pe))
(def kewqs_sl  (c/mk c/K c/E c/W c/Q c/S c/_sl))

(def kp_ob   (c/mk c/P c/_ob))
(def kp_cb   (c/mk c/P c/_cb))
(def kp_sc   (c/mk c/P c/_sc))
(def kp_qu   (c/mk c/P c/_qu))
(def kp_bl   (c/mk c/P c/_bl))
(def kp_cm   (c/mk c/P c/_cm))
(def kp_pe   (c/mk c/P c/_pe))
(def kp_sl   (c/mk c/P c/_sl))

(def kop_ob  (c/mk c/K c/O c/P c/_ob))
(def kop_cb  (c/mk c/K c/O c/P c/_cb))
(def kop_sc  (c/mk c/K c/O c/P c/_sc))
(def kop_qu  (c/mk c/K c/O c/P c/_qu))
(def kop_bl  (c/mk c/K c/O c/P c/_bl))
(def kop_cm  (c/mk c/K c/O c/P c/_cm))
(def kop_pe  (c/mk c/K c/O c/P c/_pe))
(def kop_sl  (c/mk c/K c/O c/P c/_sl))

(def ktp_ob  (c/mk c/K c/T c/P c/_ob))
(def ktp_cb  (c/mk c/K c/T c/P c/_cb))
(def ktp_sc  (c/mk c/K c/T c/P c/_sc))
(def ktp_qu  (c/mk c/K c/T c/P c/_qu))
(def ktp_bl  (c/mk c/K c/T c/P c/_bl))
(def ktp_cm  (c/mk c/K c/T c/P c/_cm))
(def ktp_pe  (c/mk c/K c/T c/P c/_pe))
(def ktp_sl  (c/mk c/K c/T c/P c/_sl))

(def kcp_ob  (c/mk c/K c/C c/P c/_ob))
(def kcp_cb  (c/mk c/K c/C c/P c/_cb))
(def kcp_sc  (c/mk c/K c/C c/P c/_sc))
(def kcp_qu  (c/mk c/K c/C c/P c/_qu))
(def kcp_bl  (c/mk c/K c/C c/P c/_bl))
(def kcp_cm  (c/mk c/K c/C c/P c/_cm))
(def kcp_pe  (c/mk c/K c/C c/P c/_pe))
(def kcp_sl  (c/mk c/K c/C c/P c/_sl))

(def kotp_ob (c/mk c/K c/O c/T c/P c/_ob))
(def kotp_cb (c/mk c/K c/O c/T c/P c/_cb))
(def kotp_sc (c/mk c/K c/O c/T c/P c/_sc))
(def kotp_qu (c/mk c/K c/O c/T c/P c/_qu))
(def kotp_bl (c/mk c/K c/O c/T c/P c/_bl))
(def kotp_cm (c/mk c/K c/O c/T c/P c/_cm))
(def kotp_pe (c/mk c/K c/O c/T c/P c/_pe))
(def kotp_sl (c/mk c/K c/O c/T c/P c/_sl))

(def kocp_ob (c/mk c/K c/O c/C c/P c/_ob))
(def kocp_cb (c/mk c/K c/O c/C c/P c/_cb))
(def kocp_sc (c/mk c/K c/O c/C c/P c/_sc))
(def kocp_qu (c/mk c/K c/O c/C c/P c/_qu))
(def kocp_bl (c/mk c/K c/O c/C c/P c/_bl))
(def kocp_cm (c/mk c/K c/O c/C c/P c/_cm))
(def kocp_pe (c/mk c/K c/O c/C c/P c/_pe))
(def kocp_sl (c/mk c/K c/O c/C c/P c/_sl))

(def ktcp_ob (c/mk c/K c/T c/C c/P c/_ob))
(def ktcp_cb (c/mk c/K c/T c/C c/P c/_cb))
(def ktcp_sc (c/mk c/K c/T c/C c/P c/_sc))
(def ktcp_qu (c/mk c/K c/T c/C c/P c/_qu))
(def ktcp_bl (c/mk c/K c/T c/C c/P c/_bl))
(def ktcp_cm (c/mk c/K c/T c/C c/P c/_cm))
(def ktcp_pe (c/mk c/K c/T c/C c/P c/_pe))
(def ktcp_sl (c/mk c/K c/T c/C c/P c/_sl))

(def kotcp_ob (c/mk c/K c/O c/T c/C c/P c/_ob))
(def kotcp_cb (c/mk c/K c/O c/T c/C c/P c/_cb))
(def kotcp_sc (c/mk c/K c/O c/T c/C c/P c/_sc))
(def kotcp_qu (c/mk c/K c/O c/T c/C c/P c/_qu))
(def kotcp_bl (c/mk c/K c/O c/T c/C c/P c/_bl))
(def kotcp_cm (c/mk c/K c/O c/T c/C c/P c/_cm))
(def kotcp_pe (c/mk c/K c/O c/T c/C c/P c/_pe))
(def kotcp_sl (c/mk c/K c/O c/T c/C c/P c/_sl))

(def kep_ob  (c/mk c/K c/E c/P c/_ob))
(def kep_cb  (c/mk c/K c/E c/P c/_cb))
(def kep_sc  (c/mk c/K c/E c/P c/_sc))
(def kep_qu  (c/mk c/K c/E c/P c/_qu))
(def kep_bl  (c/mk c/K c/E c/P c/_bl))
(def kep_cm  (c/mk c/K c/E c/P c/_cm))
(def kep_pe  (c/mk c/K c/E c/P c/_pe))
(def kep_sl  (c/mk c/K c/E c/P c/_sl))

(def kwp_ob  (c/mk c/K c/W c/P c/_ob))
(def kwp_cb  (c/mk c/K c/W c/P c/_cb))
(def kwp_sc  (c/mk c/K c/W c/P c/_sc))
(def kwp_qu  (c/mk c/K c/W c/P c/_qu))
(def kwp_bl  (c/mk c/K c/W c/P c/_bl))
(def kwp_cm  (c/mk c/K c/W c/P c/_cm))
(def kwp_pe  (c/mk c/K c/W c/P c/_pe))
(def kwp_sl  (c/mk c/K c/W c/P c/_sl))

(def kqp_ob  (c/mk c/K c/Q c/P c/_ob))
(def kqp_cb  (c/mk c/K c/Q c/P c/_cb))
(def kqp_sc  (c/mk c/K c/Q c/P c/_sc))
(def kqp_qu  (c/mk c/K c/Q c/P c/_qu))
(def kqp_bl  (c/mk c/K c/Q c/P c/_bl))
(def kqp_cm  (c/mk c/K c/Q c/P c/_cm))
(def kqp_pe  (c/mk c/K c/Q c/P c/_pe))
(def kqp_sl  (c/mk c/K c/Q c/P c/_sl))

(def kewqp_ob  (c/mk c/K c/E c/W c/Q c/P c/_ob))
(def kewqp_cb  (c/mk c/K c/E c/W c/Q c/P c/_cb))
(def kewqp_sc  (c/mk c/K c/E c/W c/Q c/P c/_sc))
(def kewqp_qu  (c/mk c/K c/E c/W c/Q c/P c/_qu))
(def kewqp_bl  (c/mk c/K c/E c/W c/Q c/P c/_bl))
(def kewqp_cm  (c/mk c/K c/E c/W c/Q c/P c/_cm))
(def kewqp_pe  (c/mk c/K c/E c/W c/Q c/P c/_pe))
(def kewqp_sl  (c/mk c/K c/E c/W c/Q c/P c/_sl))

(def ksp_ob   (c/mk c/K c/S c/P c/_ob))
(def ksp_cb   (c/mk c/K c/S c/P c/_cb))
(def ksp_sc   (c/mk c/K c/S c/P c/_sc))
(def ksp_qu   (c/mk c/K c/S c/P c/_qu))
(def ksp_bl   (c/mk c/K c/S c/P c/_bl))
(def ksp_cm   (c/mk c/K c/S c/P c/_cm))
(def ksp_pe   (c/mk c/K c/S c/P c/_pe))
(def ksp_sl   (c/mk c/K c/S c/P c/_sl))

(def kosp_ob  (c/mk c/K c/O c/S c/P c/_ob))
(def kosp_cb  (c/mk c/K c/O c/S c/P c/_cb))
(def kosp_sc  (c/mk c/K c/O c/S c/P c/_sc))
(def kosp_qu  (c/mk c/K c/O c/S c/P c/_qu))
(def kosp_bl  (c/mk c/K c/O c/S c/P c/_bl))
(def kosp_cm  (c/mk c/K c/O c/S c/P c/_cm))
(def kosp_pe  (c/mk c/K c/O c/S c/P c/_pe))
(def kosp_sl  (c/mk c/K c/O c/S c/P c/_sl))

(def ktsp_ob  (c/mk c/K c/T c/S c/P c/_ob))
(def ktsp_cb  (c/mk c/K c/T c/S c/P c/_cb))
(def ktsp_sc  (c/mk c/K c/T c/S c/P c/_sc))
(def ktsp_qu  (c/mk c/K c/T c/S c/P c/_qu))
(def ktsp_bl  (c/mk c/K c/T c/S c/P c/_bl))
(def ktsp_cm  (c/mk c/K c/T c/S c/P c/_cm))
(def ktsp_pe  (c/mk c/K c/T c/S c/P c/_pe))
(def ktsp_sl  (c/mk c/K c/T c/S c/P c/_sl))

(def kcsp_ob  (c/mk c/K c/C c/S c/P c/_ob))
(def kcsp_cb  (c/mk c/K c/C c/S c/P c/_cb))
(def kcsp_sc  (c/mk c/K c/C c/S c/P c/_sc))
(def kcsp_qu  (c/mk c/K c/C c/S c/P c/_qu))
(def kcsp_bl  (c/mk c/K c/C c/S c/P c/_bl))
(def kcsp_cm  (c/mk c/K c/C c/S c/P c/_cm))
(def kcsp_pe  (c/mk c/K c/C c/S c/P c/_pe))
(def kcsp_sl  (c/mk c/K c/C c/S c/P c/_sl))

(def kotsp_ob (c/mk c/K c/O c/T c/S c/P c/_ob))
(def kotsp_cb (c/mk c/K c/O c/T c/S c/P c/_cb))
(def kotsp_sc (c/mk c/K c/O c/T c/S c/P c/_sc))
(def kotsp_qu (c/mk c/K c/O c/T c/S c/P c/_qu))
(def kotsp_bl (c/mk c/K c/O c/T c/S c/P c/_bl))
(def kotsp_cm (c/mk c/K c/O c/T c/S c/P c/_cm))
(def kotsp_pe (c/mk c/K c/O c/T c/S c/P c/_pe))
(def kotsp_sl (c/mk c/K c/O c/T c/S c/P c/_sl))

(def kocsp_ob (c/mk c/K c/O c/C c/S c/P c/_ob))
(def kocsp_cb (c/mk c/K c/O c/C c/S c/P c/_cb))
(def kocsp_sc (c/mk c/K c/O c/C c/S c/P c/_sc))
(def kocsp_qu (c/mk c/K c/O c/C c/S c/P c/_qu))
(def kocsp_bl (c/mk c/K c/O c/C c/S c/P c/_bl))
(def kocsp_cm (c/mk c/K c/O c/C c/S c/P c/_cm))
(def kocsp_pe (c/mk c/K c/O c/C c/S c/P c/_pe))
(def kocsp_sl (c/mk c/K c/O c/C c/S c/P c/_sl))

(def ktcsp_ob (c/mk c/K c/T c/C c/S c/P c/_ob))
(def ktcsp_cb (c/mk c/K c/T c/C c/S c/P c/_cb))
(def ktcsp_sc (c/mk c/K c/T c/C c/S c/P c/_sc))
(def ktcsp_qu (c/mk c/K c/T c/C c/S c/P c/_qu))
(def ktcsp_bl (c/mk c/K c/T c/C c/S c/P c/_bl))
(def ktcsp_cm (c/mk c/K c/T c/C c/S c/P c/_cm))
(def ktcsp_pe (c/mk c/K c/T c/C c/S c/P c/_pe))
(def ktcsp_sl (c/mk c/K c/T c/C c/S c/P c/_sl))

(def kotcsp_ob (c/mk c/K c/O c/T c/C c/R c/P c/_ob))
(def kotcsp_cb (c/mk c/K c/O c/T c/C c/R c/P c/_cb))
(def kotcsp_sc (c/mk c/K c/O c/T c/C c/R c/P c/_sc))
(def kotcsp_qu (c/mk c/K c/O c/T c/C c/R c/P c/_qu))
(def kotcsp_bl (c/mk c/K c/O c/T c/C c/R c/P c/_bl))
(def kotcsp_cm (c/mk c/K c/O c/T c/C c/R c/P c/_cm))
(def kotcsp_pe (c/mk c/K c/O c/T c/C c/R c/P c/_pe))
(def kotcsp_sl (c/mk c/K c/O c/T c/C c/R c/P c/_sl))

(def kerp_ob  (c/mk c/K c/E c/R c/P c/_ob))
(def kerp_cb  (c/mk c/K c/E c/R c/P c/_cb))
(def kerp_sc  (c/mk c/K c/E c/R c/P c/_sc))
(def kerp_qu  (c/mk c/K c/E c/R c/P c/_qu))
(def kerp_bl  (c/mk c/K c/E c/R c/P c/_bl))
(def kerp_cm  (c/mk c/K c/E c/R c/P c/_cm))
(def kerp_pe  (c/mk c/K c/E c/R c/P c/_pe))
(def kerp_sl  (c/mk c/K c/E c/R c/P c/_sl))

(def kwsp_ob  (c/mk c/K c/W c/S c/P c/_ob))
(def kwsp_cb  (c/mk c/K c/W c/S c/P c/_cb))
(def kwsp_sc  (c/mk c/K c/W c/S c/P c/_sc))
(def kwsp_qu  (c/mk c/K c/W c/S c/P c/_qu))
(def kwsp_bl  (c/mk c/K c/W c/S c/P c/_bl))
(def kwsp_cm  (c/mk c/K c/W c/S c/P c/_cm))
(def kwsp_pe  (c/mk c/K c/W c/S c/P c/_pe))
(def kwsp_sl  (c/mk c/K c/W c/S c/P c/_sl))

(def kqrp_ob  (c/mk c/K c/Q c/R c/P c/_ob))
(def kqrp_cb  (c/mk c/K c/Q c/R c/P c/_cb))
(def kqrp_sc  (c/mk c/K c/Q c/R c/P c/_sc))
(def kqrp_qu  (c/mk c/K c/Q c/R c/P c/_qu))
(def kqrp_bl  (c/mk c/K c/Q c/R c/P c/_bl))
(def kqrp_cm  (c/mk c/K c/Q c/R c/P c/_cm))
(def kqrp_pe  (c/mk c/K c/Q c/R c/P c/_pe))
(def kqrp_sl  (c/mk c/K c/Q c/R c/P c/_sl))

(def kewqsp_ob  (c/mk c/K c/E c/W c/Q c/S c/P c/_ob))
(def kewqsp_cb  (c/mk c/K c/E c/W c/Q c/S c/P c/_cb))
(def kewqsp_sc  (c/mk c/K c/E c/W c/Q c/S c/P c/_sc))
(def kewqsp_qu  (c/mk c/K c/E c/W c/Q c/S c/P c/_qu))
(def kewqsp_bl  (c/mk c/K c/E c/W c/Q c/S c/P c/_bl))
(def kewqsp_cm  (c/mk c/K c/E c/W c/Q c/S c/P c/_cm))
(def kewqsp_pe  (c/mk c/K c/E c/W c/Q c/S c/P c/_pe))
(def kewqsp_sl  (c/mk c/K c/E c/W c/Q c/S c/P c/_sl))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
