;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; config
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(ns config)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; key maker
(defn mk [& parts]
  (keyword (apply str parts)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; outpath
(def edn-path "edn/")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; programs
(def ay "alacritty")
(def br "broot")
(def mc "micro")
(def hc "helix-common")
(def hi "helix-insert")
(def hn "helix-normal")
(def hs "helix-select")
(def lg "lazygit")
(def tm "term")
(def ze  "zellij-enter")
(def zl  "zellij-lock")
(def zt  "zellij-rtab")
(def zp  "zellij-rpane")
(def zs  "zellij-view")
(def zj  "zellij-share")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; primitive modifiers
(def O "O")
(def E "E")
(def T "T")
(def W "W")
(def C "C")
(def Q "Q")
(def S "S")
(def R "R")

(def K "!")
(def P "#P")
(def KS (str K S))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; primitive glyphs
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; arrow glyphs
(def _pu "page_up")
(def _pd "page_down")
(def _hm "home")
(def _ed "end")

(def _au "up_arrow")
(def _ad "down_arrow")
(def _al "left_arrow")
(def _ar "right_arrow")

; technical glyphs
(def _ob "open_bracket")
(def _cb "close_bracket")
(def _sc "semicolon")
(def _qu "quote")
(def _bl "backslash")
(def _cm "comma")
(def _pe "period")
(def _sl "slash")

; action glyphs
(def _db "delete_or_backspace")
(def _re "return_or_enter")
(def _rs "right_shift")
(def _ro "right_option")
(def _rc "right_command")
(def _sp "spacebar")
(def _rt "right_control")
(def _lc "left_command")
(def _lo "left_option")
(def _lt "left_control")
(def _ls "left_shift")

; numeric glyphs
(def _1 "1")
(def _2 "2")
(def _3 "3")
(def _4 "4")
(def _5 "5")
(def _6 "6")
(def _7 "7")
(def _8 "8")
(def _9 "9")
(def _0 "0")
(def _hy "hyphen")
(def _eq "equal_sign")

; alphabetic glyphs
(def _a "a")
(def _b "b")
(def _c "c")
(def _d "d")
(def _e "e")
(def _f "f")
(def _g "g")
(def _h "h")
(def _i "i")
(def _j "j")
(def _k "k")
(def _l "l")
(def _m "m")
(def _n "n")
(def _o "o")
(def _p "p")
(def _q "q")
(def _r "r")
(def _s "s")
(def _t "t")
(def _u "u")
(def _v "v")
(def _w "w")
(def _x "x")
(def _y "y")
(def _z "z")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; compound glyphs
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; arrow glyphs
(def k_au (mk _au))
(def k_ad (mk _ad))
(def k_al (mk _al))
(def k_ar (mk _ar))

(def ko_au (mk K O _au))
(def ko_ad (mk K O _ad))
(def ko_al (mk K O _al))
(def ko_ar (mk K O _ar))

(def kt_au (mk K T _au))
(def kt_ad (mk K T _ad))
(def kt_al (mk K T _al))
(def kt_ar (mk K T _ar))

(def kc_au (mk K C _au))
(def kc_ad (mk K C _ad))
(def kc_al (mk K C _al))
(def kc_ar (mk K C _ar))

(def kot_au (mk K O T _au))
(def kot_ad (mk K O T _ad))
(def kot_al (mk K O T _al))
(def kot_ar (mk K O T _ar))

(def koc_au (mk K O C _au))
(def koc_ad (mk K O C _ad))
(def koc_al (mk K O C _al))
(def koc_ar (mk K O C _ar))

(def ktc_au (mk K T C _au))
(def ktc_ad (mk K T C _ad))
(def ktc_al (mk K T C _al))
(def ktc_ar (mk K T C _ar))

(def kotc_au (mk K O T C _au))
(def kotc_ad (mk K O T C _ad))
(def kotc_al (mk K O T C _al))
(def kotc_ar (mk K O T C _ar))

(def ks_au (mk KS _au))
(def ks_ad (mk KS _ad))
(def ks_al (mk KS _al))
(def ks_ar (mk KS _ar))

(def kos_au (mk K O S _au))
(def kos_ad (mk K O S _ad))
(def kos_al (mk K O S _al))
(def kos_ar (mk K O S _ar))

(def kts_au (mk K T S _au))
(def kts_ad (mk K T S _ad))
(def kts_al (mk K T S _al))
(def kts_ar (mk K T S _ar))

(def kcs_au (mk K C S _au))
(def kcs_ad (mk K C S _ad))
(def kcs_al (mk K C S _al))
(def kcs_ar (mk K C S _ar))

(def kots_au (mk K O T S _au))
(def kots_ad (mk K O T S _ad))
(def kots_al (mk K O T S _al))
(def kots_ar (mk K O T S _ar))

(def kocs_au (mk K O C S _au))
(def kocs_ad (mk K O C S _ad))
(def kocs_al (mk K O C S _al))
(def kocs_ar (mk K O C S _ar))

(def ktcs_au (mk K T C S _au))
(def ktcs_ad (mk K T C S _ad))
(def ktcs_al (mk K T C S _al))
(def ktcs_ar (mk K T C S _ar))

(def kotcs_au (mk K O T C S _au))
(def kotcs_ad (mk K O T C S _ad))
(def kotcs_al (mk K O T C S _al))
(def kotcs_ar (mk K O T C S _ar))

(def kp_au   (mk K P _au))
(def kp_ad   (mk K P _ad))
(def kp_al   (mk K P _al))
(def kp_ar   (mk K P _ar))

(def kop_au  (mk K O P _au))
(def kop_ad  (mk K O P _ad))
(def kop_al  (mk K O P _al))
(def kop_ar  (mk K O P _ar))

(def ktp_au  (mk K T P _au))
(def ktp_ad  (mk K T P _ad))
(def ktp_al  (mk K T P _al))
(def ktp_ar  (mk K T P _ar))

(def kcp_au  (mk K C P _au))
(def kcp_ad  (mk K C P _ad))
(def kcp_al  (mk K C P _al))
(def kcp_ar  (mk K C P _ar))

(def kotp_au (mk K O T P _au))
(def kotp_ad (mk K O T P _ad))
(def kotp_al (mk K O T P _al))
(def kotp_ar (mk K O T P _ar))

(def kocp_au (mk K O C P _au))
(def kocp_ad (mk K O C P _ad))
(def kocp_al (mk K O C P _al))
(def kocp_ar (mk K O C P _ar))

(def ktcp_au (mk K T C P _au))
(def ktcp_ad (mk K T C P _ad))
(def ktcp_al (mk K T C P _al))
(def ktcp_ar (mk K T C P _ar))

(def kotcp_au (mk K O T C P _au))
(def kotcp_ad (mk K O T C P _ad))
(def kotcp_al (mk K O T C P _al))
(def kotcp_ar (mk K O T C P _ar))

(def ksp_au  (mk K S P _au))
(def ksp_ad  (mk K S P _ad))
(def ksp_al  (mk K S P _al))
(def ksp_ar  (mk K S P _ar))

(def kosp_au (mk K O S P _au))
(def kosp_ad (mk K O S P _ad))
(def kosp_al (mk K O S P _al))
(def kosp_ar (mk K O S P _ar))

(def ktsp_au (mk K T S P _au))
(def ktsp_ad (mk K T S P _ad))
(def ktsp_al (mk K T S P _al))
(def ktsp_ar (mk K T S P _ar))

(def kcsp_au (mk K C S P _au))
(def kcsp_ad (mk K C S P _ad))
(def kcsp_al (mk K C S P _al))
(def kcsp_ar (mk K C S P _ar))

(def kotsp_au (mk K O T S P _au))
(def kotsp_ad (mk K O T S P _ad))
(def kotsp_al (mk K O T S P _al))
(def kotsp_ar (mk K O T S P _ar))

(def kocsp_au (mk K O C S P _au))
(def kocsp_ad (mk K O C S P _ad))
(def kocsp_al (mk K O C S P _al))
(def kocsp_ar (mk K O C S P _ar))

(def ktcsp_au (mk K T C S P _au))
(def ktcsp_ad (mk K T C S P _ad))
(def ktcsp_al (mk K T C S P _al))
(def ktcsp_ar (mk K T C S P _ar))

(def kotcsp_au (mk K O T C S P _au))
(def kotcsp_ad (mk K O T C S P _ad))
(def kotcsp_al (mk K O T C S P _al))
(def kotcsp_ar (mk K O T C S P _ar))

(def k_pu (mk _pu))
(def k_pd (mk _pd))
(def k_hm (mk _hm))
(def k_ed (mk _ed))

(def ks_pu (mk KS _pu))
(def ks_pd (mk KS _pd))
(def ks_hm (mk KS _hm))
(def ks_ed (mk KS _ed))

(def ko_pu (mk K O _pu))
(def ko_pd (mk K O _pd))
(def ko_hm (mk K O _hm))
(def ko_ed (mk K O _ed))

(def kos_pu (mk K O S _pu))
(def kos_pd (mk K O S _pd))
(def kos_hm (mk K O S _hm))
(def kos_ed (mk K O S _ed))

(def kt_pu (mk K T _pu))
(def kt_pd (mk K T _pd))
(def kt_hm (mk K T _hm))
(def kt_ed (mk K T _ed))

(def kts_pu (mk K T S _pu))
(def kts_pd (mk K T S _pd))
(def kts_hm (mk K T S _hm))
(def kts_ed (mk K T S _ed))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; technical glyphs
(def k_ob   (mk _ob))
(def k_cb   (mk _cb))
(def k_sc   (mk _sc))
(def k_qu   (mk _qu))
(def k_bl   (mk _bl))
(def k_cm   (mk _cm))
(def k_pe   (mk _pe))
(def k_sl   (mk _sl))

(def ko_ob  (mk K O _ob))
(def ko_cb  (mk K O _cb))
(def ko_sc  (mk K O _sc))
(def ko_qu  (mk K O _qu))
(def ko_bl  (mk K O _bl))
(def ko_cm  (mk K O _cm))
(def ko_pe  (mk K O _pe))
(def ko_sl  (mk K O _sl))

(def kt_ob  (mk K T _ob))
(def kt_cb  (mk K T _cb))
(def kt_sc  (mk K T _sc))
(def kt_qu  (mk K T _qu))
(def kt_bl  (mk K T _bl))
(def kt_cm  (mk K T _cm))
(def kt_pe  (mk K T _pe))
(def kt_sl  (mk K T _sl))

(def kc_ob  (mk K C _ob))
(def kc_cb  (mk K C _cb))
(def kc_sc  (mk K C _sc))
(def kc_qu  (mk K C _qu))
(def kc_bl  (mk K C _bl))
(def kc_cm  (mk K C _cm))
(def kc_pe  (mk K C _pe))
(def kc_sl  (mk K C _sl))

(def kot_ob (mk K O T _ob))
(def kot_cb (mk K O T _cb))
(def kot_sc (mk K O T _sc))
(def kot_qu (mk K O T _qu))
(def kot_bl (mk K O T _bl))
(def kot_cm (mk K O T _cm))
(def kot_pe (mk K O T _pe))
(def kot_sl (mk K O T _sl))

(def koc_ob (mk K O C _ob))
(def koc_cb (mk K O C _cb))
(def koc_sc (mk K O C _sc))
(def koc_qu (mk K O C _qu))
(def koc_bl (mk K O C _bl))
(def koc_cm (mk K O C _cm))
(def koc_pe (mk K O C _pe))
(def koc_sl (mk K O C _sl))

(def ktc_ob (mk K T C _ob))
(def ktc_cb (mk K T C _cb))
(def ktc_sc (mk K T C _sc))
(def ktc_qu (mk K T C _qu))
(def ktc_bl (mk K T C _bl))
(def ktc_cm (mk K T C _cm))
(def ktc_pe (mk K T C _pe))
(def ktc_sl (mk K T C _sl))

(def kotc_ob (mk K O T C _ob))
(def kotc_cb (mk K O T C _cb))
(def kotc_sc (mk K O T C _sc))
(def kotc_qu (mk K O T C _qu))
(def kotc_bl (mk K O T C _bl))
(def kotc_cm (mk K O T C _cm))
(def kotc_pe (mk K O T C _pe))
(def kotc_sl (mk K O T C _sl))

(def ks_ob   (mk K S _ob))
(def ks_cb   (mk K S _cb))
(def ks_sc   (mk K S _sc))
(def ks_qu   (mk K S _qu))
(def ks_bl   (mk K S _bl))
(def ks_cm   (mk K S _cm))
(def ks_pe   (mk K S _pe))
(def ks_sl   (mk K S _sl))

(def kos_ob  (mk K O S _ob))
(def kos_cb  (mk K O S _cb))
(def kos_sc  (mk K O S _sc))
(def kos_qu  (mk K O S _qu))
(def kos_bl  (mk K O S _bl))
(def kos_cm  (mk K O S _cm))
(def kos_pe  (mk K O S _pe))
(def kos_sl  (mk K O S _sl))

(def kts_ob  (mk K T S _ob))
(def kts_cb  (mk K T S _cb))
(def kts_sc  (mk K T S _sc))
(def kts_qu  (mk K T S _qu))
(def kts_bl  (mk K T S _bl))
(def kts_cm  (mk K T S _cm))
(def kts_pe  (mk K T S _pe))
(def kts_sl  (mk K T S _sl))

(def kcs_ob  (mk K C S _ob))
(def kcs_cb  (mk K C S _cb))
(def kcs_sc  (mk K C S _sc))
(def kcs_qu  (mk K C S _qu))
(def kcs_bl  (mk K C S _bl))
(def kcs_cm  (mk K C S _cm))
(def kcs_pe  (mk K C S _pe))
(def kcs_sl  (mk K C S _sl))

(def kots_ob (mk K O T S _ob))
(def kots_cb (mk K O T S _cb))
(def kots_sc (mk K O T S _sc))
(def kots_qu (mk K O T S _qu))
(def kots_bl (mk K O T S _bl))
(def kots_cm (mk K O T S _cm))
(def kots_pe (mk K O T S _pe))
(def kots_sl (mk K O T S _sl))

(def kocs_ob (mk K O C S _ob))
(def kocs_cb (mk K O C S _cb))
(def kocs_sc (mk K O C S _sc))
(def kocs_qu (mk K O C S _qu))
(def kocs_bl (mk K O C S _bl))
(def kocs_cm (mk K O C S _cm))
(def kocs_pe (mk K O C S _pe))
(def kocs_sl (mk K O C S _sl))

(def ktcs_ob (mk K T C S _ob))
(def ktcs_cb (mk K T C S _cb))
(def ktcs_sc (mk K T C S _sc))
(def ktcs_qu (mk K T C S _qu))
(def ktcs_bl (mk K T C S _bl))
(def ktcs_cm (mk K T C S _cm))
(def ktcs_pe (mk K T C S _pe))
(def ktcs_sl (mk K T C S _sl))

(def kotcs_ob (mk K O T C S _ob))
(def kotcs_cb (mk K O T C S _cb))
(def kotcs_sc (mk K O T C S _sc))
(def kotcs_qu (mk K O T C S _qu))
(def kotcs_bl (mk K O T C S _bl))
(def kotcs_cm (mk K O T C S _cm))
(def kotcs_pe (mk K O T C S _pe))
(def kotcs_sl (mk K O T C S _sl))

(def kp_ob   (mk K P _ob))
(def kp_cb   (mk K P _cb))
(def kp_sc   (mk K P _sc))
(def kp_qu   (mk K P _qu))
(def kp_bl   (mk K P _bl))
(def kp_cm   (mk K P _cm))
(def kp_pe   (mk K P _pe))
(def kp_sl   (mk K P _sl))

(def kop_ob  (mk K O P _ob))
(def kop_cb  (mk K O P _cb))
(def kop_sc  (mk K O P _sc))
(def kop_qu  (mk K O P _qu))
(def kop_bl  (mk K O P _bl))
(def kop_cm  (mk K O P _cm))
(def kop_pe  (mk K O P _pe))
(def kop_sl  (mk K O P _sl))

(def ktp_ob  (mk K T P _ob))
(def ktp_cb  (mk K T P _cb))
(def ktp_sc  (mk K T P _sc))
(def ktp_qu  (mk K T P _qu))
(def ktp_bl  (mk K T P _bl))
(def ktp_cm  (mk K T P _cm))
(def ktp_pe  (mk K T P _pe))
(def ktp_sl  (mk K T P _sl))

(def kcp_ob  (mk K C P _ob))
(def kcp_cb  (mk K C P _cb))
(def kcp_sc  (mk K C P _sc))
(def kcp_qu  (mk K C P _qu))
(def kcp_bl  (mk K C P _bl))
(def kcp_cm  (mk K C P _cm))
(def kcp_pe  (mk K C P _pe))
(def kcp_sl  (mk K C P _sl))

(def kotp_ob (mk K O T P _ob))
(def kotp_cb (mk K O T P _cb))
(def kotp_sc (mk K O T P _sc))
(def kotp_qu (mk K O T P _qu))
(def kotp_bl (mk K O T P _bl))
(def kotp_cm (mk K O T P _cm))
(def kotp_pe (mk K O T P _pe))
(def kotp_sl (mk K O T P _sl))

(def kocp_ob (mk K O C P _ob))
(def kocp_cb (mk K O C P _cb))
(def kocp_sc (mk K O C P _sc))
(def kocp_qu (mk K O C P _qu))
(def kocp_bl (mk K O C P _bl))
(def kocp_cm (mk K O C P _cm))
(def kocp_pe (mk K O C P _pe))
(def kocp_sl (mk K O C P _sl))

(def ktcp_ob (mk K T C P _ob))
(def ktcp_cb (mk K T C P _cb))
(def ktcp_sc (mk K T C P _sc))
(def ktcp_qu (mk K T C P _qu))
(def ktcp_bl (mk K T C P _bl))
(def ktcp_cm (mk K T C P _cm))
(def ktcp_pe (mk K T C P _pe))
(def ktcp_sl (mk K T C P _sl))

(def kotcp_ob (mk K O T C P _ob))
(def kotcp_cb (mk K O T C P _cb))
(def kotcp_sc (mk K O T C P _sc))
(def kotcp_qu (mk K O T C P _qu))
(def kotcp_bl (mk K O T C P _bl))
(def kotcp_cm (mk K O T C P _cm))
(def kotcp_pe (mk K O T C P _pe))
(def kotcp_sl (mk K O T C P _sl))

(def ksp_ob   (mk K S P _ob))
(def ksp_cb   (mk K S P _cb))
(def ksp_sc   (mk K S P _sc))
(def ksp_qu   (mk K S P _qu))
(def ksp_bl   (mk K S P _bl))
(def ksp_cm   (mk K S P _cm))
(def ksp_pe   (mk K S P _pe))
(def ksp_sl   (mk K S P _sl))

(def kosp_ob  (mk K O S P _ob))
(def kosp_cb  (mk K O S P _cb))
(def kosp_sc  (mk K O S P _sc))
(def kosp_qu  (mk K O S P _qu))
(def kosp_bl  (mk K O S P _bl))
(def kosp_cm  (mk K O S P _cm))
(def kosp_pe  (mk K O S P _pe))
(def kosp_sl  (mk K O S P _sl))

(def ktsp_ob  (mk K T S P _ob))
(def ktsp_cb  (mk K T S P _cb))
(def ktsp_sc  (mk K T S P _sc))
(def ktsp_qu  (mk K T S P _qu))
(def ktsp_bl  (mk K T S P _bl))
(def ktsp_cm  (mk K T S P _cm))
(def ktsp_pe  (mk K T S P _pe))
(def ktsp_sl  (mk K T S P _sl))

(def kcsp_ob  (mk K C S P _ob))
(def kcsp_cb  (mk K C S P _cb))
(def kcsp_sc  (mk K C S P _sc))
(def kcsp_qu  (mk K C S P _qu))
(def kcsp_bl  (mk K C S P _bl))
(def kcsp_cm  (mk K C S P _cm))
(def kcsp_pe  (mk K C S P _pe))
(def kcsp_sl  (mk K C S P _sl))

(def kotsp_ob (mk K O T S P _ob))
(def kotsp_cb (mk K O T S P _cb))
(def kotsp_sc (mk K O T S P _sc))
(def kotsp_qu (mk K O T S P _qu))
(def kotsp_bl (mk K O T S P _bl))
(def kotsp_cm (mk K O T S P _cm))
(def kotsp_pe (mk K O T S P _pe))
(def kotsp_sl (mk K O T S P _sl))

(def kocsp_ob (mk K O C S P _ob))
(def kocsp_cb (mk K O C S P _cb))
(def kocsp_sc (mk K O C S P _sc))
(def kocsp_qu (mk K O C S P _qu))
(def kocsp_bl (mk K O C S P _bl))
(def kocsp_cm (mk K O C S P _cm))
(def kocsp_pe (mk K O C S P _pe))
(def kocsp_sl (mk K O C S P _sl))

(def ktcsp_ob (mk K T C S P _ob))
(def ktcsp_cb (mk K T C S P _cb))
(def ktcsp_sc (mk K T C S P _sc))
(def ktcsp_qu (mk K T C S P _qu))
(def ktcsp_bl (mk K T C S P _bl))
(def ktcsp_cm (mk K T C S P _cm))
(def ktcsp_pe (mk K T C S P _pe))
(def ktcsp_sl (mk K T C S P _sl))

(def kotcsp_ob (mk K O T C S P _ob))
(def kotcsp_cb (mk K O T C S P _cb))
(def kotcsp_sc (mk K O T C S P _sc))
(def kotcsp_qu (mk K O T C S P _qu))
(def kotcsp_bl (mk K O T C S P _bl))
(def kotcsp_cm (mk K O T C S P _cm))
(def kotcsp_pe (mk K O T C S P _pe))
(def kotcsp_sl (mk K O T C S P _sl))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; action glyphs
(def k_db (mk _db))
(def k_re (mk _re))
(def k_rs (mk _rs))
(def k_ro (mk _ro))
(def k_rc (mk _rc))
(def k_sp (mk _sp))

(def ko_db (mk K O _db))
(def ko_re (mk K O _re))
(def ko_rs (mk K O _rs))
(def ko_ro (mk K O _ro))
(def ko_rc (mk K O _rc))
(def ko_sp (mk K O _sp))

(def kt_db (mk K T _db))
(def kt_re (mk K T _re))
(def kt_rs (mk K T _rs))
(def kt_ro (mk K T _ro))
(def kt_rc (mk K T _rc))
(def kt_sp (mk K T _sp))

(def kc_db (mk K C _db))
(def kc_re (mk K C _re))
(def kc_rs (mk K C _rs))
(def kc_ro (mk K C _ro))
(def kc_rc (mk K C _rc))
(def kc_sp (mk K C _sp))

(def kot_db (mk K O T _db))
(def kot_re (mk K O T _re))
(def kot_rs (mk K O T _rs))
(def kot_ro (mk K O T _ro))
(def kot_rc (mk K O T _rc))
(def kot_sp (mk K O T _sp))

(def koc_db (mk K O C _db))
(def koc_re (mk K O C _re))
(def koc_rs (mk K O C _rs))
(def koc_ro (mk K O C _ro))
(def koc_rc (mk K O C _rc))
(def koc_sp (mk K O C _sp))

(def ktc_db (mk K T C _db))
(def ktc_re (mk K T C _re))
(def ktc_rs (mk K T C _rs))
(def ktc_ro (mk K T C _ro))
(def ktc_rc (mk K T C _rc))
(def ktc_sp (mk K T C _sp))

(def kotc_db (mk K O T C _db))
(def kotc_re (mk K O T C _re))
(def kotc_rs (mk K O T C _rs))
(def kotc_ro (mk K O T C _ro))
(def kotc_rc (mk K O T C _rc))
(def kotc_sp (mk K O T C _sp))

(def ks_db (mk K S _db))
(def ks_re (mk K S _re))
(def ks_rs (mk K S _rs))
(def ks_ro (mk K S _ro))
(def ks_rc (mk K S _rc))
(def ks_sp (mk K S _sp))

(def kos_db (mk K O S _db))
(def kos_re (mk K O S _re))
(def kos_rs (mk K O S _rs))
(def kos_ro (mk K O S _ro))
(def kos_rc (mk K O S _rc))
(def kos_sp (mk K O S _sp))

(def kts_db (mk K T S _db))
(def kts_re (mk K T S _re))
(def kts_rs (mk K T S _rs))
(def kts_ro (mk K T S _ro))
(def kts_rc (mk K T S _rc))
(def kts_sp (mk K T S _sp))

(def kcs_db (mk K C S _db))
(def kcs_re (mk K C S _re))
(def kcs_rs (mk K C S _rs))
(def kcs_ro (mk K C S _ro))
(def kcs_rc (mk K C S _rc))
(def kcs_sp (mk K C S _sp))

(def kots_db (mk K O T S _db))
(def kots_re (mk K O T S _re))
(def kots_rs (mk K O T S _rs))
(def kots_ro (mk K O T S _ro))
(def kots_rc (mk K O T S _rc))
(def kots_sp (mk K O T S _sp))

(def kocs_db (mk K O C S _db))
(def kocs_re (mk K O C _re))
(def kocs_rs (mk K O C S _rs))
(def kocs_ro (mk K O C S _ro))
(def kocs_rc (mk K O C S _rc))
(def kocs_sp (mk K O C S _sp))

(def ktcs_db (mk K T C S _db))
(def ktcs_re (mk K T C S _re))
(def ktcs_rs (mk K T C S _rs))
(def ktcs_ro (mk K T C S _ro))
(def ktcs_rc (mk K T C S _rc))
(def ktcs_sp (mk K T C S _sp))

(def kotcs_db (mk K O T C S _db))
(def kotcs_re (mk K O T C S _re))
(def kotcs_rs (mk K O T C S _rs))
(def kotcs_ro (mk K O T C S _ro))
(def kotcs_rc (mk K O T C S _rc))
(def kotcs_sp (mk K O T C S _sp))

(def kp_db   (mk K P _db))
(def kp_re   (mk K P _re))
(def kp_rs   (mk K P _rs))
(def kp_ro   (mk K P _ro))
(def kp_rc   (mk K P _rc))
(def kp_sp   (mk K P _sp))

(def kop_db  (mk K O P _db))
(def kop_re  (mk K O P _re))
(def kop_rs  (mk K O P _rs))
(def kop_ro  (mk K O P _ro))
(def kop_rc  (mk K O P _rc))
(def kop_sp  (mk K O P _sp))

(def ktp_db  (mk K T P _db))
(def ktp_re  (mk K T P _re))
(def ktp_rs  (mk K T P _rs))
(def ktp_ro  (mk K T P _ro))
(def ktp_rc  (mk K T P _rc))
(def ktp_sp  (mk K T P _sp))

(def kcp_db  (mk K C P _db))
(def kcp_re  (mk K C P _re))
(def kcp_rs  (mk K C P _rs))
(def kcp_ro  (mk K C P _ro))
(def kcp_rc  (mk K C P _rc))
(def kcp_sp  (mk K C P _sp))

(def kotp_db (mk K O T P _db))
(def kotp_re (mk K O T P _re))
(def kotp_rs (mk K O T P _rs))
(def kotp_ro (mk K O T P _ro))
(def kotp_rc (mk K O T P _rc))
(def kotp_sp (mk K O T P _sp))

(def kocp_db (mk K O C P _db))
(def kocp_re (mk K O C P _re))
(def kocp_rs (mk K O C P _rs))
(def kocp_ro (mk K O C P _ro))
(def kocp_rc (mk K O C P _rc))
(def kocp_sp (mk K O C P _sp))

(def ktcp_db (mk K T C P _db))
(def ktcp_re (mk K T C P _re))
(def ktcp_rs (mk K T C P _rs))
(def ktcp_ro (mk K T C P _ro))
(def ktcp_rc (mk K T C P _rc))
(def ktcp_sp (mk K T C P _sp))

(def kotcp_db (mk K O T C P _db))
(def kotcp_re (mk K O T C P _re))
(def kotcp_rs (mk K O T C P _rs))
(def kotcp_ro (mk K O T C P _ro))
(def kotcp_rc (mk K O T C P _rc))
(def kotcp_sp (mk K O T C P _sp))

(def ksp_db   (mk K S P _db))
(def ksp_re   (mk K S P _re))
(def ksp_rs   (mk K S P _rs))
(def ksp_ro   (mk K S P _ro))
(def ksp_rc   (mk K S P _rc))
(def ksp_sp   (mk K S P _sp))

(def kosp_db  (mk K O S P _db))
(def kosp_re  (mk K O S P _re))
(def kosp_rs  (mk K O S P _rs))
(def kosp_ro  (mk K O S P _ro))
(def kosp_rc  (mk K O S P _rc))
(def kosp_sp  (mk K O S P _sp))

(def ktsp_db  (mk K T S P _db))
(def ktsp_re  (mk K T S P _re))
(def ktsp_rs  (mk K T S P _rs))
(def ktsp_ro  (mk K T S P _ro))
(def ktsp_rc  (mk K T S P _rc))
(def ktsp_sp  (mk K T S P _sp))

(def kcsp_db  (mk K C S P _db))
(def kcsp_re  (mk K C S P _re))
(def kcsp_rs  (mk K C S P _rs))
(def kcsp_ro  (mk K C S P _ro))
(def kcsp_rc  (mk K C S P _rc))
(def kcsp_sp  (mk K C S P _sp))

(def kotsp_db (mk K O T S P _db))
(def kotsp_re (mk K O T S P _re))
(def kotsp_rs (mk K O T S P _rs))
(def kotsp_ro (mk K O T S P _ro))
(def kotsp_rc (mk K O T S P _rc))
(def kotsp_sp (mk K O T S P _sp))

(def kocsp_db (mk K O C S P _db))
(def kocsp_re (mk K O C S P _re))
(def kocsp_rs (mk K O C S P _rs))
(def kocsp_ro (mk K O C S P _ro))
(def kocsp_rc (mk K O C S P _rc))
(def kocsp_sp (mk K O C S P _sp))

(def ktcsp_db (mk K T C S P _db))
(def ktcsp_re (mk K T C S P _re))
(def ktcsp_rs (mk K T C S P _rs))
(def ktcsp_ro (mk K T C S P _ro))
(def ktcsp_rc (mk K T C S P _rc))
(def ktcsp_sp (mk K T C S P _sp))

(def kotcsp_db (mk K O T C S P _db))
(def kotcsp_re (mk K O T C S P _re))
(def kotcsp_rs (mk K O T C S P _rs))
(def kotcsp_ro (mk K O T C S P _ro))
(def kotcsp_rc (mk K O T C S P _rc))
(def kotcsp_sp (mk K O T C S P _sp))

(def k_rt (mk K _rt))
(def k_lc (mk K _lc))
(def k_lo (mk K _lo))
(def k_lt (mk K _lt))
(def k_ls (mk K _ls))

(def ko_rt (mk K O _rt))
(def ko_lc (mk K O _lc))
(def ko_lo (mk K O _lo))
(def ko_lt (mk K O _lt))
(def ko_ls (mk K O _ls))

(def kt_rt (mk K T _rt))
(def kt_lc (mk K T _lc))
(def kt_lo (mk K T _lo))
(def kt_lt (mk K T _lt))
(def kt_ls (mk K T _ls))

(def kc_rt (mk K C _rt))
(def kc_lc (mk K C _lc))
(def kc_lo (mk K C _lo))
(def kc_lt (mk K C _lt))
(def kc_ls (mk K C _ls))

(def kot_rt (mk K O T _rt))
(def kot_lc (mk K O T _lc))
(def kot_lo (mk K O T _lo))
(def kot_lt (mk K O T _lt))
(def kot_ls (mk K O T _ls))

(def koc_rt (mk K O C _rt))
(def koc_lc (mk K O C _lc))
(def koc_lo (mk K O C _lo))
(def koc_lt (mk K O C _lt))
(def koc_ls (mk K O C _ls))

(def ktc_rt (mk K T C _rt))
(def ktc_lc (mk K T C _lc))
(def ktc_lo (mk K T C _lo))
(def ktc_lt (mk K T C _lt))
(def ktc_ls (mk K T C _ls))

(def kotc_rt (mk K O T C _rt))
(def kotc_lc (mk K O T C _lc))
(def kotc_lo (mk K O T C _lo))
(def kotc_lt (mk K O T C _lt))
(def kotc_ls (mk K O T C _ls))

(def ks_rt (mk K S _rt))
(def ks_lc (mk K S _lc))
(def ks_lo (mk K S _lo))
(def ks_lt (mk K S _lt))
(def ks_ls (mk K S _ls))

(def kos_rt (mk K O S _rt))
(def kos_lc (mk K O S _lc))
(def kos_lo (mk K O S _lo))
(def kos_lt (mk K O S _lt))
(def kos_ls (mk K O S _ls))

(def kts_rt (mk K T S _rt))
(def kts_lc (mk K T S _lc))
(def kts_lo (mk K T S _lo))
(def kts_lt (mk K T S _lt))
(def kts_ls (mk K T S _ls))

(def kcs_rt (mk K C S _rt))
(def kcs_lc (mk K C S _lc))
(def kcs_lo (mk K C S _lo))
(def kcs_lt (mk K C S _lt))
(def kcs_ls (mk K C S _ls))

(def kots_rt (mk K O T S _rt))
(def kots_lc (mk K O T S _lc))
(def kots_lo (mk K O T S _lo))
(def kots_lt (mk K O T S _lt))
(def kots_ls (mk K O T S _ls))

(def kocs_rt (mk K O C S _rt))
(def kocs_lc (mk K O C S _lc))
(def kocs_lo (mk K O C S _lo))
(def kocs_lt (mk K O C S _lt))
(def kocs_ls (mk K O C S _ls))

(def ktcs_rt (mk K T C S _rt))
(def ktcs_lc (mk K T C S _lc))
(def ktcs_lo (mk K T C S _lo))
(def ktcs_lt (mk K T C S _lt))
(def ktcs_ls (mk K T C S _ls))

(def kotcs_rt (mk K O T C S _rt))
(def kotcs_lc (mk K O T C S _lc))
(def kotcs_lo (mk K O T C S _lo))
(def kotcs_lt (mk K O T C S _lt))
(def kotcs_ls (mk K O T C S _ls))

(def kp_rt (mk K P _rt))
(def kp_lc (mk K P _lc))
(def kp_lo (mk K P _lo))
(def kp_lt (mk K P _lt))
(def kp_ls (mk K P _ls))

(def kop_rt (mk K O P _rt))
(def kop_lc (mk K O P _lc))
(def kop_lo (mk K O P _lo))
(def kop_lt (mk K O P _lt))
(def kop_ls (mk K O P _ls))

(def ktp_rt (mk K T P _rt))
(def ktp_lc (mk K T P _lc))
(def ktp_lo (mk K T P _lo))
(def ktp_lt (mk K T P _lt))
(def ktp_ls (mk K T P _ls))

(def kcp_rt (mk K C P _rt))
(def kcp_lc (mk K C P _lc))
(def kcp_lo (mk K C P _lo))
(def kcp_lt (mk K C P _lt))
(def kcp_ls (mk K C P _ls))

(def kotp_rt (mk K O T P _rt))
(def kotp_lc (mk K O T P _lc))
(def kotp_lo (mk K O T P _lo))
(def kotp_lt (mk K O T P _lt))
(def kotp_ls (mk K O T P _ls))

(def kocp_rt (mk K O C P _rt))
(def kocp_lc (mk K O C P _lc))
(def kocp_lo (mk K O C P _lo))
(def kocp_lt (mk K O C P _lt))
(def kocp_ls (mk K O C P _ls))

(def ktcp_rt (mk K T C P _rt))
(def ktcp_lc (mk K T C P _lc))
(def ktcp_lo (mk K T C P _lo))
(def ktcp_lt (mk K T C P _lt))
(def ktcp_ls (mk K T C P _ls))

(def kotcp_rt (mk K O T C P _rt))
(def kotcp_lc (mk K O T C P _lc))
(def kotcp_lo (mk K O T C P _lo))
(def kotcp_lt (mk K O T C P _lt))
(def kotcp_ls (mk K O T C P _ls))

(def ksp_rt (mk K S P _rt))
(def ksp_lc (mk K S P _lc))
(def ksp_lo (mk K S P _lo))
(def ksp_lt (mk K S P _lt))
(def ksp_ls (mk K S P _ls))

(def kosp_rt (mk K O S P _rt))
(def kosp_lc (mk K O S P _lc))
(def kosp_lo (mk K O S P _lo))
(def kosp_lt (mk K O S P _lt))
(def kosp_ls (mk K O S P _ls))

(def ktsp_rt (mk K T S P _rt))
(def ktsp_lc (mk K T S P _lc))
(def ktsp_lo (mk K T S P _lo))
(def ktsp_lt (mk K T S P _lt))
(def ktsp_ls (mk K T S P _ls))

(def kcsp_rt (mk K C S P _rt))
(def kcsp_lc (mk K C S P _lc))
(def kcsp_lo (mk K C S P _lo))
(def kcsp_lt (mk K C S P _lt))
(def kcsp_ls (mk K C S P _ls))

(def kotsp_rt (mk K O T S P _rt))
(def kotsp_lc (mk K O T S P _lc))
(def kotsp_lo (mk K O T S P _lo))
(def kotsp_lt (mk K O T S P _lt))
(def kotsp_ls (mk K O T S P _ls))

(def kocsp_rt (mk K O C S P _rt))
(def kocsp_lc (mk K O C S P _lc))
(def kocsp_lo (mk K O C S P _lo))
(def kocsp_lt (mk K O C S P _lt))
(def kocsp_ls (mk K O C S P _ls))

(def ktcsp_rt (mk K T C S P _rt))
(def ktcsp_lc (mk K T C S P _lc))
(def ktcsp_lo (mk K T C S P _lo))
(def ktcsp_lt (mk K T C S P _lt))
(def ktcsp_ls (mk K T C S P _ls))

(def kotcsp_rt (mk K O T C S P _rt))
(def kotcsp_lc (mk K O T C S P _lc))
(def kotcsp_lo (mk K O T C S P _lo))
(def kotcsp_lt (mk K O T C S P _lt))
(def kotcsp_ls (mk K O T C S P _ls))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; numeric glyphs
(def k_1 (mk K _1))
(def k_2 (mk K _2))
(def k_3 (mk K _3))
(def k_4 (mk K _4))
(def k_5 (mk K _5))
(def k_6 (mk K _6))
(def k_7 (mk K _7))
(def k_8 (mk K _8))
(def k_9 (mk K _9))
(def k_0 (mk K _0))
(def k_hy (mk K _hy))
(def k_eq (mk K _eq))

(def ko_1  (mk K O _1))
(def ko_2  (mk K O _2))
(def ko_3  (mk K O _3))
(def ko_4  (mk K O _4))
(def ko_5  (mk K O _5))
(def ko_6  (mk K O _6))
(def ko_7  (mk K O _7))
(def ko_8  (mk K O _8))
(def ko_9  (mk K O _9))
(def ko_0  (mk K O _0))
(def ko_hy (mk K O _hy))
(def ko_eq (mk K O _eq))

(def kt_1  (mk K T _1))
(def kt_2  (mk K T _2))
(def kt_3  (mk K T _3))
(def kt_4  (mk K T _4))
(def kt_5  (mk K T _5))
(def kt_6  (mk K T _6))
(def kt_7  (mk K T _7))
(def kt_8  (mk K T _8))
(def kt_9  (mk K T _9))
(def kt_0  (mk K T _0))
(def kt_hy (mk K T _hy))
(def kt_eq (mk K T _eq))

(def kc_1  (mk K C _1))
(def kc_2  (mk K C _2))
(def kc_3  (mk K C _3))
(def kc_4  (mk K C _4))
(def kc_5  (mk K C _5))
(def kc_6  (mk K C _6))
(def kc_7  (mk K C _7))
(def kc_8  (mk K C _8))
(def kc_9  (mk K C _9))
(def kc_0  (mk K C _0))
(def kc_hy (mk K C _hy))
(def kc_eq (mk K C _eq))

(def kot_1  (mk K O T _1))
(def kot_2  (mk K O T _2))
(def kot_3  (mk K O T _3))
(def kot_4  (mk K O T _4))
(def kot_5  (mk K O T _5))
(def kot_6  (mk K O T _6))
(def kot_7  (mk K O T _7))
(def kot_8  (mk K O T _8))
(def kot_9  (mk K O T _9))
(def kot_0  (mk K O T _0))
(def kot_hy (mk K O T _hy))
(def kot_eq (mk K O T _eq))

(def koc_1  (mk K O C _1))
(def koc_2  (mk K O C _2))
(def koc_3  (mk K O C _3))
(def koc_4  (mk K O C _4))
(def koc_5  (mk K O C _5))
(def koc_6  (mk K O C _6))
(def koc_7  (mk K O C _7))
(def koc_8  (mk K O C _8))
(def koc_9  (mk K O C _9))
(def koc_0  (mk K O C _0))
(def koc_hy (mk K O C _hy))
(def koc_eq (mk K O C _eq))

(def ktc_1  (mk K T C _1))
(def ktc_2  (mk K T C _2))
(def ktc_3  (mk K T C _3))
(def ktc_4  (mk K T C _4))
(def ktc_5  (mk K T C _5))
(def ktc_6  (mk K T C _6))
(def ktc_7  (mk K T C _7))
(def ktc_8  (mk K T C _8))
(def ktc_9  (mk K T C _9))
(def ktc_0  (mk K T C _0))
(def ktc_hy (mk K T C _hy))
(def ktc_eq (mk K T C _eq))

(def kotc_1  (mk K O T C _1))
(def kotc_2  (mk K O T C _2))
(def kotc_3  (mk K O T C _3))
(def kotc_4  (mk K O T C _4))
(def kotc_5  (mk K O T C _5))
(def kotc_6  (mk K O T C _6))
(def kotc_7  (mk K O T C _7))
(def kotc_8  (mk K O T C _8))
(def kotc_9  (mk K O T C _9))
(def kotc_0  (mk K O T C _0))
(def kotc_hy (mk K O T C _hy))
(def kotc_eq (mk K O T C _eq))

(def ks_1  (mk KS _1))
(def ks_2  (mk KS _2))
(def ks_3  (mk KS _3))
(def ks_4  (mk KS _4))
(def ks_5  (mk KS _5))
(def ks_6  (mk KS _6))
(def ks_7  (mk KS _7))
(def ks_8  (mk KS _8))
(def ks_9  (mk KS _9))
(def ks_0  (mk KS _0))
(def ks_hy (mk K S _hy))
(def ks_eq (mk K S _eq))

(def kos_1  (mk K O S _1))
(def kos_2  (mk K O S _2))
(def kos_3  (mk K O S _3))
(def kos_4  (mk K O S _4))
(def kos_5  (mk K O S _5))
(def kos_6  (mk K O S _6))
(def kos_7  (mk K O S _7))
(def kos_8  (mk K O S _8))
(def kos_9  (mk K O S _9))
(def kos_0  (mk K O S _0))
(def kos_hy (mk K O S _hy))
(def kos_eq (mk K O S _eq))

(def kts_1  (mk K T S _1))
(def kts_2  (mk K T S _2))
(def kts_3  (mk K T S _3))
(def kts_4  (mk K T S _4))
(def kts_5  (mk K T S _5))
(def kts_6  (mk K T S _6))
(def kts_7  (mk K T S _7))
(def kts_8  (mk K T S _8))
(def kts_9  (mk K T S _9))
(def kts_0  (mk K T S _0))
(def kts_hy (mk K T S _hy))
(def kts_eq (mk K T S _eq))

(def kcs_1  (mk K C S _1))
(def kcs_2  (mk K C S _2))
(def kcs_3  (mk K C S _3))
(def kcs_4  (mk K C S _4))
(def kcs_5  (mk K C S _5))
(def kcs_6  (mk K C S _6))
(def kcs_7  (mk K C S _7))
(def kcs_8  (mk K C S _8))
(def kcs_9  (mk K C S _9))
(def kcs_0  (mk K C S _0))
(def kcs_hy (mk K C S _hy))
(def kcs_eq (mk K C S _eq))

(def kots_1  (mk K O T S _1))
(def kots_2  (mk K O T S _2))
(def kots_3  (mk K O T S _3))
(def kots_4  (mk K O T S _4))
(def kots_5  (mk K O T S _5))
(def kots_6  (mk K O T S _6))
(def kots_7  (mk K O T S _7))
(def kots_8  (mk K O T S _8))
(def kots_9  (mk K O T S _9))
(def kots_0  (mk K O T S _0))
(def kots_hy (mk K O T S _hy))
(def kots_eq (mk K O T S _eq))

(def kocs_1  (mk K O C S _1))
(def kocs_2  (mk K O C S _2))
(def kocs_3  (mk K O C S _3))
(def kocs_4  (mk K O C S _4))
(def kocs_5  (mk K O C S _5))
(def kocs_6  (mk K O C S _6))
(def kocs_7  (mk K O C S _7))
(def kocs_8  (mk K O C S _8))
(def kocs_9  (mk K O C S _9))
(def kocs_0  (mk K O C S _0))
(def kocs_hy (mk K O C S _hy))
(def kocs_eq (mk K O C S _eq))

(def ktcs_1  (mk K T C S _1))
(def ktcs_2  (mk K T C S _2))
(def ktcs_3  (mk K T C S _3))
(def ktcs_4  (mk K T C S _4))
(def ktcs_5  (mk K T C S _5))
(def ktcs_6  (mk K T C S _6))
(def ktcs_7  (mk K T C S _7))
(def ktcs_8  (mk K T C S _8))
(def ktcs_9  (mk K T C S _9))
(def ktcs_0  (mk K T C S _0))
(def ktcs_hy (mk K T C S _hy))
(def ktcs_eq (mk K T C S _eq))

(def kotcs_1  (mk K O T C S _1))
(def kotcs_2  (mk K O T C S _2))
(def kotcs_3  (mk K O T C S _3))
(def kotcs_4  (mk K O T C S _4))
(def kotcs_5  (mk K O T C S _5))
(def kotcs_6  (mk K O T C S _6))
(def kotcs_7  (mk K O T C S _7))
(def kotcs_8  (mk K O T C S _8))
(def kotcs_9  (mk K O T C S _9))
(def kotcs_0  (mk K O T C S _0))
(def kotcs_hy (mk K O T C S _hy))
(def kotcs_eq (mk K O T C S _eq))

(def kp_1  (mk K P _1))
(def kp_2  (mk K P _2))
(def kp_3  (mk K P _3))
(def kp_4  (mk K P _4))
(def kp_5  (mk K P _5))
(def kp_6  (mk K P _6))
(def kp_7  (mk K P _7))
(def kp_8  (mk K P _8))
(def kp_9  (mk K P _9))
(def kp_0  (mk K P _0))
(def kp_hy (mk K P _hy))
(def kp_eq (mk K P _eq))

(def kop_1  (mk K O P _1))
(def kop_2  (mk K O P _2))
(def kop_3  (mk K O P _3))
(def kop_4  (mk K O P _4))
(def kop_5  (mk K O P _5))
(def kop_6  (mk K O P _6))
(def kop_7  (mk K O P _7))
(def kop_8  (mk K O P _8))
(def kop_9  (mk K O P _9))
(def kop_0  (mk K O P _0))
(def kop_hy (mk K O P _hy))
(def kop_eq (mk K O P _eq))

(def ktp_1  (mk K T P _1))
(def ktp_2  (mk K T P _2))
(def ktp_3  (mk K T P _3))
(def ktp_4  (mk K T P _4))
(def ktp_5  (mk K T P _5))
(def ktp_6  (mk K T P _6))
(def ktp_7  (mk K T P _7))
(def ktp_8  (mk K T P _8))
(def ktp_9  (mk K T P _9))
(def ktp_0  (mk K T P _0))
(def ktp_hy (mk K T P _hy))
(def ktp_eq (mk K T P _eq))

(def kcp_1  (mk K C P _1))
(def kcp_2  (mk K C P _2))
(def kcp_3  (mk K C P _3))
(def kcp_4  (mk K C P _4))
(def kcp_5  (mk K C P _5))
(def kcp_6  (mk K C P _6))
(def kcp_7  (mk K C P _7))
(def kcp_8  (mk K C P _8))
(def kcp_9  (mk K C P _9))
(def kcp_0  (mk K C P _0))
(def kcp_hy (mk K C P _hy))
(def kcp_eq (mk K C P _eq))

(def kotp_1  (mk K O T P _1))
(def kotp_2  (mk K O T P _2))
(def kotp_3  (mk K O T P _3))
(def kotp_4  (mk K O T P _4))
(def kotp_5  (mk K O T P _5))
(def kotp_6  (mk K O T P _6))
(def kotp_7  (mk K O T P _7))
(def kotp_8  (mk K O T P _8))
(def kotp_9  (mk K O T P _9))
(def kotp_0  (mk K O T P _0))
(def kotp_hy (mk K O T P _hy))
(def kotp_eq (mk K O T P _eq))

(def kocp_1  (mk K O C P _1))
(def kocp_2  (mk K O C P _2))
(def kocp_3  (mk K O C P _3))
(def kocp_4  (mk K O C P _4))
(def kocp_5  (mk K O C P _5))
(def kocp_6  (mk K O C P _6))
(def kocp_7  (mk K O C P _7))
(def kocp_8  (mk K O C P _8))
(def kocp_9  (mk K O C P _9))
(def kocp_0  (mk K O C P _0))
(def kocp_hy (mk K O C P _hy))
(def kocp_eq (mk K O C P _eq))

(def ktcp_1  (mk K T C P _1))
(def ktcp_2  (mk K T C P _2))
(def ktcp_3  (mk K T C P _3))
(def ktcp_4  (mk K T C P _4))
(def ktcp_5  (mk K T C P _5))
(def ktcp_6  (mk K T C P _6))
(def ktcp_7  (mk K T C P _7))
(def ktcp_8  (mk K T C P _8))
(def ktcp_9  (mk K T C P _9))
(def ktcp_0  (mk K T C P _0))
(def ktcp_hy (mk K T C P _hy))
(def ktcp_eq (mk K T C P _eq))

(def kotcp_1  (mk K O T C P _1))
(def kotcp_2  (mk K O T C P _2))
(def kotcp_3  (mk K O T C P _3))
(def kotcp_4  (mk K O T C P _4))
(def kotcp_5  (mk K O T C P _5))
(def kotcp_6  (mk K O T C P _6))
(def kotcp_7  (mk K O T C P _7))
(def kotcp_8  (mk K O T C P _8))
(def kotcp_9  (mk K O T C P _9))
(def kotcp_0  (mk K O T C P _0))
(def kotcp_hy (mk K O T C P _hy))
(def kotcp_eq (mk K O T C P _eq))

(def ksp_1  (mk K S P _1))
(def ksp_2  (mk K S P _2))
(def ksp_3  (mk K S P _3))
(def ksp_4  (mk K S P _4))
(def ksp_5  (mk K S P _5))
(def ksp_6  (mk K S P _6))
(def ksp_7  (mk K S P _7))
(def ksp_8  (mk K S P _8))
(def ksp_9  (mk K S P _9))
(def ksp_0  (mk K S P _0))
(def ksp_hy (mk K S P _hy))
(def ksp_eq (mk K S P _eq))

(def kosp_1  (mk K O S P _1))
(def kosp_2  (mk K O S P _2))
(def kosp_3  (mk K O S P _3))
(def kosp_4  (mk K O S P _4))
(def kosp_5  (mk K O S P _5))
(def kosp_6  (mk K O S P _6))
(def kosp_7  (mk K O S P _7))
(def kosp_8  (mk K O S P _8))
(def kosp_9  (mk K O S P _9))
(def kosp_0  (mk K O S P _0))
(def kosp_hy (mk K O S P _hy))
(def kosp_eq (mk K O S P _eq))

(def ktsp_1  (mk K T S P _1))
(def ktsp_2  (mk K T S P _2))
(def ktsp_3  (mk K T S P _3))
(def ktsp_4  (mk K T S P _4))
(def ktsp_5  (mk K T S P _5))
(def ktsp_6  (mk K T S P _6))
(def ktsp_7  (mk K T S P _7))
(def ktsp_8  (mk K T S P _8))
(def ktsp_9  (mk K T S P _9))
(def ktsp_0  (mk K T S P _0))
(def ktsp_hy (mk K T S P _hy))
(def ktsp_eq (mk K T S P _eq))

(def kcsp_1  (mk K C S P _1))
(def kcsp_2  (mk K C S P _2))
(def kcsp_3  (mk K C S P _3))
(def kcsp_4  (mk K C S P _4))
(def kcsp_5  (mk K C S P _5))
(def kcsp_6  (mk K C S P _6))
(def kcsp_7  (mk K C S P _7))
(def kcsp_8  (mk K C S P _8))
(def kcsp_9  (mk K C S P _9))
(def kcsp_0  (mk K C S P _0))
(def kcsp_hy (mk K C S P _hy))
(def kcsp_eq (mk K C S P _eq))

(def kotsp_1  (mk K O T S P _1))
(def kotsp_2  (mk K O T S P _2))
(def kotsp_3  (mk K O T S P _3))
(def kotsp_4  (mk K O T S P _4))
(def kotsp_5  (mk K O T S P _5))
(def kotsp_6  (mk K O T S P _6))
(def kotsp_7  (mk K O T S P _7))
(def kotsp_8  (mk K O T S P _8))
(def kotsp_9  (mk K O T S P _9))
(def kotsp_0  (mk K O T S P _0))
(def kotsp_hy (mk K O T S P _hy))
(def kotsp_eq (mk K O T S P _eq))

(def kocsp_1  (mk K O C S P _1))
(def kocsp_2  (mk K O C S P _2))
(def kocsp_3  (mk K O C S P _3))
(def kocsp_4  (mk K O C S P _4))
(def kocsp_5  (mk K O C S P _5))
(def kocsp_6  (mk K O C S P _6))
(def kocsp_7  (mk K O C S P _7))
(def kocsp_8  (mk K O C S P _8))
(def kocsp_9  (mk K O C S P _9))
(def kocsp_0  (mk K O C S P _0))
(def kocsp_hy (mk K O C S P _hy))
(def kocsp_eq (mk K O C S P _eq))

(def ktcsp_1  (mk K T C S P _1))
(def ktcsp_2  (mk K T C S P _2))
(def ktcsp_3  (mk K T C S P _3))
(def ktcsp_4  (mk K T C S P _4))
(def ktcsp_5  (mk K T C S P _5))
(def ktcsp_6  (mk K T C S P _6))
(def ktcsp_7  (mk K T C S P _7))
(def ktcsp_8  (mk K T C S P _8))
(def ktcsp_9  (mk K T C S P _9))
(def ktcsp_0  (mk K T C S P _0))
(def ktcsp_hy (mk K T C S P _hy))
(def ktcsp_eq (mk K T C S P _eq))

(def kotcsp_1  (mk K O T C S P _1))
(def kotcsp_2  (mk K O T C S P _2))
(def kotcsp_3  (mk K O T C S P _3))
(def kotcsp_4  (mk K O T C S P _4))
(def kotcsp_5  (mk K O T C S P _5))
(def kotcsp_6  (mk K O T C S P _6))
(def kotcsp_7  (mk K O T C S P _7))
(def kotcsp_8  (mk K O T C S P _8))
(def kotcsp_9  (mk K O T C S P _9))
(def kotcsp_0  (mk K O T C S P _0))
(def kotcsp_hy (mk K O T C S P _hy))
(def kotcsp_eq (mk K O T C S P _eq))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; alphabetic glyphs
(def k_a (mk K _a))
(def k_b (mk K _b))
(def k_c (mk K _c))
(def k_d (mk K _d))
(def k_e (mk K _e))
(def k_f (mk K _f))
(def k_g (mk K _g))
(def k_h (mk K _h))
(def k_i (mk K _i))
(def k_j (mk K _j))
(def k_k (mk K _k))
(def k_l (mk K _l))
(def k_m (mk K _m))
(def k_n (mk K _n))
(def k_o (mk K _o))
(def k_p (mk K _p))
(def k_q (mk K _q))
(def k_r (mk K _r))
(def k_s (mk K _s))
(def k_t (mk K _t))
(def k_u (mk K _u))
(def k_v (mk K _v))
(def k_w (mk K _w))
(def k_x (mk K _x))
(def k_y (mk K _y))
(def k_z (mk K _z))

(def ko_a (mk K O _a))
(def ko_b (mk K O _b))
(def ko_c (mk K O _c))
(def ko_d (mk K O _d))
(def ko_e (mk K O _e))
(def ko_f (mk K O _f))
(def ko_g (mk K O _g))
(def ko_h (mk K O _h))
(def ko_i (mk K O _i))
(def ko_j (mk K O _j))
(def ko_k (mk K O _k))
(def ko_l (mk K O _l))
(def ko_m (mk K O _m))
(def ko_n (mk K O _n))
(def ko_o (mk K O _o))
(def ko_p (mk K O _p))
(def ko_q (mk K O _q))
(def ko_r (mk K O _r))
(def ko_s (mk K O _s))
(def ko_t (mk K O _t))
(def ko_u (mk K O _u))
(def ko_v (mk K O _v))
(def ko_w (mk K O _w))
(def ko_x (mk K O _x))
(def ko_y (mk K O _y))
(def ko_z (mk K O _z))

(def kt_a (mk K T _a))
(def kt_b (mk K T _b))
(def kt_c (mk K T _c))
(def kt_d (mk K T _d))
(def kt_e (mk K T _e))
(def kt_f (mk K T _f))
(def kt_g (mk K T _g))
(def kt_h (mk K T _h))
(def kt_i (mk K T _i))
(def kt_j (mk K T _j))
(def kt_k (mk K T _k))
(def kt_l (mk K T _l))
(def kt_m (mk K T _m))
(def kt_n (mk K T _n))
(def kt_o (mk K T _o))
(def kt_p (mk K T _p))
(def kt_q (mk K T _q))
(def kt_r (mk K T _r))
(def kt_s (mk K T _s))
(def kt_t (mk K T _t))
(def kt_u (mk K T _u))
(def kt_v (mk K T _v))
(def kt_w (mk K T _w))
(def kt_x (mk K T _x))
(def kt_y (mk K T _y))
(def kt_z (mk K T _z))

(def kc_a (mk K C _a))
(def kc_b (mk K C _b))
(def kc_c (mk K C _c))
(def kc_d (mk K C _d))
(def kc_e (mk K C _e))
(def kc_f (mk K C _f))
(def kc_g (mk K C _g))
(def kc_h (mk K C _h))
(def kc_i (mk K C _i))
(def kc_j (mk K C _j))
(def kc_k (mk K C _k))
(def kc_l (mk K C _l))
(def kc_m (mk K C _m))
(def kc_n (mk K C _n))
(def kc_o (mk K C _o))
(def kc_p (mk K C _p))
(def kc_q (mk K C _q))
(def kc_r (mk K C _r))
(def kc_s (mk K C _s))
(def kc_t (mk K C _t))
(def kc_u (mk K C _u))
(def kc_v (mk K C _v))
(def kc_w (mk K C _w))
(def kc_x (mk K C _x))
(def kc_y (mk K C _y))
(def kc_z (mk K C _z))

(def kot_a (mk K O T _a))
(def kot_b (mk K O T _b))
(def kot_c (mk K O T _c))
(def kot_d (mk K O T _d))
(def kot_e (mk K O T _e))
(def kot_f (mk K O T _f))
(def kot_g (mk K O T _g))
(def kot_h (mk K O T _h))
(def kot_i (mk K O T _i))
(def kot_j (mk K O T _j))
(def kot_k (mk K O T _k))
(def kot_l (mk K O T _l))
(def kot_m (mk K O T _m))
(def kot_n (mk K O T _n))
(def kot_o (mk K O T _o))
(def kot_p (mk K O T _p))
(def kot_q (mk K O T _q))
(def kot_r (mk K O T _r))
(def kot_s (mk K O T _s))
(def kot_t (mk K O T _t))
(def kot_u (mk K O T _u))
(def kot_v (mk K O T _v))
(def kot_w (mk K O T _w))
(def kot_x (mk K O T _x))
(def kot_y (mk K O T _y))
(def kot_z (mk K O T _z))

(def koc_a (mk K O C _a))
(def koc_b (mk K O C _b))
(def koc_c (mk K O C _c))
(def koc_d (mk K O C _d))
(def koc_e (mk K O C _e))
(def koc_f (mk K O C _f))
(def koc_g (mk K O C _g))
(def koc_h (mk K O C _h))
(def koc_i (mk K O C _i))
(def koc_j (mk K O C _j))
(def koc_k (mk K O C _k))
(def koc_l (mk K O C _l))
(def koc_m (mk K O C _m))
(def koc_n (mk K O C _n))
(def koc_o (mk K O C _o))
(def koc_p (mk K O C _p))
(def koc_q (mk K O C _q))
(def koc_r (mk K O C _r))
(def koc_s (mk K O C _s))
(def koc_t (mk K O C _t))
(def koc_u (mk K O C _u))
(def koc_v (mk K O C _v))
(def koc_w (mk K O C _w))
(def koc_x (mk K O C _x))
(def koc_y (mk K O C _y))
(def koc_z (mk K O C _z))

(def ktc_a (mk K T C _a))
(def ktc_b (mk K T C _b))
(def ktc_c (mk K T C _c))
(def ktc_d (mk K T C _d))
(def ktc_e (mk K T C _e))
(def ktc_f (mk K T C _f))
(def ktc_g (mk K T C _g))
(def ktc_h (mk K T C _h))
(def ktc_i (mk K T C _i))
(def ktc_j (mk K T C _j))
(def ktc_k (mk K T C _k))
(def ktc_l (mk K T C _l))
(def ktc_m (mk K T C _m))
(def ktc_n (mk K T C _n))
(def ktc_o (mk K T C _o))
(def ktc_p (mk K T C _p))
(def ktc_q (mk K T C _q))
(def ktc_r (mk K T C _r))
(def ktc_s (mk K T C _s))
(def ktc_t (mk K T C _t))
(def ktc_u (mk K T C _u))
(def ktc_v (mk K T C _v))
(def ktc_w (mk K T C _w))
(def ktc_x (mk K T C _x))
(def ktc_y (mk K T C _y))
(def ktc_z (mk K T C _z))

(def kotc_a (mk K O T C _a))
(def kotc_b (mk K O T C _b))
(def kotc_c (mk K O T C _c))
(def kotc_d (mk K O T C _d))
(def kotc_e (mk K O T C _e))
(def kotc_f (mk K O T C _f))
(def kotc_g (mk K O T C _g))
(def kotc_h (mk K O T C _h))
(def kotc_i (mk K O T C _i))
(def kotc_j (mk K O T C _j))
(def kotc_k (mk K O T C _k))
(def kotc_l (mk K O T C _l))
(def kotc_m (mk K O T C _m))
(def kotc_n (mk K O T C _n))
(def kotc_o (mk K O T C _o))
(def kotc_p (mk K O T C _p))
(def kotc_q (mk K O T C _q))
(def kotc_r (mk K O T C _r))
(def kotc_s (mk K O T C _s))
(def kotc_t (mk K O T C _t))
(def kotc_u (mk K O T C _u))
(def kotc_v (mk K O T C _v))
(def kotc_w (mk K O T C _w))
(def kotc_x (mk K O T C _x))
(def kotc_y (mk K O T C _y))
(def kotc_z (mk K O T C _z))

(def ks_a (mk K S _a))
(def ks_b (mk K S _b))
(def ks_c (mk K S _c))
(def ks_d (mk K S _d))
(def ks_e (mk K S _e))
(def ks_f (mk K S _f))
(def ks_g (mk K S _g))
(def ks_h (mk K S _h))
(def ks_i (mk K S _i))
(def ks_j (mk K S _j))
(def ks_k (mk K S _k))
(def ks_l (mk K S _l))
(def ks_m (mk K S _m))
(def ks_n (mk K S _n))
(def ks_o (mk K S _o))
(def ks_p (mk K S _p))
(def ks_q (mk K S _q))
(def ks_r (mk K S _r))
(def ks_s (mk K S _s))
(def ks_t (mk K S _t))
(def ks_u (mk K S _u))
(def ks_v (mk K S _v))
(def ks_w (mk K S _w))
(def ks_x (mk K S _x))
(def ks_y (mk K S _y))
(def ks_z (mk K S _z))

(def kos_a (mk K O S _a))
(def kos_b (mk K O S _b))
(def kos_c (mk K O S _c))
(def kos_d (mk K O S _d))
(def kos_e (mk K O S _e))
(def kos_f (mk K O S _f))
(def kos_g (mk K O S _g))
(def kos_h (mk K O S _h))
(def kos_i (mk K O S _i))
(def kos_j (mk K O S _j))
(def kos_k (mk K O S _k))
(def kos_l (mk K O S _l))
(def kos_m (mk K O S _m))
(def kos_n (mk K O S _n))
(def kos_o (mk K O S _o))
(def kos_p (mk K O S _p))
(def kos_q (mk K O S _q))
(def kos_r (mk K O S _r))
(def kos_s (mk K O S _s))
(def kos_t (mk K O S _t))
(def kos_u (mk K O S _u))
(def kos_v (mk K O S _v))
(def kos_w (mk K O S _w))
(def kos_x (mk K O S _x))
(def kos_y (mk K O S _y))
(def kos_z (mk K O S _z))

(def kts_a (mk K T S _a))
(def kts_b (mk K T S _b))
(def kts_c (mk K T S _c))
(def kts_d (mk K T S _d))
(def kts_e (mk K T S _e))
(def kts_f (mk K T S _f))
(def kts_g (mk K T S _g))
(def kts_h (mk K T S _h))
(def kts_i (mk K T S _i))
(def kts_j (mk K T S _j))
(def kts_k (mk K T S _k))
(def kts_l (mk K T S _l))
(def kts_m (mk K T S _m))
(def kts_n (mk K T S _n))
(def kts_o (mk K T S _o))
(def kts_p (mk K T S _p))
(def kts_q (mk K T S _q))
(def kts_r (mk K T S _r))
(def kts_s (mk K T S _s))
(def kts_t (mk K T S _t))
(def kts_u (mk K T S _u))
(def kts_v (mk K T S _v))
(def kts_w (mk K T S _w))
(def kts_x (mk K T S _x))
(def kts_y (mk K T S _y))
(def kts_z (mk K T S _z))

(def kcs_a (mk K C S _a))
(def kcs_b (mk K C S _b))
(def kcs_c (mk K C S _c))
(def kcs_d (mk K C S _d))
(def kcs_e (mk K C S _e))
(def kcs_f (mk K C S _f))
(def kcs_g (mk K C S _g))
(def kcs_h (mk K C S _h))
(def kcs_i (mk K C S _i))
(def kcs_j (mk K C S _j))
(def kcs_k (mk K C S _k))
(def kcs_l (mk K C S _l))
(def kcs_m (mk K C S _m))
(def kcs_n (mk K C S _n))
(def kcs_o (mk K C S _o))
(def kcs_p (mk K C S _p))
(def kcs_q (mk K C S _q))
(def kcs_r (mk K C S _r))
(def kcs_s (mk K C S _s))
(def kcs_t (mk K C S _t))
(def kcs_u (mk K C S _u))
(def kcs_v (mk K C S _v))
(def kcs_w (mk K C S _w))
(def kcs_x (mk K C S _x))
(def kcs_y (mk K C S _y))
(def kcs_z (mk K C S _z))

(def kots_a (mk K O T S _a))
(def kots_b (mk K O T S _b))
(def kots_c (mk K O T S _c))
(def kots_d (mk K O T S _d))
(def kots_e (mk K O T S _e))
(def kots_f (mk K O T S _f))
(def kots_g (mk K O T S _g))
(def kots_h (mk K O T S _h))
(def kots_i (mk K O T S _i))
(def kots_j (mk K O T S _j))
(def kots_k (mk K O T S _k))
(def kots_l (mk K O T S _l))
(def kots_m (mk K O T S _m))
(def kots_n (mk K O T S _n))
(def kots_o (mk K O T S _o))
(def kots_p (mk K O T S _p))
(def kots_q (mk K O T S _q))
(def kots_r (mk K O T S _r))
(def kots_s (mk K O T S _s))
(def kots_t (mk K O T S _t))
(def kots_u (mk K O T S _u))
(def kots_v (mk K O T S _v))
(def kots_w (mk K O T S _w))
(def kots_x (mk K O T S _x))
(def kots_y (mk K O T S _y))
(def kots_z (mk K O T S _z))

(def kocs_a (mk K O C S _a))
(def kocs_b (mk K O C S _b))
(def kocs_c (mk K O C S _c))
(def kocs_d (mk K O C S _d))
(def kocs_e (mk K O C S _e))
(def kocs_f (mk K O C S _f))
(def kocs_g (mk K O C S _g))
(def kocs_h (mk K O C S _h))
(def kocs_i (mk K O C S _i))
(def kocs_j (mk K O C S _j))
(def kocs_k (mk K O C S _k))
(def kocs_l (mk K O C S _l))
(def kocs_m (mk K O C S _m))
(def kocs_n (mk K O C S _n))
(def kocs_o (mk K O C S _o))
(def kocs_p (mk K O C S _p))
(def kocs_q (mk K O C S _q))
(def kocs_r (mk K O C S _r))
(def kocs_s (mk K O C S _s))
(def kocs_t (mk K O C S _t))
(def kocs_u (mk K O C S _u))
(def kocs_v (mk K O C S _v))
(def kocs_w (mk K O C S _w))
(def kocs_x (mk K O C S _x))
(def kocs_y (mk K O C S _y))
(def kocs_z (mk K O C S _z))

(def ktcs_a (mk K T C S _a))
(def ktcs_b (mk K T C S _b))
(def ktcs_c (mk K T C S _c))
(def ktcs_d (mk K T C S _d))
(def ktcs_e (mk K T C S _e))
(def ktcs_f (mk K T C S _f))
(def ktcs_g (mk K T C S _g))
(def ktcs_h (mk K T C S _h))
(def ktcs_i (mk K T C S _i))
(def ktcs_j (mk K T C S _j))
(def ktcs_k (mk K T C S _k))
(def ktcs_l (mk K T C S _l))
(def ktcs_m (mk K T C S _m))
(def ktcs_n (mk K T C S _n))
(def ktcs_o (mk K T C S _o))
(def ktcs_p (mk K T C S _p))
(def ktcs_q (mk K T C S _q))
(def ktcs_r (mk K T C S _r))
(def ktcs_s (mk K T C S _s))
(def ktcs_t (mk K T C S _t))
(def ktcs_u (mk K T C S _u))
(def ktcs_v (mk K T C S _v))
(def ktcs_w (mk K T C S _w))
(def ktcs_x (mk K T C S _x))
(def ktcs_y (mk K T C S _y))
(def ktcs_z (mk K T C S _z))

(def kotcs_a (mk K O T C S _a))
(def kotcs_b (mk K O T C S _b))
(def kotcs_c (mk K O T C S _c))
(def kotcs_d (mk K O T C S _d))
(def kotcs_e (mk K O T C S _e))
(def kotcs_f (mk K O T C S _f))
(def kotcs_g (mk K O T C S _g))
(def kotcs_h (mk K O T C S _h))
(def kotcs_i (mk K O T C S _i))
(def kotcs_j (mk K O T C S _j))
(def kotcs_k (mk K O T C S _k))
(def kotcs_l (mk K O T C S _l))
(def kotcs_m (mk K O T C S _m))
(def kotcs_n (mk K O T C S _n))
(def kotcs_o (mk K O T C S _o))
(def kotcs_p (mk K O T C S _p))
(def kotcs_q (mk K O T C S _q))
(def kotcs_r (mk K O T C S _r))
(def kotcs_s (mk K O T C S _s))
(def kotcs_t (mk K O T C S _t))
(def kotcs_u (mk K O T C S _u))
(def kotcs_v (mk K O T C S _v))
(def kotcs_w (mk K O T C S _w))
(def kotcs_x (mk K O T C S _x))
(def kotcs_y (mk K O T C S _y))
(def kotcs_z (mk K O T C S _z))

(def kp_a (mk K P _a))
(def kp_b (mk K P _b))
(def kp_c (mk K P _c))
(def kp_d (mk K P _d))
(def kp_e (mk K P _e))
(def kp_f (mk K P _f))
(def kp_g (mk K P _g))
(def kp_h (mk K P _h))
(def kp_i (mk K P _i))
(def kp_j (mk K P _j))
(def kp_k (mk K P _k))
(def kp_l (mk K P _l))
(def kp_m (mk K P _m))
(def kp_n (mk K P _n))
(def kp_o (mk K P _o))
(def kp_p (mk K P _p))
(def kp_q (mk K P _q))
(def kp_r (mk K P _r))
(def kp_s (mk K P _s))
(def kp_t (mk K P _t))
(def kp_u (mk K P _u))
(def kp_v (mk K P _v))
(def kp_w (mk K P _w))
(def kp_x (mk K P _x))
(def kp_y (mk K P _y))
(def kp_z (mk K P _z))

(def kop_a (mk K O P _a))
(def kop_b (mk K O P _b))
(def kop_c (mk K O P _c))
(def kop_d (mk K O P _d))
(def kop_e (mk K O P _e))
(def kop_f (mk K O P _f))
(def kop_g (mk K O P _g))
(def kop_h (mk K O P _h))
(def kop_i (mk K O P _i))
(def kop_j (mk K O P _j))
(def kop_k (mk K O P _k))
(def kop_l (mk K O P _l))
(def kop_m (mk K O P _m))
(def kop_n (mk K O P _n))
(def kop_o (mk K O P _o))
(def kop_p (mk K O P _p))
(def kop_q (mk K O P _q))
(def kop_r (mk K O P _r))
(def kop_s (mk K O P _s))
(def kop_t (mk K O P _t))
(def kop_u (mk K O P _u))
(def kop_v (mk K O P _v))
(def kop_w (mk K O P _w))
(def kop_x (mk K O P _x))
(def kop_y (mk K O P _y))
(def kop_z (mk K O P _z))

(def ktp_a (mk K T P _a))
(def ktp_b (mk K T P _b))
(def ktp_c (mk K T P _c))
(def ktp_d (mk K T P _d))
(def ktp_e (mk K T P _e))
(def ktp_f (mk K T P _f))
(def ktp_g (mk K T P _g))
(def ktp_h (mk K T P _h))
(def ktp_i (mk K T P _i))
(def ktp_j (mk K T P _j))
(def ktp_k (mk K T P _k))
(def ktp_l (mk K T P _l))
(def ktp_m (mk K T P _m))
(def ktp_n (mk K T P _n))
(def ktp_o (mk K T P _o))
(def ktp_p (mk K T P _p))
(def ktp_q (mk K T P _q))
(def ktp_r (mk K T P _r))
(def ktp_s (mk K T P _s))
(def ktp_t (mk K T P _t))
(def ktp_u (mk K T P _u))
(def ktp_v (mk K T P _v))
(def ktp_w (mk K T P _w))
(def ktp_x (mk K T P _x))
(def ktp_y (mk K T P _y))
(def ktp_z (mk K T P _z))

(def kcp_a (mk K C P _a))
(def kcp_b (mk K C P _b))
(def kcp_c (mk K C P _c))
(def kcp_d (mk K C P _d))
(def kcp_e (mk K C P _e))
(def kcp_f (mk K C P _f))
(def kcp_g (mk K C P _g))
(def kcp_h (mk K C P _h))
(def kcp_i (mk K C P _i))
(def kcp_j (mk K C P _j))
(def kcp_k (mk K C P _k))
(def kcp_l (mk K C P _l))
(def kcp_m (mk K C P _m))
(def kcp_n (mk K C P _n))
(def kcp_o (mk K C P _o))
(def kcp_p (mk K C P _p))
(def kcp_q (mk K C P _q))
(def kcp_r (mk K C P _r))
(def kcp_s (mk K C P _s))
(def kcp_t (mk K C P _t))
(def kcp_u (mk K C P _u))
(def kcp_v (mk K C P _v))
(def kcp_w (mk K C P _w))
(def kcp_x (mk K C P _x))
(def kcp_y (mk K C P _y))
(def kcp_z (mk K C P _z))

(def kotp_a (mk K O T P _a))
(def kotp_b (mk K O T P _b))
(def kotp_c (mk K O T P _c))
(def kotp_d (mk K O T P _d))
(def kotp_e (mk K O T P _e))
(def kotp_f (mk K O T P _f))
(def kotp_g (mk K O T P _g))
(def kotp_h (mk K O T P _h))
(def kotp_i (mk K O T P _i))
(def kotp_j (mk K O T P _j))
(def kotp_k (mk K O T P _k))
(def kotp_l (mk K O T P _l))
(def kotp_m (mk K O T P _m))
(def kotp_n (mk K O T P _n))
(def kotp_o (mk K O T P _o))
(def kotp_p (mk K O T P _p))
(def kotp_q (mk K O T P _q))
(def kotp_r (mk K O T P _r))
(def kotp_s (mk K O T P _s))
(def kotp_t (mk K O T P _t))
(def kotp_u (mk K O T P _u))
(def kotp_v (mk K O T P _v))
(def kotp_w (mk K O T P _w))
(def kotp_x (mk K O T P _x))
(def kotp_y (mk K O T P _y))
(def kotp_z (mk K O T P _z))

(def kocp_a (mk K O C P _a))
(def kocp_b (mk K O C P _b))
(def kocp_c (mk K O C P _c))
(def kocp_d (mk K O C P _d))
(def kocp_e (mk K O C P _e))
(def kocp_f (mk K O C P _f))
(def kocp_g (mk K O C P _g))
(def kocp_h (mk K O C P _h))
(def kocp_i (mk K O C P _i))
(def kocp_j (mk K O C P _j))
(def kocp_k (mk K O C P _k))
(def kocp_l (mk K O C P _l))
(def kocp_m (mk K O C P _m))
(def kocp_n (mk K O C P _n))
(def kocp_o (mk K O C P _o))
(def kocp_p (mk K O C P _p))
(def kocp_q (mk K O C P _q))
(def kocp_r (mk K O C P _r))
(def kocp_s (mk K O C P _s))
(def kocp_t (mk K O C P _t))
(def kocp_u (mk K O C P _u))
(def kocp_v (mk K O C P _v))
(def kocp_w (mk K O C P _w))
(def kocp_x (mk K O C P _x))
(def kocp_y (mk K O C P _y))
(def kocp_z (mk K O C P _z))

(def ktcp_a (mk K T C P _a))
(def ktcp_b (mk K T C P _b))
(def ktcp_c (mk K T C P _c))
(def ktcp_d (mk K T C P _d))
(def ktcp_e (mk K T C P _e))
(def ktcp_f (mk K T C P _f))
(def ktcp_g (mk K T C P _g))
(def ktcp_h (mk K T C P _h))
(def ktcp_i (mk K T C P _i))
(def ktcp_j (mk K T C P _j))
(def ktcp_k (mk K T C P _k))
(def ktcp_l (mk K T C P _l))
(def ktcp_m (mk K T C P _m))
(def ktcp_n (mk K T C P _n))
(def ktcp_o (mk K T C P _o))
(def ktcp_p (mk K T C P _p))
(def ktcp_q (mk K T C P _q))
(def ktcp_r (mk K T C P _r))
(def ktcp_s (mk K T C P _s))
(def ktcp_t (mk K T C P _t))
(def ktcp_u (mk K T C P _u))
(def ktcp_v (mk K T C P _v))
(def ktcp_w (mk K T C P _w))
(def ktcp_x (mk K T C P _x))
(def ktcp_y (mk K T C P _y))
(def ktcp_z (mk K T C P _z))

(def kotcp_a (mk K O T C P _a))
(def kotcp_b (mk K O T C P _b))
(def kotcp_c (mk K O T C P _c))
(def kotcp_d (mk K O T C P _d))
(def kotcp_e (mk K O T C P _e))
(def kotcp_f (mk K O T C P _f))
(def kotcp_g (mk K O T C P _g))
(def kotcp_h (mk K O T C P _h))
(def kotcp_i (mk K O T C P _i))
(def kotcp_j (mk K O T C P _j))
(def kotcp_k (mk K O T C P _k))
(def kotcp_l (mk K O T C P _l))
(def kotcp_m (mk K O T C P _m))
(def kotcp_n (mk K O T C P _n))
(def kotcp_o (mk K O T C P _o))
(def kotcp_p (mk K O T C P _p))
(def kotcp_q (mk K O T C P _q))
(def kotcp_r (mk K O T C P _r))
(def kotcp_s (mk K O T C P _s))
(def kotcp_t (mk K O T C P _t))
(def kotcp_u (mk K O T C P _u))
(def kotcp_v (mk K O T C P _v))
(def kotcp_w (mk K O T C P _w))
(def kotcp_x (mk K O T C P _x))
(def kotcp_y (mk K O T C P _y))
(def kotcp_z (mk K O T C P _z))

(def ksp_a (mk K S P _a))
(def ksp_b (mk K S P _b))
(def ksp_c (mk K S P _c))
(def ksp_d (mk K S P _d))
(def ksp_e (mk K S P _e))
(def ksp_f (mk K S P _f))
(def ksp_g (mk K S P _g))
(def ksp_h (mk K S P _h))
(def ksp_i (mk K S P _i))
(def ksp_j (mk K S P _j))
(def ksp_k (mk K S P _k))
(def ksp_l (mk K S P _l))
(def ksp_m (mk K S P _m))
(def ksp_n (mk K S P _n))
(def ksp_o (mk K S P _o))
(def ksp_p (mk K S P _p))
(def ksp_q (mk K S P _q))
(def ksp_r (mk K S P _r))
(def ksp_s (mk K S P _s))
(def ksp_t (mk K S P _t))
(def ksp_u (mk K S P _u))
(def ksp_v (mk K S P _v))
(def ksp_w (mk K S P _w))
(def ksp_x (mk K S P _x))
(def ksp_y (mk K S P _y))
(def ksp_z (mk K S P _z))

(def kosp_a (mk K O S P _a))
(def kosp_b (mk K O S P _b))
(def kosp_c (mk K O S P _c))
(def kosp_d (mk K O S P _d))
(def kosp_e (mk K O S P _e))
(def kosp_f (mk K O S P _f))
(def kosp_g (mk K O S P _g))
(def kosp_h (mk K O S P _h))
(def kosp_i (mk K O S P _i))
(def kosp_j (mk K O S P _j))
(def kosp_k (mk K O S P _k))
(def kosp_l (mk K O S P _l))
(def kosp_m (mk K O S P _m))
(def kosp_n (mk K O S P _n))
(def kosp_o (mk K O S P _o))
(def kosp_p (mk K O S P _p))
(def kosp_q (mk K O S P _q))
(def kosp_r (mk K O S P _r))
(def kosp_s (mk K O S P _s))
(def kosp_t (mk K O S P _t))
(def kosp_u (mk K O S P _u))
(def kosp_v (mk K O S P _v))
(def kosp_w (mk K O S P _w))
(def kosp_x (mk K O S P _x))
(def kosp_y (mk K O S P _y))
(def kosp_z (mk K O S P _z))

(def ktsp_a (mk K T S P _a))
(def ktsp_b (mk K T S P _b))
(def ktsp_c (mk K T S P _c))
(def ktsp_d (mk K T S P _d))
(def ktsp_e (mk K T S P _e))
(def ktsp_f (mk K T S P _f))
(def ktsp_g (mk K T S P _g))
(def ktsp_h (mk K T S P _h))
(def ktsp_i (mk K T S P _i))
(def ktsp_j (mk K T S P _j))
(def ktsp_k (mk K T S P _k))
(def ktsp_l (mk K T S P _l))
(def ktsp_m (mk K T S P _m))
(def ktsp_n (mk K T S P _n))
(def ktsp_o (mk K T S P _o))
(def ktsp_p (mk K T S P _p))
(def ktsp_q (mk K T S P _q))
(def ktsp_r (mk K T S P _r))
(def ktsp_s (mk K T S P _s))
(def ktsp_t (mk K T S P _t))
(def ktsp_u (mk K T S P _u))
(def ktsp_v (mk K T S P _v))
(def ktsp_w (mk K T S P _w))
(def ktsp_x (mk K T S P _x))
(def ktsp_y (mk K T S P _y))
(def ktsp_z (mk K T S P _z))

(def kcsp_a (mk K C S P _a))
(def kcsp_b (mk K C S P _b))
(def kcsp_c (mk K C S P _c))
(def kcsp_d (mk K C S P _d))
(def kcsp_e (mk K C S P _e))
(def kcsp_f (mk K C S P _f))
(def kcsp_g (mk K C S P _g))
(def kcsp_h (mk K C S P _h))
(def kcsp_i (mk K C S P _i))
(def kcsp_j (mk K C S P _j))
(def kcsp_k (mk K C S P _k))
(def kcsp_l (mk K C S P _l))
(def kcsp_m (mk K C S P _m))
(def kcsp_n (mk K C S P _n))
(def kcsp_o (mk K C S P _o))
(def kcsp_p (mk K C S P _p))
(def kcsp_q (mk K C S P _q))
(def kcsp_r (mk K C S P _r))
(def kcsp_s (mk K C S P _s))
(def kcsp_t (mk K C S P _t))
(def kcsp_u (mk K C S P _u))
(def kcsp_v (mk K C S P _v))
(def kcsp_w (mk K C S P _w))
(def kcsp_x (mk K C S P _x))
(def kcsp_y (mk K C S P _y))
(def kcsp_z (mk K C S P _z))

(def kotsp_a (mk K O T S P _a))
(def kotsp_b (mk K O T S P _b))
(def kotsp_c (mk K O T S P _c))
(def kotsp_d (mk K O T S P _d))
(def kotsp_e (mk K O T S P _e))
(def kotsp_f (mk K O T S P _f))
(def kotsp_g (mk K O T S P _g))
(def kotsp_h (mk K O T S P _h))
(def kotsp_i (mk K O T S P _i))
(def kotsp_j (mk K O T S P _j))
(def kotsp_k (mk K O T S P _k))
(def kotsp_l (mk K O T S P _l))
(def kotsp_m (mk K O T S P _m))
(def kotsp_n (mk K O T S P _n))
(def kotsp_o (mk K O T S P _o))
(def kotsp_p (mk K O T S P _p))
(def kotsp_q (mk K O T S P _q))
(def kotsp_r (mk K O T S P _r))
(def kotsp_s (mk K O T S P _s))
(def kotsp_t (mk K O T S P _t))
(def kotsp_u (mk K O T S P _u))
(def kotsp_v (mk K O T S P _v))
(def kotsp_w (mk K O T S P _w))
(def kotsp_x (mk K O T S P _x))
(def kotsp_y (mk K O T S P _y))
(def kotsp_z (mk K O T S P _z))

(def kocsp_a (mk K O C S P _a))
(def kocsp_b (mk K O C S P _b))
(def kocsp_c (mk K O C S P _c))
(def kocsp_d (mk K O C S P _d))
(def kocsp_e (mk K O C S P _e))
(def kocsp_f (mk K O C S P _f))
(def kocsp_g (mk K O C S P _g))
(def kocsp_h (mk K O C S P _h))
(def kocsp_i (mk K O C S P _i))
(def kocsp_j (mk K O C S P _j))
(def kocsp_k (mk K O C S P _k))
(def kocsp_l (mk K O C S P _l))
(def kocsp_m (mk K O C S P _m))
(def kocsp_n (mk K O C S P _n))
(def kocsp_o (mk K O C S P _o))
(def kocsp_p (mk K O C S P _p))
(def kocsp_q (mk K O C S P _q))
(def kocsp_r (mk K O C S P _r))
(def kocsp_s (mk K O C S P _s))
(def kocsp_t (mk K O C S P _t))
(def kocsp_u (mk K O C S P _u))
(def kocsp_v (mk K O C S P _v))
(def kocsp_w (mk K O C S P _w))
(def kocsp_x (mk K O C S P _x))
(def kocsp_y (mk K O C S P _y))
(def kocsp_z (mk K O C S P _z))

(def ktcsp_a (mk K T C S P _a))
(def ktcsp_b (mk K T C S P _b))
(def ktcsp_c (mk K T C S P _c))
(def ktcsp_d (mk K T C S P _d))
(def ktcsp_e (mk K T C S P _e))
(def ktcsp_f (mk K T C S P _f))
(def ktcsp_g (mk K T C S P _g))
(def ktcsp_h (mk K T C S P _h))
(def ktcsp_i (mk K T C S P _i))
(def ktcsp_j (mk K T C S P _j))
(def ktcsp_k (mk K T C S P _k))
(def ktcsp_l (mk K T C S P _l))
(def ktcsp_m (mk K T C S P _m))
(def ktcsp_n (mk K T C S P _n))
(def ktcsp_o (mk K T C S P _o))
(def ktcsp_p (mk K T C S P _p))
(def ktcsp_q (mk K T C S P _q))
(def ktcsp_r (mk K T C S P _r))
(def ktcsp_s (mk K T C S P _s))
(def ktcsp_t (mk K T C S P _t))
(def ktcsp_u (mk K T C S P _u))
(def ktcsp_v (mk K T C S P _v))
(def ktcsp_w (mk K T C S P _w))
(def ktcsp_x (mk K T C S P _x))
(def ktcsp_y (mk K T C S P _y))
(def ktcsp_z (mk K T C S P _z))

(def kotcsp_a (mk K O T C S P _a))
(def kotcsp_b (mk K O T C S P _b))
(def kotcsp_c (mk K O T C S P _c))
(def kotcsp_d (mk K O T C S P _d))
(def kotcsp_e (mk K O T C S P _e))
(def kotcsp_f (mk K O T C S P _f))
(def kotcsp_g (mk K O T C S P _g))
(def kotcsp_h (mk K O T C S P _h))
(def kotcsp_i (mk K O T C S P _i))
(def kotcsp_j (mk K O T C S P _j))
(def kotcsp_k (mk K O T C S P _k))
(def kotcsp_l (mk K O T C S P _l))
(def kotcsp_m (mk K O T C S P _m))
(def kotcsp_n (mk K O T C S P _n))
(def kotcsp_o (mk K O T C S P _o))
(def kotcsp_p (mk K O T C S P _p))
(def kotcsp_q (mk K O T C S P _q))
(def kotcsp_r (mk K O T C S P _r))
(def kotcsp_s (mk K O T C S P _s))
(def kotcsp_t (mk K O T C S P _t))
(def kotcsp_u (mk K O T C S P _u))
(def kotcsp_v (mk K O T C S P _v))
(def kotcsp_w (mk K O T C S P _w))
(def kotcsp_x (mk K O T C S P _x))
(def kotcsp_y (mk K O T C S P _y))
(def kotcsp_z (mk K O T C S P _z))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
